### ISSUE TITLE
Set up unit testing for CCM code

### ISSUE THREAD

**Issue by frapposelli** [kubernetes/cloud-provider-vsphere#10]
This would ideally run a `make test` on the tide testing infrastructure, this issue is for the creation of the hook, `make test` can be a noop for now.

/kind feature
/help

**Comment by akutz** [comment]
Hi @figo,

To be clear, @frapposelli cares little about the test output at this time. His concern is that the `images` target is executed in order to ensure that the images are built and deployed to a remote registry to make it simple for others to obtain a working cloud provider.
