### ISSUE TITLE
Refactor NodeManager to use PropertyCollector

### ISSUE THREAD

**Issue by frapposelli** [kubernetes/cloud-provider-vsphere#11]
Currently state changes within vCenter are discovered by discovering/manually fetching the Moref and then polling the object for changes, we should refactor this code to use the `PropertyCollector` service offered in vCenter >4.1

/kind feature

**Comment by frapposelli** [comment]
@dvonthenen is tackling this refactor as part of #35

**Comment by dvonthenen** [comment]
yup! the intersection between the two is a lot. took what you had as a base and working on it. I should have this early next week.

**Comment by dvonthenen** [comment]
Submitted PR: https://github.com/kubernetes/cloud-provider-vsphere/pull/43
