### ISSUE TITLE
csi: should /etc/cloud/vsphere.conf be required?

### ISSUE THREAD

**Issue by codenrhoden** [kubernetes/cloud-provider-vsphere#115]
While testing CSI, I came across this and wanted to capture it before I forgot.

When starting the CSI plugin on a new node, I get an error:
```
$ ./vsphere-csi
FATA[0000] Failed to open /etc/cloud/vsphere.conf . Err: open /etc/cloud/vsphere.conf: no such file or directory
```

I was expecting to be able to set all the needed parameters via env var for my simple case, but if the referenced config file is not present, the plugin does not start up. Furthermore, when looking at the code [here](https://github.com/kubernetes/cloud-provider-vsphere/blob/a06c86025167f56f988f800c5f132bf1f778cbab/pkg/common/config/config.go#L344) It looks like the config file would have precedence over env vars. I'm used to the other way around -- using env vars to override something that may be in a config file.

I wanted to use this issue to clarify that behavior and see if we could agree on what is desired. And then document it.

**Comment by dvonthenen** [comment]
I believe this was addressed in the change made in this PR: https://github.com/kubernetes/cloud-provider-vsphere/pull/112/
