### ISSUE TITLE
Investigate using k8s.io/klog instead of glog

### ISSUE THREAD

**Issue by andrewsykim** [kubernetes/cloud-provider-vsphere#137]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind feature

**What happened**:
We should investigate using k8s.io/klog instead of glog. `klog` is a fork of `glog` so we should validate that there are no breaking changes in the way we use glog if we were to switch.

**Comment by dvonthenen** [comment]
There was also small additional discussion about consolidating to use a single logger. Currently using glog(->klog) and logrus. I know logrus is used in the gocsi framework/skeleton code that was created... so not entirely sure how feasible this is.

**Comment by dvonthenen** [comment]
Implemented and currently testing...

**Comment by dvonthenen** [comment]
PR was merged
/close
