### ISSUE TITLE
Create vcpctl tool to facilitate CCM provisioning

### ISSUE THREAD

**Issue by fanzhangio** [kubernetes/cloud-provider-vsphere#15]
**FEATURE REQUEST**:

>
> /kind feature

Deploying a cloud provider on vSphere is a task that has many prerequisites, from creating a user with correct roles on vCenter, to creating a correct configuration for the service. When migrating users from the in-tree version there's also a need to convert configuration files and to make sure sensitive credentials are stored safely.

The tool should fulfill these needs:

- [ ] Perform vSphere configuration health check:
  - disk.uuid set on esx
  - network reachability
- [ ] Create vSphere role with minimal set of permissions
- [x] Create vSphere solution user (generate keypair), to be used with CCM
- [ ] Convert old in-tree `vsphere.conf` configuration files to new configmap

**Comment by dougm** [comment]
@fanzhangio a few pointers:

## disk.EnableUUID

This is a VM "extra config" property, can be set using:
```
% govc vm.change -e disk.enableUUID=1 -vm vm-name
```

See: https://github.com/vmware/govmomi/blob/056ad0d4991b2ae3900603480c1d27583ffeaa1d/govc/vm/change.go#L132-L134

Get using:
```
% govc vm.info -e -vm vm-name | grep disk.enableUUID
```

See: https://github.com/vmware/govmomi/blob/056ad0d4991b2ae3900603480c1d27583ffeaa1d/govc/vm/info.go#L335-L340

## sso

Creating a solution user: https://github.com/vmware/kubernetes/issues/489

See: https://github.com/vmware/govmomi/blob/master/govc/sso/user/create.go

## roles

Roles can be created, updated, listed using the govc role.* commands: https://github.com/vmware/govmomi/blob/master/govc/USAGE.md#rolecreate

See: https://github.com/vmware/govmomi/tree/master/govc/role

**Comment by fanzhangio** [comment]
vcpctl might also need to implement session login/logout as well ?
@frapposelli @dougm
