### ISSUE TITLE
Please update Travis-CI env vars / fixes Aggregation layer e2e conformance test

### ISSUE THREAD

**Issue by akutz** [kubernetes/cloud-provider-vsphere#152]
Hi @frapposelli,

Please update the following Travis-CI environment variables:

| Name | Value |
|-------|------|
| `SK8_URL` | `https://raw.githubusercontent.com/vmware/simple-k8s-test-env/v0.2.1/sk8.sh` |
| `E2E_IMAGE` | `gcr.io/kubernetes-conformance-testing/sk8e2e:v20190304-v0.2.1-1-g6d7e0f0` |

The new script and image support the Kubernetes aggregation layer, thereby fixing the broken e2e conformance test `[sig-api-machinery] Aggregator [It] Should be able to support the 1.10 Sample API Server using the current Aggregator [Conformance]`.

Related to https://github.com/vmware/simple-k8s-test-env/pull/10 and https://github.com/vmware/simple-k8s-test-env/pull/12.

cc @figo @imkin

**Comment by frapposelli** [comment]
done!
