### ISSUE TITLE
The test "TestGRPCServerClient" is flaky on Prow

### ISSUE THREAD

**Issue by akutz** [kubernetes/cloud-provider-vsphere#160]
/kind bug
/assign @dvonthenen 

**What happened**:
The test `TestGRPCServerClient` fails occasionally on Prow.

**What you expected to happen**:
For the test to not fail.

**How to reproduce it (as minimally and precisely as possible)**:
I don't know. Please see https://prow.k8s.io/job-history/kubernetes-jenkins/pr-logs/directory/pull-cloud-provider-vsphere-test for a list of the failed tests, specifically builds [385](https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/cloud-provider-vsphere/156/pull-cloud-provider-vsphere-test/385) and [387](https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/cloud-provider-vsphere/156/pull-cloud-provider-vsphere-test/387).

**Anything else we need to know?**: NA

**Environment**: NA

**Comment by dvonthenen** [comment]
Taking a look at it now... it's been flaky for a while. Will fix shortly.
