### ISSUE TITLE
Explore splitting CSI plugin into separate repo

### ISSUE THREAD

**Issue by codenrhoden** [kubernetes/cloud-provider-vsphere#170]
/kind cleanup

We should look at whether we want to move the CSI plugin to it's own separate repo. Having it in the same repo as the CCM means they are coupled for releases, and makes versioning and tagging more complicated. We originally put CSI in here with the CCM because we followed [KEP 02](https://github.com/kubernetes/enhancements/blob/master/keps/sig-cloud-provider/20180530-cloud-controller-manager.md#repository-requirements), but this is worth a revisit. Early discussions with @andrewsykim indicate SIG-cloud provider may be open to changing this.

Assuming we *do* want to split out, two questions arise:

What is the location for the new repo? k8s-sigs has been the most common suggestion so far.

Since the CSI repo will need to import the common code from the CCM, should we move the commong code (e.g. `cloud-provider-vsphere/pkg/common`) to a separate repo as well? This would likely need to be hosted under the VMware org rather than Kubernetes.

**Comment by SandeepPissay** [comment]
I think it makes sense to have a separate repo for vSphere CSI and also the common code that CSI and CCM can use. Is there a KEP for moving csi out of the cloud-provider repo? Any progress on this issue so far?

**Comment by andrewsykim** [comment]
I don't think anyone would object if you proposed a change in https://github.com/kubernetes/enhancements/blob/master/keps/sig-cloud-provider/20180530-cloud-controller-manager.md#implementation-detailsnotesconstraints for this. Fwiw, that KEP is a bit out-dated and needs an update :)

**Comment by codenrhoden** [comment]
@SandeepPissay No I haven't done anything so far. I was going to wait until after we tagged a 0.2.0 release for CSI, which should be coming shortly. I'll be looking into this in the next couple of weeks.
