### ISSUE TITLE
csi: update kubernetes-csi docs

### ISSUE THREAD

**Issue by codenrhoden** [kubernetes/cloud-provider-vsphere#171]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind documentation

The docs at https://kubernetes-csi.github.io/docs/drivers.html are out of date re: csi-vSphere, an need to be updated to point to the right place.

**Comment by saad-ali** [comment]
Create a PR https://github.com/kubernetes-csi/docs/pulls editing the https://github.com/kubernetes-csi/docs/blob/master/book/src/drivers.md file. Site will be updated as soon as that PR merges.
