### ISSUE TITLE
Allow IPv6 Node Addresses

### ISSUE THREAD

**Issue by andrewsykim** [kubernetes/cloud-provider-vsphere#209]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind feature

**What happened**:
Currently we do a check for only IPv4 addresses when getting node addresses. 
```go
	addrs := []v1.NodeAddress{}
	for _, v := range oVM.Guest.Net {
		if v.DeviceConfigId == -1 {
			klog.V(4).Info("Skipping device because not a vNIC")
			continue
		}
		for _, ip := range v.IpAddress {
			if net.ParseIP(ip).To4() != nil {
				v1helper.AddToNodeAddresses(&addrs,
					v1.NodeAddress{
						Type:    v1.NodeExternalIP,
						Address: ip,
					}, v1.NodeAddress{
						Type:    v1.NodeInternalIP,
						Address: ip,
					}, v1.NodeAddress{
						Type:    v1.NodeHostName,
						Address: oVM.Guest.HostName,
					},
				)
			}
		}
    }
```

This means vNICs with v6 addresses can never be registered on a Kubernetes node. I'm not sure if the solution is to just remove that check since it may unexpectedly add v6 addresses and potentially break clusters but there should be some sort of way to opt in, maybe via a field in cloud config? 

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- vsphere-cloud-controller-manager version:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by andrewsykim** [comment]
cc @akutz

**Comment by akutz** [comment]
Currently the Cluster API Provider for vSphere allows IPv6 addresses, but ultimately will deploy clusters that break since the cloud provider will filter out those addresses when reporting node addresses.

**Comment by akutz** [comment]
Please touch base with me and @andrewsykim on this. This needs to occur with some version of `KubernetesPreferredCIDR` mask used to filter non-Kubernetes IP addresses.

**Comment by dvonthenen** [comment]
Talked with @andrewsykim about it... started implementation. Will have a PR by tomorrow.

**Comment by dvonthenen** [comment]
PR https://github.com/kubernetes/cloud-provider-vsphere/pull/231 merged

/close
