### ISSUE TITLE
 User names cannot be used with escape characters.

### ISSUE THREAD

**Issue by qw1mb0** [kubernetes/cloud-provider-vsphere#214]
/kind bug

**What happened**:
We have a user named `user\sa-DevopsProvisioner` with which we want to order disks.

**What you expected to happen**:
If you use the username in vsphere.conf:
`user = 'user\sa-DevopsProvisioner'` we get the controller error:
```
time="2019-07-05T11:15:14Z" level=fatal msg="grpc failed" error="2:8: unquoted '\\' must be followed by new line or double quote"
```

If you use the username
`user = 'user\\sa-DevopsProvisioner'` we get the controller error:
```
time="2019-07-05T11:15:14Z" level=fatal msg="grpc failed" error="2:8: unquoted '\\' must be followed by new line or double quote"
```

If you use the username
`user = "user\\sa-DevopsProvisioner"` we get the controller error:
```
E0705 11:17:42.653946       1 connection.go:63] Failed to create govmomi client. err: ServerFaultCode: Cannot complete login due to an incorrect user name or password.
W0705 11:17:42.655611       1 credentialmanager.go:77] Cannot get secret  in namespace . error: "secret \"\" not found"
W0705 11:17:42.655650       1 credentialmanager.go:54] secret "" not found in namespace ""
E0705 11:17:42.655660       1 credentialmanager.go:68] credentials not found for server "p-vc-3.hq.ru.corp.leroymerlin.com"
E0705 11:17:42.655678       1 connectionmanager.go:153] Failed to get credentials from Secret Credential Manager with err:Credentials not found
```

If you use the username
`user = "user\sa-DevopsProvisioner"`  we get the controller error:
```
time="2019-07-05T11:18:25Z" level=error msg="Failed to parse config. Err: 2:16: unknown escape sequence"
```

How can I use a username with escape characters?

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- vsphere-cloud-controller-manager version: `gcr.io/cloud-provider-vsphere/vsphere-csi:v0.2.0`
- OS (e.g. from /etc/os-release): `Ubuntu 16.04.6 LTS`
- Kernel (e.g. `uname -a`): 
- Install tools:
- Others:

**Comment by dvonthenen** [comment]
@qw1mb0 How were you even able to create a user account `user\sa-DevopsProvisioner` in the vCenter Server? The `\` is an invalid character in a vSphere username.

**Comment by qw1mb0** [comment]
In this case, it turned out that `user` is a domain, corrected the user on `sa-DevopsProvisioner@domain.example.com` and everything began to work correctly
