### ISSUE TITLE
Error with deleting Persistent Volumes after they've been mounted to a worker node

### ISSUE THREAD

**Issue by taylorsilva** [kubernetes/cloud-provider-vsphere#219]
**What happened**: When I deleted a PVC, the corresponding PV was not automatically deleted. The reclaim policy was set to `DELETE`. Describing the PV shows an error:

```
$ kubectl describe pv pvc-c7bd01cd-afe0-11e9-89ec-005056b9048c
Name:            pvc-c7bd01cd-afe0-11e9-89ec-005056b9048c
Labels:          <none>
Annotations:     kubernetes.io/createdby: vsphere-volume-dynamic-provisioner
                 pv.kubernetes.io/bound-by-controller: yes
                 pv.kubernetes.io/provisioned-by: kubernetes.io/vsphere-volume
Finalizers:      [kubernetes.io/pv-protection]
StorageClass:    concourse-storage-class
Status:          Failed
Claim:           default/nginx-pvc-claim
Reclaim Policy:  Delete
Access Modes:    RWO
VolumeMode:      Filesystem
Capacity:        2Gi
Node Affinity:   <none>
Message:         Error caused by file /vmfs/volumes/57f6b68b-54df1c80-56db-00253028000d/kubevols/kubernetes-dynamic-pvc-c7bd01cd-afe0-11e9-89ec-005056b9048c.vmdk
Source:
    Type:               vSphereVolume (a Persistent Disk resource in vSphere)
    VolumePath:         [vnx5600-wild-2] kubevols/kubernetes-dynamic-pvc-c7bd01cd-afe0-11e9-89ec-005056b9048c.vmdk
    FSType:             ext4
    StoragePolicyName:
Events:
  Type     Reason              Age   From                         Message
  ----     ------              ----  ----                         -------
  Warning  VolumeFailedDelete  11s   persistentvolume-controller  Error caused by file /vmfs/volumes/57f6b68b-54df1c80-56db-00253028000d/kubevols/kubernetes-dynamic-pvc-c7bd01cd-afe0-11e9-89ec-005056b9048c.vmdk

```

**What you expected to happen**: The PV is automatically deleted when the PVC is deleted.

**How to reproduce it (as minimally and precisely as possible)**:
See this gist for steps on reproducing: https://gist.github.com/taylorsilva/6dbb045650635bc7709a5e4ce1f3a77f

The error with deleting the PV only happens **after** the PV has been mounted in a container. If you create a PVC and then delete it before it's mounted to a container, the PV is created and deleted without error.

**Environment**:
- vsphere-cloud-controller-manager version: *not sure how to get this. Let me know how and I'll grab it*
- OS (e.g. from /etc/os-release): Got this from one of the worker nodes.
```
NAME="Ubuntu"
VERSION="16.04.6 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.6 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```
- Kernel (e.g. `uname -a`): `Linux 8a6d3591-522f-467a-87a2-e5f748ccad91 4.15.0-52-generic #56~16.04.1-Ubuntu SMP Thu Jun 6 12:03:31 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux` 
- Install tools: Bosh deployed PKS using PAS (v2.6)
- PKS (Pivotal Container Service) `v1.4.1-build.4`

Let me know if any more information would help. Thank you!

/kind bug

**Comment by dvonthenen** [comment]
@taylorsilva the vSphere CCM/CPI (this project) doesn't handle anything related to storage.

PKS uses the in-tree provider since the CCM (this project repo) and CSI are still listed as beta and not recommended yet for production environments.

I would re-submit this issue in the k/k repo so it can get the proper attention and people to look at it. Re-submit here: https://github.com/kubernetes/kubernetes

**Comment by taylorsilva** [comment]
@dvonthenen Thank you David, I'll repost there.
