### ISSUE TITLE
worker node without zones unable to start kubelet without config file

### ISSUE THREAD

**Issue by jd-daniels** [kubernetes/cloud-provider-vsphere#220]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
When adding a new worker node to an existing cluster that already uses vsphere cloud provider, I am running into this:

"Error: failed to run Kubelet: could not init cloud provider "vsphere": no vSphere cloud provider config file given"

**What you expected to happen**:

The documentation says that I shouldn't need to provide a config file for worker nodes when not using zones, which I am not using.

**How to reproduce it (as minimally and precisely as possible)**:

Set   --cloud-provider=vsphere on a new worker node which joined the cluster without the flag for a config file.

**Anything else we need to know?**:

**Environment**:
Vsphere 6.5, hardware version 13. Kernel 4.19. VSAN datastore.

**Comment by frapposelli** [comment]
Hi @jd-daniels, looks like you're using the in-tree provider for vsphere which is a different codebase hosted under github.com/kubernetes/kubernetes, can you please file this issue there?

**Comment by jd-daniels** [comment]
Sorry about that, will do.
