### ISSUE TITLE
Support different secret/secretNamespace per vCenter

### ISSUE THREAD

**Issue by akutz** [kubernetes/cloud-provider-vsphere#233]
/kind feature

Currently the CCM only supports a single `secret` and `secretNamespace` for all vCenters as global properties. This issue tracks support for a `secret`/`secretNamespace` per vCenter.

**Comment by dvonthenen** [comment]
Discussed with @akutz, got more requirements, and started implementation on it

**Comment by dvonthenen** [comment]
Closing because PR https://github.com/kubernetes/cloud-provider-vsphere/pull/241 was merged

/close

**Comment by dvonthenen** [comment]
@akutz This came up in the cloud-provider-vsphere meeting. The group just wanted to make sure that was implemented satisfies the needs you posted in this issue.

What was implemented allows for:
- a secret/secretNamespace per vCenter which maps to a given vCenter username/password
- allows for multiple connections to a vCenter with each connection holding a different username/password stored in a secret/secretNamespace. (ie using vCenter user accounts for role-based access to vCenter resources, such as but not limited to a cluster or resource pool.)

**Comment by akutz** [comment]
lgtm!
