### ISSUE TITLE
Invalid patch version value

### ISSUE THREAD

**Issue by schizoid90** [kubernetes/cloud-provider-vsphere#246]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
 /kind bug
> /kind feature

**What happened**:
I followed the instructions on this [page](https://docs.vmware.com/en/VMware-vSphere/6.7/Cloud-Native-Storage/GUID-039425C1-597F-46FF-8BAA-C5A46FF10E63.html) to install the driver on my kubernetes cluster.

When i apply the vSphere CSI driver configuration two containers in the vsphere-csi-controller-0 pod don't come up:
vsphere-csi-controller
csi-provisioner

This is what I see when I inspect the container logs:
```bash
kube@kube-master01:~/kubeManifests/storage$ kubectl logs --namespace=kube-system vsphere-csi-controller-0 csi-provisioner
I0905 15:24:01.982184       1 feature_gate.go:226] feature gates: &{map[Topology:true]}
I0905 15:24:01.982359       1 csi-provisioner.go:98] Version: v1.2.1-0-g971feacb
I0905 15:24:01.982406       1 csi-provisioner.go:112] Building kube configs for running in cluster...
E0905 15:24:01.994364       1 csi-provisioner.go:137] OnConnectionLoss callback only supported for unix:// addresses


kube@kube-master01:~/kubeManifests/storage$ kubectl logs --namespace=kube-system vsphere-csi-controller-0 vsphere-csi-controller
I0905 15:24:00.150395       1 config.go:265] GetCnsconfig called with cfgPath: /etc/cloud/csi-vsphere.conf
I0905 15:24:00.150597       1 config.go:209] Initializing vc server 10.3.1.52
I0905 15:24:00.150609       1 controller.go:66] Initializing CNS controller
I0905 15:24:00.150658       1 virtualcentermanager.go:61] Initializing defaultVirtualCenterManager...
I0905 15:24:00.150666       1 virtualcentermanager.go:63] Successfully initialized defaultVirtualCenterManager
I0905 15:24:00.150673       1 virtualcentermanager.go:105] Successfully registered VC "10.3.1.52"
I0905 15:24:00.150683       1 manager.go:55] Initializing volume.defaultManager...
I0905 15:24:00.150686       1 manager.go:59] volume.defaultManager initialized
I0905 15:24:00.179278       1 virtualcenter.go:130] New session ID for 'root' = 52658661-45de-92dc-33e3-515260399620
E0905 15:24:00.179295       1 controller.go:96] checkAPI failed for vcenter API version: 6.7.2, err=Invalid patch version value
time="2019-09-05T15:24:00Z" level=error msg="Failed to init controller" error="Invalid patch version value"
time="2019-09-05T15:24:00Z" level=info msg="configured: csi.vsphere.vmware.com" controllerType=VANILLA mode=controller
time="2019-09-05T15:24:00Z" level=info msg="removed sock file" path=/var/lib/csi/sockets/pluginproxy/csi.sock
time="2019-09-05T15:24:00Z" level=fatal msg="grpc failed" error="Invalid patch version value"
```

I'm confused because version 6.7.0 is running so don't know where 6.7.2 is coming from.

**What you expected to happen**:
Everything to come up correctly without issue

**How to reproduce it (as minimally and precisely as possible)**:
follow install steps in [guide](https://docs.vmware.com/en/VMware-vSphere/6.7/Cloud-Native-Storage/GUID-039425C1-597F-46FF-8BAA-C5A46FF10E63.html)

**Anything else we need to know?**:

**Environment**:
- vsphere-cloud-controller-manager version: 6.7.0
- OS (e.g. from /etc/os-release): Ubuntu 18.04.2 LTS
- Kernel (e.g. `uname -a`): Linux kube-master01 4.15.0-60-generic #67-Ubuntu SMP Thu Aug 22 16:55:30 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Others:

**Comment by dvonthenen** [comment]
Hi @schizoid90, please file this issue in https://github.com/kubernetes-sigs/vsphere-csi-driver. This repo doesn't contain any of the CSI components and another team handles it's development/issue-tracking/etc. This is repo only contains bits relating for Cloud Provider Interface (CPI).

**Comment by schizoid90** [comment]
Thanks @dvonthenen, got here from Google so assumed it was the right place
