### ISSUE TITLE
Firewall settings for CSI

### ISSUE THREAD

**Issue by danielkucera** [kubernetes/cloud-provider-vsphere#247]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**What happened**:

We have a firewall between kubernetes cluster and vsphere API (vcenter). I was trying to find in the documentation which connections do we need to allow - if `all masters -> vsphere API` is enough or if also nodes need to access it.

Could you please clarify this in the docs?

**Comment by dvonthenen** [comment]
Hi @danielkucera,

Thanks for taking the time to file this issue, but you can you re-file this issue in the following repo https://github.com/kubernetes-sigs/vsphere-csi-driver. This repo only contains code for the external Cloud Provider Interface and does not contain any storage-related or CSI functionality. The CSI repo listed above is also maintained by a different team and I want to make sure it gets the proper visibility and attention.
