### ISSUE TITLE
Document vCenter/ESXi compatibility matrix

### ISSUE THREAD

**Issue by frapposelli** [kubernetes/cloud-provider-vsphere#255]
Document the vCenter/ESXi compatibility matrix with regards to CPI and CSI

/kind feature

**Comment by dvonthenen** [comment]
Based on my testing, it looks like the CNS based CSI driver only supports 6.7u3 after having tests with back level 6.7u2 and 6.7u1 ESX hosts using a 6.7u3 vCenter. I dug around and found the following PRs in govmomi which supports that claim.

https://github.com/vmware/govmomi/pull/1585/files
https://github.com/vmware/govmomi/pull/1572/files


As for CPI testing (and having familiarity developing the implementation), I tested a vCenter/ESX combo of 6.5 and the CPI works fine. I would expect but did not test that the CPI would work for all subsequent versions of vSphere based on the APIs used in govmomi.

**Comment by dvonthenen** [comment]
PR https://github.com/kubernetes/cloud-provider-vsphere/pull/263 merged

/close
