### ISSUE TITLE
Docs on Cloud Config need an update

### ISSUE THREAD

**Issue by andrewsykim** [kubernetes/cloud-provider-vsphere#261]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind feature

When I initially put together the docs for cloud config (https://cloud-provider-vsphere.sigs.k8s.io/cloud_config.html), it was with both the in-tree and out-of-tree provider in mind. Realizing now that documenting both on the same page is not feasible. We should update that page so it only references config valid for the external provider. The doc itself is also a bit outdated and requires an update.

**Comment by dvonthenen** [comment]
PR https://github.com/kubernetes/cloud-provider-vsphere/pull/263 merged

/close
