### ISSUE TITLE
vsphere secret

### ISSUE THREAD

**Issue by kfox1111** [kubernetes/cloud-provider-vsphere#265]
The documentation mentions putting credentials in a configmap. Its best practice to put them in secrets.

**Comment by dvonthenen** [comment]
Yea, the documentation should definitely document using k8s secret since the CPI supports it. Will make the change to the docs.

/assign

**Comment by dvonthenen** [comment]
PR submitted.

@kfox1111 That should at least get you going if you haven't done so already.

**Comment by kfox1111** [comment]
Great. Thanks! :)
