### ISSUE TITLE
Cloud controller is unable to patch node with IP addresses from cloud provider

### ISSUE THREAD

**Issue by ivanfilippov** [kubernetes/cloud-provider-vsphere#266]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
Cloud controller is unable to patch node with IP addresses from cloud provider on a multi-NIC VM.

```
I1011 05:22:49.646435       1 instances.go:158] instances.InstanceExistsByProviderID() CACHED with 42348b4e-4ba1-e452-e946-6d0e9a323160
I1011 05:22:49.646457       1 instances.go:78] instances.NodeAddressesByProviderID() CACHED with 42348b4e-4ba1-e452-e946-6d0e9a323160
E1011 05:22:49.656899       1 node_controller.go:188] Error patching node with cloud ip addresses = [failed to patch status "{\"status\":{\"$setElementOrder/addresses\":[{\"type\":\"ExternalIP\"},{\"type\":\"InternalIP\"},{\"type\":\"Hostname\"},{\"type\":\"ExternalIP\"},{\"type\":\"InternalIP\"},{\"type\":\"ExternalIP\"},{\"type\":\"InternalIP\"}],\"addresses\":[{\"address\":\"172.16.202.44\",\"type\":\"ExternalIP\"},{\"address\":\"172.16.201.44\",\"type\":\"ExternalIP\"},{\"address\":\"172.16.45.44\",\"type\":\"ExternalIP\"},{\"address\":\"172.16.202.44\",\"type\":\"InternalIP\"},{\"address\":\"172.16.201.44\",\"type\":\"InternalIP\"},{\"address\":\"172.16.45.44\",\"type\":\"InternalIP\"}]}}" for node "k8s-prod5-worker-2": The order in patch list:
[map[address:172.16.202.44 type:ExternalIP] map[address:172.16.201.44 type:ExternalIP] map[address:172.16.45.44 type:ExternalIP] map[address:172.16.202.44 type:InternalIP] map[address:172.16.201.44 type:InternalIP] map[address:172.16.45.44 type:InternalIP]]
 doesn't match $setElementOrder list:
[map[type:ExternalIP] map[type:InternalIP] map[type:Hostname] map[type:ExternalIP] map[type:InternalIP] map[type:ExternalIP] map[type:InternalIP]]
]
```

**What you expected to happen**:
Nodes are patched with IP addresses from cloud provider.

**How to reproduce it (as minimally and precisely as possible)**:
Build a worker node with 3 NICs and attempt to deploy the cloud controller

**Anything else we need to know?**:
This was encountered in the openstack provider as well and was fixed there (https://github.com/kubernetes/cloud-provider-openstack/issues/407).

**Environment**:
- vsphere-cloud-controller-manager version: latest from github
- OS (e.g. from /etc/os-release): RancherOS v1.5.4
- Kernel (e.g. `uname -a`): 4.14.138-rancher
- Install tools: cluster installed via RKE
- Others:

**Comment by dvonthenen** [comment]
It looks like that was merged and possibly made it into 1.16. Any confirmation on that?

**Comment by andrewsykim** [comment]
yeah its in v1.16

**Comment by dvonthenen** [comment]
> yeah its in v1.16

Since I need to rebuild my dev env, will be trying this out today or tomorrow.

**Comment by andrewsykim** [comment]
It seems like just k8s.io/kubernetes needs to be updated

**Comment by dvonthenen** [comment]
Looks like it's only on the k8s side. I tested with the latest CPI binary without updating the k8s.io/kubernetes that the CPI is built on and it works just fine with 1.16.2. Closing this out.

/close

**Comment by andrewsykim** [comment]
@dvonthenen you used multiple vNICs in your tests? At first glance it sounds like we do need to update k8s.io/kubernetes in the controller manager since PatchNodeStatus is still called by the cloud node controllerl

**Comment by dvonthenen** [comment]
ahhhh i missed that condition... will re-test right now

**Comment by dvonthenen** [comment]
Yep, I re-tested with 3 NICs with 3 different IPs one on each NIC and I don't see that error. Works with the latest CPI binary without updating the k8s.io/kubernetes that the CPI is built on.

Keep in mind, we also made the change that only the first IP is patched remember. That change isn't in the 1.0.0 release but only on master.

**Comment by andrewsykim** [comment]
So sounds like this is already fixed in master but we're going to allow users to configure which networks the VM addresses should come from in https://github.com/kubernetes/cloud-provider-vsphere/pull/271? Is that correct @dvonthenen?

**Comment by dvonthenen** [comment]
@andrewsykim that is correct

**Comment by frapposelli** [comment]
@dvonthenen can you verify and close?

**Comment by dvonthenen** [comment]
Same as https://github.com/kubernetes/cloud-provider-vsphere/issues/270

**Comment by frapposelli** [comment]
closed via #284 

/close

**Comment by deshui123** [comment]
hit the same issue for pure IPv6, related ticket https://github.com/kubernetes/cloud-provider-vsphere/issues/312

**Comment by deshui123** [comment]
When using vSphere VM Network names, the error disappeared.

**Comment by andrewsykim** [comment]
FYI we also need to backport https://github.com/kubernetes/kubernetes/pull/79391

**Comment by lubronzhan** [comment]
Hit this issue with k8s 1.18 + CCM 1.1.0
