### ISSUE TITLE
Migration documentation

### ISSUE THREAD

**Issue by kfox1111** [kubernetes/cloud-provider-vsphere#268]
Documentation is needed for how to migrate from the deprecated in tree driver to the external driver.

**Comment by dvonthenen** [comment]
Not sure if the CPI repo is the best place for this document (which the migration effort/work is still pending last I checked). For the CPI, the migration is just setting `--cloud-provider=external` and deploying it. For CSI (and the storage capabilities it provides) which is located in this repo (https://github.com/kubernetes-sigs/vsphere-csi-driver) will have a bunch of requirements for migration.

I will say that we do have a combined doc for deployment on this repo. Not sure if that's going to get confusing later on though.

**Comment by frapposelli** [comment]
@frapposelli to loop in CSI folks to create a single doc for in-tree > out-of-tree.

/cc @mylesagray

**Comment by frapposelli** [comment]
@mylesagray any luck on this one?

**Comment by mylesagray** [comment]
@frapposelli - I'm having some conversations internally about how best to approach this, I think a combined doc is the way to go for this, as generally the CSI and CPI will be used in tandem to replace the dual functionality of the VCP.

I was hoping we might do the CSI migration piece once we have a better story around the VCP->CSI volume conversion using the shim layer as there is essentially a requirement on that to allow VCP volumes to be mounted post-move to CPI.

**Comment by kfox1111** [comment]
Still important

/reopen
/remove-lifecycle rotten

**Comment by dvonthenen** [comment]
@kfox1111 I think this might be addressed with this doc
https://github.com/kubernetes-sigs/vsphere-csi-driver/blob/master/docs/book/features/vsphere_csi_migration.md

**Comment by kfox1111** [comment]
That doc looks pretty good. It doesn't mention if the cloud provider needs to be adopted as well or in what order to do that. So looking very close to done but not quite?

/remove-lifecycle rotten
