### ISSUE TITLE
Both InternalIP and ExternalIP gets created for first IP on each vNIC

### ISSUE THREAD

**Issue by zuzzas** [kubernetes/cloud-provider-vsphere#270]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**What happened**:

If there are multiple vNICs, then for the first address on each vNICs `status.addresses` on the Node object would contain both InternalIP and ExternalIP address type.

**What you expected to happen**:

I'd like to have a way to specify exact network name, so that when vsphere CCM iterates over vNICs, it detects correct Node address type.

**How to reproduce it (as minimally and precisely as possible)**:

Specify multiple vNICs on VM creation, and assign IPs to each one. Then observe `.status.addresses` field on the Node object.

**Comment by dvonthenen** [comment]
I am trying to test this feature against what customers might do in the wild and even in my own test environment, what we thought was sufficient turns out it might not be. I'm re-opening this issue to block the 1.1 release. Going to think about this a little more and then update the implementation.

**Comment by frapposelli** [comment]
closed via #284 

/close
