### ISSUE TITLE
Support yaml for cloud config

### ISSUE THREAD

**Issue by andrewsykim** [kubernetes/cloud-provider-vsphere#275]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind feature

**What happened**:
Support the cloud config being in yaml instead of gcfg. We would have to support both but I assume most users are already comfortable with yaml. 

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- vsphere-cloud-controller-manager version:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by frapposelli** [comment]
We should make a priority for v1.2.0 to transition to yaml
