### ISSUE TITLE
CPI and CSI Config Alignment

### ISSUE THREAD

**Issue by dvonthenen** [kubernetes/cloud-provider-vsphere#276]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind feature

**What happened**:
The configs between CPI and CSI have a lot of commonality between the two, but there are also CPI and CSI specific things that should not be inherited by other components when they are not applicable.

You will find a link to a Google Doc which is a collaboration space for the definition of what the CPI and CSI configurations look like. Since these configurations will change over time until we merge a PR that addresses this issue, this will be a living document requiring updates and could even be used for planning or even potentially a spec containing a single source of truth on what these configs look like. From there, we can iterate for correctness within this Google doc and use this GitHub issue to discuss how we can resolve this problem.

https://docs.google.com/document/d/1c9oYbKkTtaNlzbjSG0WwaNztU1LZuQdZInHpfGytktE/edit?usp=sharing

**What you expected to happen**:
Have common configuration between the two and then create CPI and CSI specific sections and/or implementations that only pertain to those components

**How to reproduce it (as minimally and precisely as possible)**:
Just take a look at the configs? 🤷‍♂️

**Anything else we need to know?**:
NA

**Environment**:
NA

**Comment by frapposelli** [comment]
@frapposelli to loop in folks from CSI to agree on a common spec
