### ISSUE TITLE
Minor versions should track Kubernetes minor versions

### ISSUE THREAD

**Issue by andrewsykim** [kubernetes/cloud-provider-vsphere#277]
/kind feature

Ideally every minor version of the vSphere cloud provider should track a minor version of Kubernetes by importing the corresponding version of k8s.io/kubernetes. The semantic versioning doesn't have to match exactly, but there should still be a 1 to 1 correlation. By doing so we can prescribe to users the exact version of the cloud provider based on the version of Kubernetes they are running.

**Comment by frapposelli** [comment]
Let's move the current milestone from `1.2.0` to `1.18.0` which will be our new versioning scheme aligned with Kubernetes minors.

**Comment by dvonthenen** [comment]
Going to assign this to you @gwang550. @andrewsykim thought it might be a good idea for you to take a look at this. I unfortunately am getting sidetracked temporarily with some internal unrelated items for right now. Looking to do this before accepting new merge requests.

**Comment by andrewsykim** [comment]
This is technically done with the last two minor releases

/close
