### ISSUE TITLE
CPI (vsphere-cloud-controller-manager) unable to enable instance when using FQDN

### ISSUE THREAD

**Issue by mardicas** [kubernetes/cloud-provider-vsphere#285]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
Installing the external vSphere integration CPI components. The vsphere-cloud-controller-manager container is unable to find the kubernetes hosts when using FQDN as nodes in kubernetes setup.
It is also unable to detect the IP address of nodes.

When using govc tool, then I am able to find the hosts using FQDN. From vSphere you can see the VM-s also with the same FQDN-s.
Worker nodes taints are not removed.

**What you expected to happen**:
The nodes are found via the FQDN or IP. The worker nodes taints are removed.

**How to reproduce it (as minimally and precisely as possible)**:
Create VM-s with FQDN, create kubernetes nodes with same FQDN names.

**Anything else we need to know?**:
Currently workaround is to specify "--hostname-override" on all kubelets without the domain part.
So insteaf of "k8s-worker-03.dev.obscure.this.com" use "k8s-worker-03".

**Environment**:
- vsphere-cloud-controller-manager version:  933c60515902 | latest v1.0.0
- OS (e.g. from /etc/os-release):
Ubuntu 18.04.3 LTS / vSphere 6.7 U3 / VM HWVersion: 15
- Kernel (e.g. `uname -a`): Linux k8s-master-01 4.15.0-65-generic #74-Ubuntu SMP Tue Sep 17 17:06:04 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: rke v1.0.0
- Others:
I added the log with the failed startup. I had to obscure/redact the actual hostnames and such.
[vsphere-cloud-controller.log](https://github.com/kubernetes/cloud-provider-vsphere/files/3960353/vsphere-cloud-controller.log)

Kubelets are started as:
```
kubelet --v=2 --max-pods=250 --volume-plugin-dir=/var/lib/kubelet/volumeplugins --anonymous-auth=false --resolv-conf=/etc/resolv.conf --make-iptables-util-chains=true --authorization-mode=Webhook --tls-cipher-suites=TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305 --root-dir=/var/lib/kubelet --cgroups-per-qos=True --fail-swap-on=false --read-only-port=0 --address=0.0.0.0 --cni-conf-dir=/etc/cni/net.d --streaming-connection-idle-timeout=30m --cluster-domain=cluster.local --hostname-override=k8s-master-01.dev.obscure.this.com --pod-infra-container-image=rancher/pause:3.1 --authentication-token-webhook=true --client-ca-file=/etc/kubernetes/ssl/kube-ca.pem --node-ip=10.0.34.71 --network-plugin=cni --kubeconfig=/etc/kubernetes/ssl/kubecfg-kube-node.yaml --register-with-taints=node-role.kubernetes.io/controlplane=true:NoSchedule --cluster-dns=10.43.0.10 --event-qps=0 --cni-bin-dir=/opt/cni/bin --cloud-provider=external --cgroup-driver=systemd --resolv-conf=/run/systemd/resolve/resolv.conf
```
govc using the same credentials on the same kubernetes host.
```
govc find -name=k8s-master-01.dev.obscure.this.com
/OBSCURED/vm/dev.obscured/k8s-master-01.dev.obscure.this.com

govc vm.info k8s-master-01.dev.obscure.this.com
Name:           k8s-master-01.dev.obscure.this.com
  Path:         /OBSCURED/vm/dev.obscured/k8s-master-01.dev.obscure.this.com
  UUID:         42100344-c68f-f790-8ee8-32c1964487aa
  Guest name:   Ubuntu Linux (64-bit)
  Memory:       4096MB
  CPU:          4 vCPU(s)
  Power state:  poweredOn
  Boot time:    2019-12-13 08:29:15.397574 +0000 UTC
  IP address:   10.0.34.71
  Host:         esxi-05-a.obscured
```
Same goes for all hosts. 
Without the FQDN govc does not find the hosts.

Also noticed the when searching by IP, it reports
```
E1213 09:10:24.890293       1 datacenter.go:90] Unable to find VM by IP. VM IP: k8s-worker-03.dev.obscure.this.com
```
Looking at the source code, I think it should instead show the IP address and not host-name?
Also the main issue that happens only when using FQDN
```
I1213 09:10:22.297450       1 search.go:72] WhichVCandDCByNodeID by Name
I1213 09:10:22.297456       1 search.go:74] WhichVCandDCByNodeID nodeID: k8s-master-02.dev.obscure.this.com
I1213 09:10:22.305751       1 search.go:152] Finding node k8s-master-02.dev.obscure.this.com in vc=dev.vmware.obscured and datacenter=OBSCURED
E1213 09:10:22.309754       1 datacenter.go:107] Unable to find VM by DNS Name. VM DNS Name: k8s-master-02.dev.obscure.this.com
E1213 09:10:22.309779       1 search.go:180] Error while looking for vm=k8s-master-02.dev.obscure.this.com(byName) in vc=dev.vmware.obscured and datacenter=OBSCURED: No VM found
```

**Comment by dvonthenen** [comment]
@mardicas is each node running VMTools and is current/update-to-date/latest version?

/assign

**Comment by dvonthenen** [comment]
I just went through configuring all nodes using FQDNs and all nodes are correctly identified by the CPI. All nodes are discovered and all attributes are set up correctly for all nodes, but just showing the master node as example below.

The attached screenshot shows what the master node looks like in vCenter with VMTools status as an example.
![master](https://user-images.githubusercontent.com/12752197/70820063-91628000-1d8c-11ea-8cf5-14a67a0e048c.png)

The CPI log below for the master node:
```
I1213 17:33:08.638525       1 search.go:151] Finding node 423637ea-d028-0855-70a9-000f7140c2e5 in vc=10.162.18.29 and datacenter=vicdc
I1213 17:33:08.644424       1 search.go:151] Finding node 423637ea-d028-0855-70a9-000f7140c2e5 in vc=10.162.18.29 and datacenter=vicdc
I1213 17:33:08.662804       1 search.go:207] Found node 423637ea-d028-0855-70a9-000f7140c2e5 as vm=VirtualMachine:vm-55 in vc=10.162.18.29 and datacenter=vicdc
I1213 17:33:08.662896       1 search.go:209] Hostname: k8smaster.example.com, UUID: 423637ea-d028-0855-70a9-000f7140c2e5
I1213 17:33:08.662927       1 nodemanager.go:123] Discovered VM using normal UUID format
I1213 17:33:08.675245       1 nodemanager.go:222] Adding Hostname: k8smaster.example.com
I1213 17:33:08.675369       1 nodemanager.go:236] internalVMNetworkName = Internal K8s Traffic
I1213 17:33:08.675392       1 nodemanager.go:237] externalVMNetworkName = External/Outbound Traffic
I1213 17:33:08.675405       1 nodemanager.go:238] v.Network = External/Outbound Traffic
I1213 17:33:08.675475       1 nodemanager.go:146] IP is local only or there was an error. ip="fe80::5b6d:a8a8:e210:cdea" err=failed to validate ip addr=fe80::5b6d:a8a8:e210:cdea: link-local-unicast
I1213 17:33:08.675515       1 nodemanager.go:294] Adding External IP by NetworkName: 10.162.27.60
I1213 17:33:08.675528       1 nodemanager.go:232] Skipping device because not a vNIC
I1213 17:33:08.675548       1 nodemanager.go:232] Skipping device because not a vNIC
I1213 17:33:08.675562       1 nodemanager.go:236] internalVMNetworkName = Internal K8s Traffic
I1213 17:33:08.675575       1 nodemanager.go:237] externalVMNetworkName = External/Outbound Traffic
I1213 17:33:08.675589       1 nodemanager.go:238] v.Network = Internal K8s Traffic
I1213 17:33:08.675610       1 nodemanager.go:146] IP is local only or there was an error. ip="fe80::e79:10be:19e1:b3ee" err=failed to validate ip addr=fe80::e79:10be:19e1:b3ee: link-local-unicast
I1213 17:33:08.675632       1 nodemanager.go:146] IP is local only or there was an error. ip="fe80::2a4e:5135:341f:913a" err=failed to validate ip addr=fe80::2a4e:5135:341f:913a: link-local-unicast
I1213 17:33:08.675657       1 nodemanager.go:282] Adding Internal IP by NetworkName: 10.162.16.75
I1213 17:33:08.675678       1 nodemanager.go:232] Skipping device because not a vNIC
I1213 17:33:08.675688       1 nodemanager.go:232] Skipping device because not a vNIC
I1213 17:33:08.675702       1 nodemanager.go:232] Skipping device because not a vNIC
I1213 17:33:08.675714       1 nodemanager.go:331] Found node 423637ea-d028-0855-70a9-000f7140c2e5 as vm=VirtualMachine:vm-55 in vc=10.162.18.29 and datacenter=vicdc
I1213 17:33:08.675738       1 nodemanager.go:333] Hostname: k8smaster.example.com UUID: 423637ea-d028-0855-70a9-000f7140c2e5
I1213 17:33:08.675794       1 nodemanager.go:80] addNodeInfo NodeName: k8smaster.example.com, UUID: 423637ea-d028-0855-70a9-000f7140c2e5
I1213 17:33:08.675815       1 nodemanager.go:89] addNode NodeName: k8smaster.example.com, UID: 423637ea-d028-0855-70a9-000f7140c2e5
I1213 17:33:08.675848       1 nodemanager.go:67] RegisterNode LEAVE: k8smaster.example.com
```

**Comment by mardicas** [comment]
> @mardicas is each node running VMTools and is current/update-to-date/latest version? I also assume that the actual hostnames are discoverable within DNS (aka the hostnames resolve)?
> 
> /assign

Yes the host names resolve with the FQDN. For short names it does not (not in the search path of resolv). Is it required to resolve short names too?
```
k8s-master-01:~# nslookup k8s-master-01.dev.obscure.this.com
Server:         127.0.0.53
Address:        127.0.0.53#53

Non-authoritative answer:
Name:   k8s-master-01.dev.obscure.this.com
Address: 127.0.1.1
Name:   k8s-master-01.dev.obscure.this.com
Address: 10.0.34.71
```

The vmtoolsd is running:
```
root@k8s-master-01:~# ps -ef | grep vmtoo
root       619     1  0 dets 13 ?      00:02:43 /usr/bin/vmtoolsd
root@k8s-master-01:~# vmtoolsd --version
VMware Tools daemon, version 10.3.10.10540 (build-12406962)
```
To my knowledge this should be a recent enough version.

**Comment by mardicas** [comment]
The machines are all cloned from the same vm image - could that cause problems? 
All the VM-s have the same ID in /etc/machine-id.

**Comment by mardicas** [comment]
I noticed the vSphere screen shows also the pod-to-pod network interface IP. Seems sometimes it has reported the flannel interface as primary instead.
![Screenshot 2019-12-16 at 10 27 39](https://user-images.githubusercontent.com/29144235/70892431-d9361100-1ff1-11ea-9d64-af0e890bf765.jpg)

From vmware tools debug logs:
```
 [   debug] [vmsvc] GuestInfoGetPrimaryIP: returning '10.0.34.71'
 [   debug] [vmsvc] GuestInfoGetPrimaryIP: returning '10.42.0.0'
```
Interfaces
```
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 10.0.34.71  netmask 255.255.255.0  broadcast 10.0.34.255
        ether 00:50:56:90:d8:c7  txqueuelen 1000  (Ethernet)
        RX packets 29541  bytes 6220784 (6.2 MB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 28626  bytes 4233864 (4.2 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

flannel.1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1450
        inet 10.42.0.0  netmask 255.255.255.255  broadcast 0.0.0.0
        ether 82:1d:75:be:6b:2b  txqueuelen 0  (Ethernet)
        RX packets 173  bytes 56326 (56.3 KB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 197  bytes 29796 (29.7 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```
Both IP-s are reported to vSphere though.
The flannel interface is not ignored by vmware tools.
```
[2019-12-16T08:47:27.807Z] [   debug] [vmsvc] VMTools_ConfigGetString: Returning default value for '[guestinfo] exclude-nics'=docker*,veth*,virbr*.
````

**Comment by mardicas** [comment]
I have changed the configuration of machines, so the hosts file is:
```
root@k8s-master-01:~# cat /etc/hosts
127.0.0.1       localhost
10.0.34.71      k8s-master-01.dev.obscure.this.com k8s-master-01
```
The flannel interface is now ignored by vmtools and only the correct IP is reported by vmware tools. (10.0.34.71)
Also the nslookup no longer answers as 127.0.1.1 when looking up the host itself.

I still find it odd that when it looks by IP it does not find it, and the log does not even show the IP that is being searched(just hostname?):
```
I1216 11:11:18.001356       1 search.go:70] WhichVCandDCByNodeID by IP
I1216 11:11:18.001362       1 search.go:74] WhichVCandDCByNodeID nodeID: k8s-master-01.dev.obscure.this.com
I1216 11:11:18.014006       1 search.go:152] Finding node k8s-master-01.dev.obscure.this.com in vc=vcenter.obscured.com and datacenter=OBSCURED
E1216 11:11:18.018885       1 datacenter.go:90] Unable to find VM by IP. VM IP: k8s-master-01.dev.obscure.this.com
E1216 11:11:18.018898       1 search.go:180] Error while looking for vm=k8s-master-01.dev.obscure.this.com(byIP) in vc=vcenter.obscured.com and datacenter=OBSCURED: No VM found
I1216 11:11:18.018908       1 search.go:185] Did not find node k8s-master-01.dev.obscure.this.com in vc=vcenter.obscured.com and datacenter=OBSCURED
I1216 11:11:18.018916       1 search.go:227] WhichVCandDCByNodeID: "k8s-master-01.dev.obscure.this.com" vm not found
```
The "DNS Name" is still shown without the FQDN.
![k8s-master](https://user-images.githubusercontent.com/29144235/70903421-86ffea80-2007-11ea-8129-3ccbabe1a831.jpg)

**Comment by mardicas** [comment]
I now discovered that when I put the FQDN into the /etc/hostname file, then the joining works and the "DNS Name" in vsphere is shown correctly. This hostname file is set by vmware tools itself.
The interesting part is that I can not set FQDN as the "host_name" when cloning the machine. I have to set "host_name" as the short name and specify the "domain" as the domain. Then vmware itself proceeds to setup the host after cloning:
/var/log/vmware-imc/toolsDeployPkg.log
```
DEBUG: Processing line: 'HOSTNAME = k8s-master-01' 
DEBUG: ADDED KEY-VAL :: 'NETWORK|HOSTNAME' = 'k8s-master-01' 
DEBUG: Processing line: 'DOMAINNAME = dev.obscure.this.com' 
DEBUG: ADDED KEY-VAL :: 'NETWORK|DOMAINNAME' = 'dev.obscure.this.com' 
...
DEBUG: Set the host name to k8s-master-01 via [hostnamectl set-hostname]
DEBUG: Host name is k8s-master-01 
...
INFO: Customizing Hosts file ...  
DEBUG: Old hostname=[ubuntu-1804-amd64] 
DEBUG: Old FQDN=[ubuntu-1804-amd64] 
DEBUG: New hostname=[k8s-master-01] 
DEBUG: Building FQDN. HostnameFQDN: k8s-master-01, Domainname: dev.obscure.this.com
DEBUG: New FQDN=[k8s-master-01.dev.obscure.this.com] 
DEBUG: opening file /etc/hosts.
```
After that linux behaves as expected:
```
root@k8s-master-01:~# hostname --fqdn
k8s-master-01.dev.obscure.this.com
root@k8s-master-01:~# hostname 
k8s-master-01
root@k8s-master-01:~# hostname -s
k8s-master-01
```
However when it comes to reporitng the "DNS Name" back by the tools then it reports the short name, unless I manually reconfigure the hostname used.

1) Setings the FQDN in /etc/hostname seems to solve the "WhichVCandDCByNodeID by Name"
2) Finding by IP should work even if it is not found by name, why is the IP not reported in the log?

**Comment by mardicas** [comment]
I can now confirm that when I set the system hostname with ansible after cloning:
```
root@k8s-master-01:~# hostname --fqdn
k8s-master-01.dev.obscure.this.com
root@k8s-master-01:~# hostname
k8s-master-01.dev.obscure.this.com
root@k8s-master-01:~# cat /etc/hostname 
k8s-master-01.dev.obscure.this.com
```
The kubernetes nodes are found and everything works by hostname.
So the issue was not related to CPI, but vmware/vmtoolsd cloning or/and reporting. I am not even sure weather tools should rely on "hostname -f" when reporting the "DNS Name" or the cloning (customize) part should be able to set the FQDN correctly on linux hosts.

I would close the issue, but: Why does it not find the hosts by the IP?

**Comment by dvonthenen** [comment]
There are a lot of replies/questions here... will try to address all of them.

> Is it required to resolve short names too?

No, the short name is not required. If the FQDN is used, then the hostname for the system (ie /etc/hostname) must be the FQDN. If an IP is used, then the hostname must be the IP. Whatever is registered with the kubernetes cluster must resolve in DNS somehow.

> The machines are all cloned from the same vm image - could that cause problems?

The system UUID for each VM is required to be unique. On a clone operation, the system UUID should auto-generated and therefore unique. Moving or re-registering an existing VM should have a system UUID be regenerated (this is actually usually prompted in the vSphere UI when/if this condition is detected).

> I noticed the vSphere screen shows also the pod-to-pod network interface IP. Seems sometimes it has reported the flannel interface as primary instead.

Functionality is being provided in the next release to select or chose the internal and external IPs used by k8s.

> Also the "DNS Name" seems to be without the FQDN in vsphere for some reason.

This is because the system's hostname is using the short name. The /etc/hostname *must* contain the hostname would want to be reflected in k8s. In your case, you want to use the FQDN.

> I still find it odd that when it looks by IP it does not find it, and the log does not even show the IP that is being searched(just hostname?)

FindByIP is only used as a fallback or hail mary attempt. There is an undocumented and unsupported way of configuring all of this by IP addresses alone but we don't want to get into that. If the CPI is attempting to look up the node/VM by IP, that means you probably have something misconfigured.

If you have any other questions, please hit me up in slack. If not, closing this issue based on your suggestion.

/close

**Comment by mardicas** [comment]
I tried to document all the steps I did to solve the issue. In case someone else runs into the same problem.
Thank you! No need to re-open issue.

**Comment by dvonthenen** [comment]
> I tried to document all the steps I did to solve the issue. In case someone else runs into the same problem.
> Thank you! No need to re-open issue.

Oh no worries. The info is super valuable. I was more concerned about addressing all the questions you had and not missing any. Thanks again!
