### ISSUE TITLE
Passwords cannot use escape characters

### ISSUE THREAD

**Issue by mike-england** [kubernetes/cloud-provider-vsphere#287]
/kind bug

**What happened**:
CSI stateful set is unable to start when passwords have backslash in it (and possibly other special characters but I didn't do extensive testing).

When following the [guide](https://cloud-provider-vsphere.sigs.k8s.io/tutorials/kubernetes-on-vsphere-with-kubeadm.html), under csi-vsphere.conf, I'm unable to use a username with backslash, which is talked about in [issue 214](https://github.com/kubernetes/cloud-provider-vsphere/issues/214), and seems to be a workaround.  I also can't seem to use a backslash within a password, which is a bigger problem.

The error message looks like this:
`time="2020-01-06T21:43:52Z" level=fatal msg="grpc failed" error="6:12: unquoted '\\' must be followed by new line or double quote"`

I've tried escaping the backslash, encoding it (base64), and passing with single quotes, none of which work.

**What you expected to happen**:
Username and password to be accepted, even with special characters.

**How to reproduce it (as minimally and precisely as possible)**:
```
$ cat csi-vsphere.conf 
[Global]
cluster-id = "k8s-cluster1"
[VirtualCenter "10.1.1.14"]
insecure-flag = "true"
user = "k8s_admin@itlab.com"
password = "}sso\d$2!UsO"
port = "443"
datacenters = "Vancouver"
```
```
ubuntu@k8s-master:~$ kubectl create secret generic vsphere-config-secret --from-file=csi-vsphere.conf --namespace=kube-system
ubuntu@k8s-master:~$ kubectl apply -f https://raw.githubusercontent.com/kubernetes-sigs/vsphere-csi-driver/master/manifests/1.14/deploy/vsphere-csi-controller-ss.yaml
```

**Anything else we need to know?**:
Single quotes don't seem to work at all.  Even once I simplified the password, surrounding them with single quotes failed with a permission denied.

Interestingly, single quotes seem to work in handling backslashes when deploying the CPI, but that's in YAML format as opposed to this which is from a conf file. (Under "Create a CPI secret" in the documentation)

**Environment**:
- vsphere-cloud-controller-manager version: gcr.io/cloud-provider-vsphere/csi/release/driver:v1.0.1
- OS (e.g. from /etc/os-release): Ubuntu 18.04.3 LTS
- Kernel (e.g. `uname -a`): 4.15.0-72-generic
- Install tools:
- Others:

**Comment by dvonthenen** [comment]
Hi @mike-england!

Please file an issue in the CSI repo in order to get the correct visibility: https://github.com/kubernetes-sigs/vsphere-csi-driver/

/close
