### ISSUE TITLE
vcpctl Solution User ServerFaultCode: Invalid certificate bytes

### ISSUE THREAD

**Issue by vitality411** [kubernetes/cloud-provider-vsphere#298]
/kind bug

**What happened**:
I tried to use vcpctl to provision the requirements for CCM but got an error during solution user creation:
```
vcpctl provision --host 'https://x.x.x.x/sdk' --insecure=true --user myuser --password mypw --cert  k8s-vcp.crt  --interactive
Perform cloud provider provisioning...
Create solution user...
error: ServerFaultCode: Invalid certificate bytes
```

**What you expected to happen**:
Solution user to be created

**How to reproduce it (as minimally and precisely as possible)**:
```
git clone https://github.com/kubernetes/cloud-provider-vsphere.git
cd cloud-provider-vsphere/
go build -o vcpctl ./cmd/vcpctl/main.go
cp ./vcpctl /usr/local/bin/vcpctl
vcpctl provision --host 'https://x.x.x.x/sdk' --insecure=true --user myuser --password mypw --cert  k8s-vcp.crt  --interactive
```

**Anything else we need to know?**:
It works with the vcpctl created certificate when using govc as described in https://github.com/vmware-archive/kubernetes/issues/489:
`govc sso.user.create -A -R Administrator -C "$(cat k8s-vcp.crt)" k8s-vcp`

**Environment**:
- vsphere-cloud-controller-manager version: latest
- OS (e.g. from /etc/os-release): CentOS Linux 7 (Core)
- Kernel (e.g. `uname -a`): Linux buildhost 3.10.0-1062.9.1.el7.x86_64 #1 SMP Fri Dec 6 15:49:49 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: go1.13.7.linux-amd64.tar.gz
- Others:

**Comment by dvonthenen** [comment]
Hi @vitality411,

I can take a look at this but will need to familiarize myself with this utility. The `vcpctl` hasn't been maintained for some time since the primary contributor has left the project. Will need to bring attention to this to see if we can get enough support for it.

**Comment by frapposelli** [comment]
Reviving `vcpctl` is something desirable but we don't have a timeline for it, setting to milestone Next
