### ISSUE TITLE
vsphere-cloud-controller-manager pod crashes with error:  Error from server: no preferred addresses found; known addresses: []

### ISSUE THREAD

**Issue by mamullen13316** [kubernetes/cloud-provider-vsphere#299]
**Is this a BUG REPORT or FEATURE REQUEST?**:  BUG REPORT
 /kind bug

**What happened**:
While working through the documentation https://cloud-provider-vsphere.sigs.k8s.io/tutorials/kubernetes-on-vsphere-with-kubeadm.html. In the section titled "Deploy the CPI Manifests",  the cloud-controller-manager daemonset and pod are launched with the command:
kubectl apply -f https://github.com/kubernetes/cloud-provider-vsphere/raw/master/manifests/controller-manager/vsphere-cloud-controller-manager-ds.yaml

The daemonset is stuck in Waiting and the pod is crashing with the below error:

root@ubuntu1804-k8s-1:/etc/kubernetes# kubectl logs vsphere-cloud-controller-manager-wttqb -n kube-system
Error from server: no preferred addresses found; known addresses: []

Kubernetes version is v1.14.2.   

**What you expected to happen**:
Working cloud-controller-manager pod. 

**How to reproduce it (as minimally and precisely as possible)**:
Follow through the instructions https://cloud-provider-vsphere.sigs.k8s.io/tutorials/kubernetes-on-vsphere-with-kubeadm.html.  

**Anything else we need to know?**:
The vsphere.conf file placed in /etc/kubernetes has the following contents:

root@ubuntu1804-k8s-1:/etc/kubernetes# cat vsphere.conf
[Global]
port = "443"
insecure-flag = "true"

[VirtualCenter "172.16.4.214"]
datacenters = "DC1"
secret-name = "cpi-secret"
secret-namespace = "kube-system"

The secret cpi-secret is created in the kube-system namespace:

root@ubuntu1804-k8s-1:/etc/kubernetes# kubectl get secret cpi-secret -n kube-system -o yaml
apiVersion: v1
data:
  172.16.4.214.password: **REDACTED**
  172.16.4.214.username: **REDACTED**
kind: Secret
metadata:
  creationTimestamp: "2020-02-15T23:49:03Z"
  name: cpi-secret
  namespace: kube-system
  resourceVersion: "6850"
  selfLink: /api/v1/namespaces/kube-system/secrets/cpi-secret
  uid: bf2e0946-504d-11ea-b498-005056941456
type: Opaque

**Environment**:
- vsphere-cloud-controller-manager version: latest
- OS (e.g. from /etc/os-release): 18.04.4 LTS (Bionic Beaver)
- Kernel (e.g. `uname -a`):Linux ubuntu1804-k8s-1 4.15.0-76-generic #86-Ubuntu SMP Fri Jan 17 17:24:28 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Others:

**Comment by dvonthenen** [comment]
Hi @mamullen13316 

Can you paste the entire logs for the daemonset?

**Comment by mamullen13316** [comment]
Hi @dvonthenen,
Thanks for getting back to me.  Would you please let me know the command for the output you are requesting?  The single log message above is all that is being returned from the pod,  and i'm not sure how to gather logs for a daemonset.  Here's the output from a describe if that is helpful.  

root@ubuntu1804-k8s-1:~# kubectl describe daemonset vsphere-cloud-controller-manager -n kube-system
Name:           vsphere-cloud-controller-manager
Selector:       k8s-app=vsphere-cloud-controller-manager
Node-Selector:  node-role.kubernetes.io/master=
Labels:         k8s-app=vsphere-cloud-controller-manager
Annotations:    deprecated.daemonset.template.generation: 1
                kubectl.kubernetes.io/last-applied-configuration:
                  {"apiVersion":"apps/v1","kind":"DaemonSet","metadata":{"annotations":{},"labels":{"k8s-app":"vsphere-cloud-controller-manager"},"name":"vs...
Desired Number of Nodes Scheduled: 1
Current Number of Nodes Scheduled: 1
Number of Nodes Scheduled with Up-to-date Pods: 1
Number of Nodes Scheduled with Available Pods: 0
Number of Nodes Misscheduled: 0
Pods Status:  1 Running / 0 Waiting / 0 Succeeded / 0 Failed
Pod Template:
  Labels:           k8s-app=vsphere-cloud-controller-manager
  Service Account:  cloud-controller-manager
  Containers:
   vsphere-cloud-controller-manager:
    Image:      gcr.io/cloud-provider-vsphere/cpi/release/manager:latest
    Port:       <none>
    Host Port:  <none>
    Args:
      --v=2
      --cloud-provider=vsphere
      --cloud-config=/etc/cloud/vsphere.conf
    Requests:
      cpu:        200m
    Environment:  <none>
    Mounts:
      /etc/cloud from vsphere-config-volume (ro)
  Volumes:
   vsphere-config-volume:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      cloud-config
    Optional:  false
Events:        <none>

**Comment by dvonthenen** [comment]
The command should be:
```
kubectl logs vsphere-cloud-controller-manager-<5 random letters> -n kube-system
```

Just in case you don't know how to get the pod info with the random 5 letters:
```
kubectl get pods --all-namespaces
```

**Comment by mamullen13316** [comment]
It's just a single log message:

`root@ubuntu1804-k8s-1:~# kubectl logs vsphere-cloud-controller-manager-t7hxn -n kube-system
Error from server: no preferred addresses found; known addresses: []`

**Comment by dvonthenen** [comment]
Sorry. That's my bad... I forgot to ask to up the log level. Increase the log level to `--v=6`, redeploy, and run the log capture line again.

**Comment by mamullen13316** [comment]
I deleted the daemonset,  then cloned the repo locally and made the change to line 41 to increase the logging level to 6 as suggested.  Then launched again with kubectl apply -f vsphere-cloud-controller-manager-ds.yaml.   Unfortunately i'm still only seeing the single log message as before.

root@ubuntu1804-k8s-1:~/cloud-provider-vsphere/manifests/controller-manager# kubectl logs vsphere-cloud-controller-manager-wdgwc -n kube-system
Error from server: no preferred addresses found; known addresses: []

**Comment by dvonthenen** [comment]
Hi @mamullen13316  That's odd. Ok will investigate.

- What is the version of your VC?
- I assume that all your k8s nodes have a valid *single* IPv4 address per node based on your configuration?

**Comment by mamullen13316** [comment]
vCenter is 6.7.0.42000.   Yes,  single IPv4 per node plus of course the IPs that are added by Docker and Flannel.  

root@ubuntu1804-k8s-1:~/cloud-provider-vsphere/manifests/controller-manager# ifconfig
docker0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        inet 172.17.0.1  netmask 255.255.0.0  broadcast 172.17.255.255
        ether 02:42:e0:a9:e5:08  txqueuelen 0  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

ens192: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 172.16.4.71  netmask 255.255.255.0  broadcast 172.16.4.255
        inet6 fe80::250:56ff:fe94:1456  prefixlen 64  scopeid 0x20<link>
        ether 00:50:56:94:14:56  txqueuelen 1000  (Ethernet)
        RX packets 3122269  bytes 495811397 (495.8 MB)
        RX errors 0  dropped 25  overruns 0  frame 0
        TX packets 2034246  bytes 984716658 (984.7 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

flannel.1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1450
        inet 10.244.0.0  netmask 255.255.255.255  broadcast 0.0.0.0
        inet6 fe80::c829:9bff:fe7c:44e4  prefixlen 64  scopeid 0x20<link>
        ether ca:29:9b:7c:44:e4  txqueuelen 0  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 250 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 89800089  bytes 15993005341 (15.9 GB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 89800089  bytes 15993005341 (15.9 GB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

**Comment by dvonthenen** [comment]
On a very off chance... Do your hostnames resolve from DNS on every node? I assume the gateway is set and all nodes are routable (I assume yes because you are able to pull the container image)?

Can you do a describe on the master node and print node labels?

**Comment by mamullen13316** [comment]
Host resolution is working between the nodes and from the nodes to vcenter.  Using hosts files for local name resolution between the machines, and they point to Internet DNS servers for outbound.  

`
root@ubuntu1804-k8s-1:~# kubectl describe nodes
Name:               ubuntu1804-k8s-1
Roles:              master
Labels:             beta.kubernetes.io/arch=amd64
                    beta.kubernetes.io/os=linux
                    kubernetes.io/arch=amd64
                    kubernetes.io/hostname=ubuntu1804-k8s-1
                    kubernetes.io/os=linux
                    node-role.kubernetes.io/master=
Annotations:        flannel.alpha.coreos.com/backend-data: {"VtepMAC":"ca:29:9b:7c:44:e4"}
                    flannel.alpha.coreos.com/backend-type: vxlan
                    flannel.alpha.coreos.com/kube-subnet-manager: true
                    flannel.alpha.coreos.com/public-ip: 172.16.4.71
                    kubeadm.alpha.kubernetes.io/cri-socket: /var/run/dockershim.sock
                    node.alpha.kubernetes.io/ttl: 0
                    volumes.kubernetes.io/controller-managed-attach-detach: true
CreationTimestamp:  Sat, 15 Feb 2020 22:25:50 +0000
Taints:             node-role.kubernetes.io/master:NoSchedule
                    node.cloudprovider.kubernetes.io/uninitialized=true:NoSchedule
Unschedulable:      false
Conditions:
  Type             Status  LastHeartbeatTime                 LastTransitionTime                Reason                       Message
  ----             ------  -----------------                 ------------------                ------                       -------
  MemoryPressure   False   Thu, 27 Feb 2020 22:54:57 +0000   Sat, 15 Feb 2020 22:25:47 +0000   KubeletHasSufficientMemory   kubelet has sufficient memory available
  DiskPressure     False   Thu, 27 Feb 2020 22:54:57 +0000   Sat, 15 Feb 2020 22:25:47 +0000   KubeletHasNoDiskPressure     kubelet has no disk pressure
  PIDPressure      False   Thu, 27 Feb 2020 22:54:57 +0000   Sat, 15 Feb 2020 22:25:47 +0000   KubeletHasSufficientPID      kubelet has sufficient PID available
  Ready            True    Thu, 27 Feb 2020 22:54:57 +0000   Sat, 15 Feb 2020 22:29:02 +0000   KubeletReady                 kubelet is posting ready status. AppArmor enabled
Addresses:
Capacity:
 cpu:                2
 ephemeral-storage:  20508240Ki
 hugepages-1Gi:      0
 hugepages-2Mi:      0
 memory:             8168480Ki
 pods:               110
Allocatable:
 cpu:                2
 ephemeral-storage:  18900393953
 hugepages-1Gi:      0
 hugepages-2Mi:      0
 memory:             8066080Ki
 pods:               110
System Info:
 Machine ID:                 b208d3acb1214f64b5a4c15ae05aa9c6
 System UUID:                54CA1442-4958-3F88-4211-4137FAF80693
 Boot ID:                    24f91804-63d7-4530-927d-a00f5cb93a6c
 Kernel Version:             4.15.0-76-generic
 OS Image:                   Ubuntu 18.04.4 LTS
 Operating System:           linux
 Architecture:               amd64
 Container Runtime Version:  docker://18.6.0
 Kubelet Version:            v1.14.2
 Kube-Proxy Version:         v1.14.2
PodCIDR:                     10.244.0.0/24
Non-terminated Pods:         (7 in total)
  Namespace                  Name                                        CPU Requests  CPU Limits  Memory Requests  Memory Limits  AGE
  ---------                  ----                                        ------------  ----------  ---------------  -------------  ---
  kube-system                etcd-ubuntu1804-k8s-1                       0 (0%)        0 (0%)      0 (0%)           0 (0%)         12d
  kube-system                kube-apiserver-ubuntu1804-k8s-1             250m (12%)    0 (0%)      0 (0%)           0 (0%)         12d
  kube-system                kube-controller-manager-ubuntu1804-k8s-1    200m (10%)    0 (0%)      0 (0%)           0 (0%)         12d
  kube-system                kube-flannel-ds-amd64-vn8tg                 100m (5%)     100m (5%)   50Mi (0%)        50Mi (0%)      12d
  kube-system                kube-proxy-frj67                            0 (0%)        0 (0%)      0 (0%)           0 (0%)         12d
  kube-system                kube-scheduler-ubuntu1804-k8s-1             100m (5%)     0 (0%)      0 (0%)           0 (0%)         12d
  kube-system                vsphere-cloud-controller-manager-wn2mm      200m (10%)    0 (0%)      0 (0%)           0 (0%)         16m
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  Resource           Requests    Limits
  --------           --------    ------
  cpu                850m (42%)  100m (5%)
  memory             50Mi (0%)   50Mi (0%)
  ephemeral-storage  0 (0%)      0 (0%)
Events:              <none>


Name:               ubuntu1804-k8s-2
Roles:              <none>
Labels:             beta.kubernetes.io/arch=amd64
                    beta.kubernetes.io/os=linux
                    kubernetes.io/arch=amd64
                    kubernetes.io/hostname=ubuntu1804-k8s-2
                    kubernetes.io/os=linux
Annotations:        flannel.alpha.coreos.com/backend-data: {"VtepMAC":"e6:e7:85:2d:b5:71"}
                    flannel.alpha.coreos.com/backend-type: vxlan
                    flannel.alpha.coreos.com/kube-subnet-manager: true
                    flannel.alpha.coreos.com/public-ip: 172.16.4.82
                    kubeadm.alpha.kubernetes.io/cri-socket: /var/run/dockershim.sock
                    node.alpha.kubernetes.io/ttl: 0
                    volumes.kubernetes.io/controller-managed-attach-detach: true
CreationTimestamp:  Sat, 15 Feb 2020 23:11:26 +0000
Taints:             node.cloudprovider.kubernetes.io/uninitialized=true:NoSchedule
Unschedulable:      false
Conditions:
  Type             Status  LastHeartbeatTime                 LastTransitionTime                Reason                       Message
  ----             ------  -----------------                 ------------------                ------                       -------
  MemoryPressure   False   Thu, 27 Feb 2020 22:54:53 +0000   Sat, 15 Feb 2020 23:11:26 +0000   KubeletHasSufficientMemory   kubelet has sufficient memory available
  DiskPressure     False   Thu, 27 Feb 2020 22:54:53 +0000   Sat, 15 Feb 2020 23:11:26 +0000   KubeletHasNoDiskPressure     kubelet has no disk pressure
  PIDPressure      False   Thu, 27 Feb 2020 22:54:53 +0000   Sat, 15 Feb 2020 23:11:26 +0000   KubeletHasSufficientPID      kubelet has sufficient PID available
  Ready            True    Thu, 27 Feb 2020 22:54:53 +0000   Sat, 15 Feb 2020 23:12:06 +0000   KubeletReady                 kubelet is posting ready status. AppArmor enabled
Addresses:
Capacity:
 cpu:                2
 ephemeral-storage:  20508240Ki
 hugepages-1Gi:      0
 hugepages-2Mi:      0
 memory:             16426016Ki
 pods:               110
Allocatable:
 cpu:                2
 ephemeral-storage:  18900393953
 hugepages-1Gi:      0
 hugepages-2Mi:      0
 memory:             16323616Ki
 pods:               110
System Info:
 Machine ID:                 785fa3b5044b45e986770f19717c9bdf
 System UUID:                A3DC1442-2C71-636C-25B4-CE24CA7AA25C
 Boot ID:                    eb3d1c9c-6de4-42ef-87ed-21456053e223
 Kernel Version:             4.15.0-76-generic
 OS Image:                   Ubuntu 18.04.4 LTS
 Operating System:           linux
 Architecture:               amd64
 Container Runtime Version:  docker://18.6.0
 Kubelet Version:            v1.14.2
 Kube-Proxy Version:         v1.14.2
PodCIDR:                     10.244.1.0/24
Non-terminated Pods:         (2 in total)
  Namespace                  Name                           CPU Requests  CPU Limits  Memory Requests  Memory Limits  AGE
  ---------                  ----                           ------------  ----------  ---------------  -------------  ---
  kube-system                kube-flannel-ds-amd64-c6h4w    100m (5%)     100m (5%)   50Mi (0%)        50Mi (0%)      11d
  kube-system                kube-proxy-x72rf               0 (0%)        0 (0%)      0 (0%)           0 (0%)         11d
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  Resource           Requests   Limits
  --------           --------   ------
  cpu                100m (5%)  100m (5%)
  memory             50Mi (0%)  50Mi (0%)
  ephemeral-storage  0 (0%)     0 (0%)
Events:              <none>

root@ubuntu1804-k8s-1:~# kubectl get pods --show-labels -n kube-system
NAME                                       READY   STATUS             RESTARTS   AGE   LABELS
coredns-6557d7f7d6-fh54h                   0/1     Pending            0          12d   k8s-app=kube-dns,pod-template-hash=6557d7f7d6
coredns-6557d7f7d6-jgmx2                   0/1     Pending            0          12d   k8s-app=kube-dns,pod-template-hash=6557d7f7d6
etcd-ubuntu1804-k8s-1                      1/1     Running            1          12d   component=etcd,tier=control-plane
kube-apiserver-ubuntu1804-k8s-1            1/1     Running            1          12d   component=kube-apiserver,tier=control-plane
kube-controller-manager-ubuntu1804-k8s-1   1/1     Running            3          12d   component=kube-controller-manager,tier=control-plane
kube-flannel-ds-amd64-c6h4w                1/1     Running            1          11d   app=flannel,controller-revision-hash=8676477c4,pod-template-generation=1,tier=node
kube-flannel-ds-amd64-vn8tg                1/1     Running            1          12d   app=flannel,controller-revision-hash=8676477c4,pod-template-generation=1,tier=node
kube-proxy-frj67                           1/1     Running            1          12d   controller-revision-hash=6c5f45759d,k8s-app=kube-proxy,pod-template-generation=1
kube-proxy-x72rf                           1/1     Running            1          11d   controller-revision-hash=6c5f45759d,k8s-app=kube-proxy,pod-template-generation=1
kube-scheduler-ubuntu1804-k8s-1            1/1     Running            3          12d   component=kube-scheduler,tier=control-plane
vsphere-cloud-controller-manager-wn2mm     0/1     CrashLoopBackOff   8          17m   controller-revision-hash=78c9b4f8f9,k8s-app=vsphere-cloud-controller-manager,pod-template-generation=1
vsphere-csi-controller-0                   0/5     Pending            0          11d   app=vsphere-csi-controller,controller-revision-hash=vsphere-csi-controller-57896cd985,role=vsphere-csi,statefulset.kubernetes.io/pod-name=vsphere-csi-controller-0

The coredns pods are in pending state due to the taint on the nodes.  I think it might be expected for the nodes to have taints installed until the cloud provider comes online,  but wanted to mention it. 

root@ubuntu1804-k8s-1:~# kubectl get nodes -o json | jq '.items[].spec'
{
  "podCIDR": "10.244.0.0/24",
  "taints": [
    {
      "effect": "NoSchedule",
      "key": "node-role.kubernetes.io/master"
    },
    {
      "effect": "NoSchedule",
      "key": "node.cloudprovider.kubernetes.io/uninitialized",
      "value": "true"
    }
  ]
}
{
  "podCIDR": "10.244.1.0/24",
  "taints": [
    {
      "effect": "NoSchedule",
      "key": "node.cloudprovider.kubernetes.io/uninitialized",
      "value": "true"
    }
  ]
}

`

**Comment by frapposelli** [comment]
This was triaged also during the monthly vSphere provider call and it was pointed out that there might be a fix for this behavior in 1.16, see kubernetes/kubernetes#75229

**Comment by mamullen13316** [comment]
Thank you @frapposelli,  it does appear this was resolved.  I am no longer seeing the issue after deploying 1.17.3.

**Comment by lubronzhan** [comment]
This behavior will be reverted from this PR 
https://github.com/kubernetes/kubernetes/pull/120751
