### ISSUE TITLE
For IPv6, loud controller is unable to patch node with IP addresses from cloud provider

### ISSUE THREAD

**Issue by deshui123** [kubernetes/cloud-provider-vsphere#312]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug

**What happened**:
For IPv6(both internal and external are IPv6), cloud controller is unable to patch node with IP addresses from cloud provider on a multi-NIC VM.
When I get node address info using following cli, I can only get **one external IP address**.
I want to get **both internal and external IP address for IPv6** ENV which can achieve this for cloud-provider-openstack.
And for IPv4 with cloud-provider-vsphere, I can also **get both internal and external IP address for IPv4.**
I want to confirm if this is a BUG for cloud-provider-vsphere with pure IPv6
```
kubectl get nodes henry-m -o go-template --template='{{range .status.addresses}}{{printf "%s: %s \n" .type .address}}{{end}}'  
```
```
E0402 18:22:26.818297       1 node_controller.go:188] Error patching node with cloud ip addresses = [failed to patch status "{\"status\":{\"$setElementOrder/addresses\":[{\"type\":\"Hostname\"},{\"type\":\"ExternalIP\"},{\"type\":\"InternalIP\"},{\"type\":\"ExternalIP\"},{\"type\":\"InternalIP\"}],\"addresses\":[{\"address\":\"2650:1:87:64::84\",\"type\":\"ExternalIP\"},{\"address\":\"2001:da8:8003:801::84\",\"type\":\"ExternalIP\"},{\"address\":\"2650:1:87:64::84\",\"type\":\"InternalIP\"},{\"address\":\"2001:da8:8003:801::84\",\"type\":\"InternalIP\"}]}}" for node "henry-w": The order in patch list:
[map[address:2650:1:87:64::84 type:ExternalIP] map[address:2001:da8:8003:801::84 type:ExternalIP] map[address:2650:1:87:64::84 type:InternalIP] map[address:2001:da8:8003:801::84 type:InternalIP]]
 doesn't match $setElementOrder list:
[map[type:Hostname] map[type:ExternalIP] map[type:InternalIP] map[type:ExternalIP] map[type:InternalIP]]
```

```
[root@henry-m ~]# kubectl get nodes henry-m -o go-template  --template='{{range .status.addresses}}{{printf "%s: %s \n" .type .address}}{{end}}'
InternalIP: 2650:1:87:64::83
Hostname: henry-m
[root@henry-m ~]# ip a
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 00:50:56:9f:c3:c4 brd ff:ff:ff:ff:ff:ff
    inet6 2001:da8:8003:801::83/64 scope global noprefixroute
       valid_lft forever preferred_lft forever
    inet6 fe80::250:56ff:fe9f:c3c4/64 scope link noprefixroute
       valid_lft forever preferred_lft forever
3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 00:50:56:9f:66:65 brd ff:ff:ff:ff:ff:ff
    inet 135.1.87.83/27 brd 135.1.87.95 scope global noprefixroute eth1
       valid_lft forever preferred_lft forever
    inet6 2650:1:87:64::83/64 scope global noprefixroute
       valid_lft forever preferred_lft forever
    inet6 fe80::250:56ff:fe9f:6665/64 scope link noprefixroute
       valid_lft forever preferred_lft forever
```
**What you expected to happen**:
For vsphere provider, when using IPv4, can get all node interfaces but for IPv6, failed.

For openstack provider, all node interfaces can be show when using IPv6
```
[root@henry-1972-cs-01 ~]# kubectl get nodes henry-1972-cs-01 -o go-template --template='{{range .status.addresses}}{{printf "%s: %s \n" .type .address}}{{end}}'
InternalIP: c5f::1:f816:3eff:fe34:3ae9
InternalIP: c5f:0:0:101::2e9
Hostname: henry-1972-cs-01
[root@henry-1972-cs-01 ~]# ip a
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether fa:16:3e:34:3a:e9 brd ff:ff:ff:ff:ff:ff
    inet6 c5f::1:f816:3eff:fe34:3ae9/64 scope global noprefixroute dynamic
       valid_lft 2591739sec preferred_lft 604539sec
    inet6 fe80::f816:3eff:fe34:3ae9/64 scope link noprefixroute
       valid_lft forever preferred_lft forever
3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether fa:16:3e:08:b6:a1 brd ff:ff:ff:ff:ff:ff
    inet6 c5f:0:0:101::2e9/128 scope global noprefixroute dynamic
       valid_lft 5096sec preferred_lft 4796sec
    inet6 fe80::f816:3eff:fe08:b6a1/64 scope link noprefixroute
       valid_lft forever preferred_lft forever
```
**How to reproduce it (as minimally and precisely as possible)**:
Build a master node with 2 NICs which using pure IPv6 and attempt to deploy the cloud controller
**Anything else we need to know?**:
```
[root@henry-m ~]# cat /etc/os-release
NAME="Red Hat Enterprise Linux Server"
VERSION="7.7 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.7"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.7 (Maipo)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.7:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.7
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.7"

```
**Environment**:
- vsphere-cloud-controller-manager version: latest from github

**Comment by dvonthenen** [comment]
Hi @deshui123 

Did you try switching the IP Family in the config to IPv6? By default, the provider uses IPv4.
https://github.com/kubernetes/cloud-provider-vsphere/blob/master/pkg/common/config/types.go#L109-L113

**Comment by deshui123** [comment]
@dvonthenen Yes, I have specified the ip-family to ipv6.
If i don't specify this value, I can only get IPv4 address info of node.
But even I specified to "ipv6", i can only get the external IP address. I want to get both internal and external IP address  which can be achieved in cloud-provider-openstack

**Comment by dvonthenen** [comment]
Did you also specify the following?

https://github.com/kubernetes/cloud-provider-vsphere/blob/master/pkg/cloudprovider/vsphere/types.go#L44-L53

**Comment by deshui123** [comment]
@dvonthenen  Thanks for your response.
My vsphere version is **6.5**. 
I referred to such guide to set up my cluster using kubeadm  https://cloud-provider-vsphere.sigs.k8s.io/tutorials/k8s-vcp-on-vsphere-with-kubeadm.html

There is no mentioned about internalVMNetworkName and other parameters mentioned in your link.

Could u please share some info or vsphere.conf about these parameters?

**Comment by dvonthenen** [comment]
Yea, they are meant as advanced options for users to try out. The comments should provide some details on how to use... in a nutshell, you can specify the following:
- Using CIDR, which means all your IPs must be in the same network (ie. /24 for IPv4)
- Using vSphere VM Network names which allows you to have multiple networks (ie IPs from different subnets), but you must have a dedicated VM Network (which just could be the default "VM Network") which contains only a single vNIC that only has either a single IPv4 or IPv6 address (single because dual stack is not supported yet).

**Comment by deshui123** [comment]
@dvonthenen Thanks for your response.
When add vSphere VM Network names, I can get both internal&external IPs.
Thanks a lot

**Comment by dvonthenen** [comment]
@deshui123 no problem at all!
