### ISSUE TITLE
Getting error attachvolume.attach failed for volume has no nodeid annotation in kubernetes 1.18.1 and vsphere 6.7u3

### ISSUE THREAD

**Issue by adityasaxena88** [kubernetes/cloud-provider-vsphere#324]

**Comment by dvonthenen** [comment]
Hi @adityasaxena88 

- Were you able to verify that cloud-provider-vsphere was installed and running correctly?
- Can you provide some logs for the cloud-provider-vsphere instance?
- Can you also attach a print of node labels?

That would be a pretty good start.

Thanks!

**Comment by adityasaxena88** [comment]
logs of cloud provider 

I0422 03:53:51.565211       1 instances.go:78] instances.NodeAddressesByProviderID() CACHED with 42159afd-43f4-981f-2bed-4048da618451
I0422 03:53:51.568846       1 instances.go:158] instances.InstanceExistsByProviderID() CACHED with 4215bc17-179f-bf15-72cf-aa34edc25be5
I0422 03:53:51.568865       1 instances.go:78] instances.NodeAddressesByProviderID() CACHED with 4215bc17-179f-bf15-72cf-aa34edc25be5
I0422 03:53:51.572178       1 instances.go:158] instances.InstanceExistsByProviderID() CACHED with 4215c284-e0d4-22f4-ffa1-3c2e120325e2
I0422 03:53:51.572198       1 instances.go:78] instances.NodeAddressesByProviderID() CACHED with 4215c284-e0d4-22f4-ffa1-3c2e120325e2
I0422 03:58:51.578193       1 instances.go:158] instances.InstanceExistsByProviderID() CACHED with 4215952a-d7bc-2a99-ae73-f4e6b1c7ed9a
I0422 03:58:51.578240       1 instances.go:78] instances.NodeAddressesByProviderID() CACHED with 4215952a-d7bc-2a99-ae73-f4e6b1c7ed9a
I0422 03:58:51.581701       1 instances.go:158] instances.InstanceExistsByProviderID() CACHED with 42159afd-43f4-981f-2bed-4048da618451
I0422 03:58:51.581724       1 instances.go:78] instances.NodeAddressesByProviderID() CACHED with 42159afd-43f4-981f-2bed-4048da618451
I0422 03:58:51.584938       1 instances.go:158] instances.InstanceExistsByProviderID() CACHED with 4215bc17-179f-bf15-72cf-aa34edc25be5
I0422 03:58:51.584958       1 instances.go:78] instances.NodeAddressesByProviderID() CACHED with 4215bc17-179f-bf15-72cf-aa34edc25be5
I0422 03:58:51.588175       1 instances.go:158] instances.InstanceExistsByProviderID() CACHED with 4215c284-e0d4-22f4-ffa1-3c2e120325e2
I0422 03:58:51.588196       1 instances.go:78] instances.NodeAddressesByProviderID() CACHED with 4215c284-e0d4-22f4-ffa1-3c2e120325e2
I0422 04:03:51.593594       1 instances.go:158] instances.InstanceExistsByProviderID() CACHED with 4215bc17-179f-bf15-72cf-aa34edc25be5
I0422 04:03:51.593630       1 instances.go:78] instances.NodeAddressesByProviderID() CACHED with 4215bc17-179f-bf15-72cf-aa34edc25be5
I0422 04:03:51.597268       1 instances.go:158] instances.InstanceExistsByProviderID() CACHED with 4215c284-e0d4-22f4-ffa1-3c2e120325e2
I0422 04:03:51.597292       1 instances.go:78] instances.NodeAddressesByProviderID() CACHED with 4215c284-e0d4-22f4-ffa1-3c2e120325e2
I0422 04:03:51.601426       1 instances.go:158] instances.InstanceExistsByProviderID() CACHED with 4215952a-d7bc-2a99-ae73-f4e6b1c7ed9a
I0422 04:03:51.601450       1 instances.go:78] instances.NodeAddressesByProviderID() CACHED with 4215952a-d7bc-2a99-ae73-f4e6b1c7ed9a
I0422 04:03:51.604628       1 instances.go:158] instances.InstanceExistsByProviderID() CACHED with 42159afd-43f4-981f-2bed-4048da618451
I0422 04:03:51.604648       1 instances.go:78] instances.NodeAddressesByProviderID() CACHED with 42159afd-43f4-981f-2bed-4048da618451
I0422 04:08:51.610266       1 instances.go:158] instances.InstanceExistsByProviderID() CACHED with 4215bc17-179f-bf15-72cf-aa34edc25be5
I0422 04:08:51.610293       1 instances.go:78] instances.NodeAddressesByProviderID() CACHED with 4215bc17-179f-bf15-72cf-aa34edc25be5
I0422 04:08:51.613655       1 instances.go:158] instances.InstanceExistsByProviderID() CACHED with 4215c284-e0d4-22f4-ffa1-3c2e120325e2
I0422 04:08:51.613694       1 instances.go:78] instances.NodeAddressesByProviderID() CACHED with 4215c284-e0d4-22f4-ffa1-3c2e120325e2
I0422 04:08:51.616730       1 instances.go:158] instances.InstanceExistsByProviderID() CACHED with 4215952a-d7bc-2a99-ae73-f4e6b1c7ed9a
I0422 04:08:51.616783       1 instances.go:78] instances.NodeAddressesByProviderID() CACHED with 4215952a-d7bc-2a99-ae73-f4e6b1c7ed9a
I0422 04:08:51.620128       1 instances.go:158] instances.InstanceExistsByProviderID() CACHED with 42159afd-43f4-981f-2bed-4048da618451
I0422 04:08:51.620148       1 instances.go:78] instances.NodeAddressesByProviderID() CACHED with 42159afd-43f4-981f-2bed-4048da618451
I0422 04:13:51.624938       1 instances.go:158] instances.InstanceExistsByProviderID() CACHED with 42159afd-43f4-981f-2bed-4048da618451
I0422 04:13:51.624969       1 instances.go:78] instances.NodeAddressesByProviderID() CACHED with 42159afd-43f4-981f-2bed-4048da618451
I0422 04:13:51.628733       1 instances.go:158] instances.InstanceExistsByProviderID() CACHED with 4215bc17-179f-bf15-72cf-aa34edc25be5
I0422 04:13:51.628758       1 instances.go:78] instances.NodeAddressesByProviderID() CACHED with 4215bc17-179f-bf15-72cf-aa34edc25be5
I0422 04:13:51.631789       1 instances.go:158] instances.InstanceExistsByProviderID() CACHED with 4215c284-e0d4-22f4-ffa1-3c2e120325e2
I0422 04:13:51.631806       1 instances.go:78] instances.NodeAddressesByProviderID() CACHED with 4215c284-e0d4-22f4-ffa1-3c2e120325e2
I0422 04:13:51.634609       1 instances.go:158] instances.InstanceExistsByProviderID() CACHED with 4215952a-d7bc-2a99-ae73-f4e6b1c7ed9a
I0422 04:13:51.634628       1 instances.go:78] instances.NodeAddressesByProviderID() CACHED with 4215952a-d7bc-2a99-ae73-f4e6b1c7ed9a
I0422 04:18:51.639252       1 instances.go:158] instances.InstanceExistsByProviderID() CACHED with 42159afd-43f4-981f-2bed-4048da618451
I0422 04:18:51.639281       1 instances.go:78] instances.NodeAddressesByProviderID() CACHED with 42159afd-43f4-981f-2bed-4048da618451
I0422 04:18:51.642740       1 instances.go:158] instances.InstanceExistsByProviderID() CACHED with 4215bc17-179f-bf15-72cf-aa34edc25be5
I0422 04:18:51.642757       1 instances.go:78] instances.NodeAddressesByProviderID() CACHED with 4215bc17-179f-bf15-72cf-aa34edc25be5
I0422 04:18:51.646604       1 instances.go:158] instances.InstanceExistsByProviderID() CACHED with 4215c284-e0d4-22f4-ffa1-3c2e120325e2
I0422 04:18:51.646620       1 instances.go:78] instances.NodeAddressesByProviderID() CACHED with 4215c284-e0d4-22f4-ffa1-3c2e120325e2
I0422 04:18:51.651346       1 instances.go:158] instances.InstanceExistsByProviderID() CACHED with 4215952a-d7bc-2a99-ae73-f4e6b1c7ed9a
I0422 04:18:51.651391       1 instances.go:78] instances.NodeAddressesByProviderID() CACHED with 4215952a-d7bc-2a99-ae73-f4e6b1c7ed9a
I0422 04:23:51.657459       1 instances.go:158] instances.InstanceExistsByProviderID() CACHED with 4215952a-d7bc-2a99-ae73-f4e6b1c7ed9a
I0422 04:23:51.657486       1 instances.go:78] instances.NodeAddressesByProviderID() CACHED with 4215952a-d7bc-2a99-ae73-f4e6b1c7ed9a
I0422 04:23:51.661731       1 instances.go:158] instances.InstanceExistsByProviderID() CACHED with 42159afd-43f4-981f-2bed-4048da618451
I0422 04:23:51.661756       1 instances.go:78] instances.NodeAddressesByProviderID() CACHED with 42159afd-43f4-981f-2bed-4048da618451
I0422 04:23:51.665657       1 instances.go:158] instances.InstanceExistsByProviderID() CACHED with 4215bc17-179f-bf15-72cf-aa34edc25be5
I0422 04:23:51.665683       1 instances.go:78] instances.NodeAddressesByProviderID() CACHED with 4215bc17-179f-bf15-72cf-aa34edc25be5
I0422 04:23:51.669451       1 instances.go:158] instances.InstanceExistsByProviderID() CACHED with 4215c284-e0d4-22f4-ffa1-3c2e120325e2
I0422 04:23:51.669479       1 instances.go:78] instances.NodeAddressesByProviderID() CACHED with 4215c284-e0d4-22f4-ffa1-3c2e120325e2
I0422 04:28:51.674922       1 instances.go:158] instances.InstanceExistsByProviderID() CACHED with 4215bc17-179f-bf15-72cf-aa34edc25be5
I0422 04:28:51.674950       1 instances.go:78] instances.NodeAddressesByProviderID() CACHED with 4215bc17-179f-bf15-72cf-aa34edc25be5
I0422 04:28:51.678326       1 instances.go:158] instances.InstanceExistsByProviderID() CACHED with 4215c284-e0d4-22f4-ffa1-3c2e120325e2
I0422 04:28:51.678342       1 instances.go:78] instances.NodeAddressesByProviderID() CACHED with 4215c284-e0d4-22f4-ffa1-3c2e120325e2
I0422 04:28:51.681584       1 instances.go:158] instances.InstanceExistsByProviderID() CACHED with 4215952a-d7bc-2a99-ae73-f4e6b1c7ed9a
I0422 04:28:51.681608       1 instances.go:78] instances.NodeAddressesByProviderID() CACHED with 4215952a-d7bc-2a99-ae73-f4e6b1c7ed9a
I0422 04:28:51.685152       1 instances.go:158] instances.InstanceExistsByProviderID() CACHED with 42159afd-43f4-981f-2bed-4048da618451
I0422 04:28:51.685176       1 instances.go:78] instances.NodeAddressesByProviderID() CACHED with 42159afd-43f4-981f-2bed-4048da618451
I0422 04:33:51.689711       1 instances.go:158] instances.InstanceExistsByProviderID() CACHED with 4215bc17-179f-bf15-72cf-aa34edc25be5
I0422 04:33:51.689740       1 instances.go:78] instances.NodeAddressesByProviderID() CACHED with 4215bc17-179f-bf15-72cf-aa34edc25be5
I0422 04:33:51.694118       1 instances.go:158] instances.InstanceExistsByProviderID() CACHED with 4215c284-e0d4-22f4-ffa1-3c2e120325e2
I0422 04:33:51.694140       1 instances.go:78] instances.NodeAddressesByProviderID() CACHED with 4215c284-e0d4-22f4-ffa1-3c2e120325e2
I0422 04:33:51.697442       1 instances.go:158] instances.InstanceExistsByProviderID() CACHED with 4215952a-d7bc-2a99-ae73-f4e6b1c7ed9a
I0422 04:33:51.697480       1 instances.go:78] instances.NodeAddressesByProviderID() CACHED with 4215952a-d7bc-2a99-ae73-f4e6b1c7ed9a
I0422 04:33:51.700727       1 instances.go:158] instances.InstanceExistsByProviderID() CACHED with 42159afd-43f4-981f-2bed-4048da618451
I0422 04:33:51.700747       1 instances.go:78] instances.NodeAddressesByProviderID() CACHED with 42159afd-43f4-981f-2bed-4048da618451
I0422 04:38:51.705409       1 instances.go:158] instances.InstanceExistsByProviderID() CACHED with 4215952a-d7bc-2a99-ae73-f4e6b1c7ed9a
I0422 04:38:51.705434       1 instances.go:78] instances.NodeAddressesByProviderID() CACHED with 4215952a-d7bc-2a99-ae73-f4e6b1c7ed9a
I0422 04:38:51.709413       1 instances.go:158] instances.InstanceExistsByProviderID() CACHED with 42159afd-43f4-981f-2bed-4048da618451
I0422 04:38:51.709429       1 instances.go:78] instances.NodeAddressesByProviderID() CACHED with 42159afd-43f4-981f-2bed-4048da618451
I0422 04:38:51.713203       1 instances.go:158] instances.InstanceExistsByProviderID() CACHED with 4215bc17-179f-bf15-72cf-aa34edc25be5
I0422 04:38:51.713221       1 instances.go:78] instances.NodeAddressesByProviderID() CACHED with 4215bc17-179f-bf15-72cf-aa34edc25be5
I0422 04:38:51.716294       1 instances.go:158] instances.InstanceExistsByProviderID() CACHED with 4215c284-e0d4-22f4-ffa1-3c2e120325e2
I0422 04:38:51.716319       1 instances.go:78] instances.NodeAddressesByProviderID() CACHED with 4215c284-e0d4-22f4-ffa1-3c2e120325e2
I0422 04:43:51.722249       1 instances.go:158] instances.InstanceExistsByProviderID() CACHED with 4215bc17-179f-bf15-72cf-aa34edc25be5
I0422 04:43:51.722274       1 instances.go:78] instances.NodeAddressesByProviderID() CACHED with 4215bc17-179f-bf15-72cf-aa34edc25be5
I0422 04:43:51.725728       1 instances.go:158] instances.InstanceExistsByProviderID() CACHED with 4215c284-e0d4-22f4-ffa1-3c2e120325e2
I0422 04:43:51.725751       1 instances.go:78] instances.NodeAddressesByProviderID() CACHED with 4215c284-e0d4-22f4-ffa1-3c2e120325e2
I0422 04:43:51.729276       1 instances.go:158] instances.InstanceExistsByProviderID() CACHED with 4215952a-d7bc-2a99-ae73-f4e6b1c7ed9a
I0422 04:43:51.729298       1 instances.go:78] instances.NodeAddressesByProviderID() CACHED with 4215952a-d7bc-2a99-ae73-f4e6b1c7ed9a
I0422 04:43:51.732729       1 instances.go:158] instances.InstanceExistsByProviderID() CACHED with 42159afd-43f4-981f-2bed-4048da618451
I0422 04:43:51.732742       1 instances.go:78] instances.NodeAddressesByProviderID() CACHED with 42159afd-43f4-981f-2bed-4048da618451

Were you able to verify that cloud-provider-vsphere was installed and running correctly?

![pod-details](https://user-images.githubusercontent.com/12782430/79942980-6c41f480-8485-11ea-8fb8-7ec8cb1fe2ce.JPG)


Can you also attach a print of node labels?

![node](https://user-images.githubusercontent.com/12782430/79943175-d8bcf380-8485-11ea-8c68-b308a37bc9fa.JPG)


![csi-attacher](https://user-images.githubusercontent.com/12782430/79943271-191c7180-8486-11ea-867a-57a2dbe2d22d.JPG)

**Comment by dvonthenen** [comment]
@adityasaxena88  I can see the node labels getting applied by the CPI (node name, VM properties, etc). It looks like the CPI is functioning properly. This appears to be a CSI storage driver related issue... you might need to file an issue in the following repo (https://github.com/kubernetes-sigs/vsphere-csi-driver/). If you can include logs for the CSI controller where the attach happens, I might be able to give you a quick answer/look with your problem.

**Comment by adityasaxena88** [comment]
![csi-controller](https://user-images.githubusercontent.com/12782430/80010450-0fc3f100-84e8-11ea-82d9-e4e461d9666c.JPG)



![csi-aatacher](https://user-images.githubusercontent.com/12782430/80010459-1488a500-84e8-11ea-87a0-2f855964b107.JPG)

**Comment by dvonthenen** [comment]
It looks like the deploy of the CSI driver has changed quite a bit along with the deployment YAML... Can you take this info and open a ticket in the https://github.com/kubernetes-sigs/vsphere-csi-driver/ repo? The people working on the CSI team should be able to better help you with this issue.

**Comment by adityasaxena88** [comment]
Vmtools is installed on all machine. Even disk.EnableUUID is set to True. 

I can see from the log that 

I0422 16:28:19.976955       1 csi_handler.go:512] CSINode k8s-worker-2-aditya does not contain driver csi.vsphere.vmware.com
I0422 16:28:19.976964       1 csi_handler.go:382] Saving attach error to "csi-8e1d24fa4bd5a4c250cb9f6566ae22317c1fa297889c162c5fbbf1921c5b214d"
I0422 16:28:19.981306       1 controller.go:141] Ignoring VolumeAttachment "csi-8e1d24fa4bd5a4c250cb9f6566ae22317c1fa297889c162c5fbbf1921c5b214d" change
I0422 16:28:19.981412       1 csi_handler.go:392] Saved attach error to "csi-8e1d24fa4bd5a4c250cb9f6566ae22317c1fa297889c162c5fbbf1921c5b214d"


that node doesn't contain the driver is it normal thing or driver should be installed.

**Comment by dvonthenen** [comment]
yea, I think there was a recent change to that if I recall... but i don't have the details. definitely follow up on the storage driver repo. it looks like you created an issue on that repo... so going to close this issue out here

/close
