### ISSUE TITLE
invalid url

### ISSUE THREAD

**Issue by wyyxd2017** [kubernetes/cloud-provider-vsphere#333]
#330 
I found their have many invaild url in this repository！Some paths have been deleted, they no longer exist, and some are no longer valid.

ex: https://github.com/vmware/govmomi/tree/master/govc

**Comment by dvonthenen** [comment]
Hi @wyyxd2017 

If you find an issue in https://github.com/vmware/govmomi, you can file a PR or issue in that repo. 

By the way, thanks again for helping out with fixing dead links and etc! 
It's been most helpful!

**Comment by frapposelli** [comment]
looks like the link you provided works correctly, feel free to open a new issue for broken links

/close
