### ISSUE TITLE
Implement unit tests for pkg/cloudprovider/vsphere

### ISSUE THREAD

**Issue by frapposelli** [kubernetes/cloud-provider-vsphere#34]
We need unit tests for the cloud provider code to ensure we do not introduce breaking changes.

Currently `pkg/cloudprovider/vsphere` has no unit tests, we should implement an initial set of unit tests for the package.

These tests should be part of the `unit` Makefile target that is automatically run as part of the `test` target, which in turn is run by our CI job.

/kind feature

**Comment by frapposelli** [comment]
@akutz FYI

**Comment by dvonthenen** [comment]
Currently working on this issue... just posted this so I can get notified when someone else posts on it 😄

**Comment by dougm** [comment]
A few pointers to get started:

https://github.com/vmware/govmomi/tree/master/vcsim

https://godoc.org/github.com/vmware/govmomi/simulator#example-VPX

There are existing tests in-tree, some can run against real vCenter or vcsim via: https://github.com/kubernetes/kubernetes/blob/652cebcba54a88d30d631e6bab1d829d01e0bf1d/pkg/cloudprovider/providers/vsphere/vsphere_test.go#L151

A few others in vclib that are vcsim-only: https://github.com/kubernetes/kubernetes/blob/652cebcba54a88d30d631e6bab1d829d01e0bf1d/pkg/cloudprovider/providers/vsphere/vclib/virtualmachine_test.go#L30

**Comment by dvonthenen** [comment]
Thanks for the info!

**Comment by frapposelli** [comment]
/assign @dvonthenen 

🎉

**Comment by dvonthenen** [comment]
Submitted PR https://github.com/kubernetes/cloud-provider-vsphere/pull/39
