### ISSUE TITLE
Chart: vsphere-cloud-controller-manager daemonset bringup issue

### ISSUE THREAD

**Issue by zhoudayongdennis** [kubernetes/cloud-provider-vsphere#340]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug
> /kind feature

after helm install cpi on cluster, failed to bring up DaemonSet on three control nodes, and one was UP and the other 2 with same error message "failed to create listener: failed to listen on 0.0.0.0:10258: listen tcp 0.0.0.0:10258: bind: address already in use".

Not sure how it caused such kind of issues.

CPI version used 1.1.0.

[root@tesla-auto-2006-v67-os7-v22-control-01 templates]# kubectl get service -A | grep vsphere
kube-system   vsphere-cloud-controller-manager   NodePort    10.254.50.106    <none>                                43001:30801/TCP                       10m
[root@tesla-auto-2006-v67-os7-v22-control-01 templates]# kubectl get pods -A | grep vsphere
kube-system   vsphere-cloud-controller-manager-ftjfp                           1/1     Running            0          10m
kube-system   vsphere-cloud-controller-manager-hnq2l                           0/1     CrashLoopBackOff   6          10m
kube-system   vsphere-cloud-controller-manager-n2xjd                           0/1     CrashLoopBackOff   6          10m
[root@tesla-auto-2006-v67-os7-v22-control-01 templates]# kubectl get nodes -owide
NAME                                     STATUS   ROLES    AGE     VERSION   INTERNAL-IP       EXTERNAL-IP       OS-IMAGE                KERNEL-VERSION                CONTAINER-RUNTIME
tesla-auto-2006-v67-os7-v22-control-01   Ready    <none>   3h24m   v1.18.3   172.26.1.21       <none>            CentOS Linux 7 (Core)   4.18.0-147.5.1.el8_1.x86_64   docker://19.3.11
tesla-auto-2006-v67-os7-v22-control-02   Ready    <none>   3h24m   v1.18.3   172.26.1.22       <none>            CentOS Linux 7 (Core)   4.18.0-147.5.1.el8_1.x86_64   docker://19.3.11
tesla-auto-2006-v67-os7-v22-control-03   Ready    <none>   3h24m   v1.18.3   172.26.1.23       <none>            CentOS Linux 7 (Core)   4.18.0-147.5.1.el8_1.x86_64   docker://19.3.11
tesla-auto-2006-v67-os7-v22-edge-01      Ready    <none>   3h24m   v1.18.3   135.111.166.143   135.111.166.143   CentOS Linux 7 (Core)   4.18.0-147.5.1.el8_1.x86_64   docker://19.3.11
tesla-auto-2006-v67-os7-v22-edge-02      Ready    <none>   3h24m   v1.18.3   172.26.1.27       <none>            CentOS Linux 7 (Core)   4.18.0-147.5.1.el8_1.x86_64   docker://19.3.11
tesla-auto-2006-v67-os7-v22-worker-01    Ready    <none>   3h24m   v1.18.3   172.26.1.24       <none>            CentOS Linux 7 (Core)   4.18.0-147.5.1.el8_1.x86_64   docker://19.3.11
tesla-auto-2006-v67-os7-v22-worker-02    Ready    <none>   3h24m   v1.18.3   172.26.1.25       <none>            CentOS Linux 7 (Core)   4.18.0-147.5.1.el8_1.x86_64   docker://19.3.11
[root@tesla-auto-2006-v67-os7-v22-control-01 templates]# kubectl logs -nkube-system   vsphere-cloud-controller-manager-hnq2l
I0608 08:13:07.578467       1 flags.go:33] FLAG: --address="0.0.0.0"
I0608 08:13:07.579713       1 flags.go:33] FLAG: --allocate-node-cidrs="false"
I0608 08:13:07.579752       1 flags.go:33] FLAG: --allow-untagged-cloud="false"
I0608 08:13:07.579761       1 flags.go:33] FLAG: --alsologtostderr="false"
I0608 08:13:07.579772       1 flags.go:33] FLAG: --authentication-kubeconfig=""
I0608 08:13:07.579783       1 flags.go:33] FLAG: --authentication-skip-lookup="false"
I0608 08:13:07.579791       1 flags.go:33] FLAG: --authentication-token-webhook-cache-ttl="10s"
I0608 08:13:07.579802       1 flags.go:33] FLAG: --authentication-tolerate-lookup-failure="false"
I0608 08:13:07.579809       1 flags.go:33] FLAG: --authorization-always-allow-paths="[/healthz]"
I0608 08:13:07.579828       1 flags.go:33] FLAG: --authorization-kubeconfig=""
I0608 08:13:07.579836       1 flags.go:33] FLAG: --authorization-webhook-cache-authorized-ttl="10s"
I0608 08:13:07.579845       1 flags.go:33] FLAG: --authorization-webhook-cache-unauthorized-ttl="10s"
I0608 08:13:07.579853       1 flags.go:33] FLAG: --bind-address="0.0.0.0"
I0608 08:13:07.579862       1 flags.go:33] FLAG: --cert-dir=""
I0608 08:13:07.579869       1 flags.go:33] FLAG: --cidr-allocator-type="RangeAllocator"
I0608 08:13:07.579877       1 flags.go:33] FLAG: --client-ca-file=""
I0608 08:13:07.579884       1 flags.go:33] FLAG: --cloud-config="/etc/cloud/vsphere.conf"
I0608 08:13:07.579892       1 flags.go:33] FLAG: --cloud-provider="vsphere"
I0608 08:13:07.579900       1 flags.go:33] FLAG: --cluster-cidr=""
I0608 08:13:07.579908       1 flags.go:33] FLAG: --cluster-name="kubernetes"
I0608 08:13:07.579916       1 flags.go:33] FLAG: --concurrent-service-syncs="1"
I0608 08:13:07.579926       1 flags.go:33] FLAG: --configure-cloud-routes="true"
I0608 08:13:07.579933       1 flags.go:33] FLAG: --contention-profiling="false"
I0608 08:13:07.579941       1 flags.go:33] FLAG: --controller-start-interval="0s"
I0608 08:13:07.579948       1 flags.go:33] FLAG: --controllers="[*]"
I0608 08:13:07.579959       1 flags.go:33] FLAG: --external-cloud-volume-plugin=""
I0608 08:13:07.579966       1 flags.go:33] FLAG: --feature-gates=""
I0608 08:13:07.579978       1 flags.go:33] FLAG: --help="false"
I0608 08:13:07.579986       1 flags.go:33] FLAG: --http2-max-streams-per-connection="0"
I0608 08:13:07.579996       1 flags.go:33] FLAG: --kube-api-burst="30"
I0608 08:13:07.580003       1 flags.go:33] FLAG: --kube-api-content-type="application/vnd.kubernetes.protobuf"
I0608 08:13:07.580012       1 flags.go:33] FLAG: --kube-api-qps="20"
I0608 08:13:07.580037       1 flags.go:33] FLAG: --kubeconfig=""
I0608 08:13:07.580045       1 flags.go:33] FLAG: --leader-elect="true"
I0608 08:13:07.580052       1 flags.go:33] FLAG: --leader-elect-lease-duration="15s"
I0608 08:13:07.580061       1 flags.go:33] FLAG: --leader-elect-renew-deadline="10s"
I0608 08:13:07.580068       1 flags.go:33] FLAG: --leader-elect-resource-lock="endpoints"
I0608 08:13:07.580076       1 flags.go:33] FLAG: --leader-elect-retry-period="2s"
I0608 08:13:07.580083       1 flags.go:33] FLAG: --log-backtrace-at=":0"
I0608 08:13:07.580096       1 flags.go:33] FLAG: --log-dir=""
I0608 08:13:07.580105       1 flags.go:33] FLAG: --log-file=""
I0608 08:13:07.580112       1 flags.go:33] FLAG: --log-file-max-size="1800"
I0608 08:13:07.580120       1 flags.go:33] FLAG: --log-flush-frequency="5s"
I0608 08:13:07.580128       1 flags.go:33] FLAG: --logtostderr="true"
I0608 08:13:07.580136       1 flags.go:33] FLAG: --master=""
I0608 08:13:07.580143       1 flags.go:33] FLAG: --min-resync-period="12h0m0s"
I0608 08:13:07.580151       1 flags.go:33] FLAG: --node-monitor-period="5s"
I0608 08:13:07.580159       1 flags.go:33] FLAG: --node-status-update-frequency="5m0s"
I0608 08:13:07.580166       1 flags.go:33] FLAG: --node-sync-period="0s"
I0608 08:13:07.580174       1 flags.go:33] FLAG: --port="0"
I0608 08:13:07.580181       1 flags.go:33] FLAG: --profiling="false"
I0608 08:13:07.580189       1 flags.go:33] FLAG: --requestheader-allowed-names="[]"
I0608 08:13:07.580209       1 flags.go:33] FLAG: --requestheader-client-ca-file=""
I0608 08:13:07.580216       1 flags.go:33] FLAG: --requestheader-extra-headers-prefix="[x-remote-extra-]"
I0608 08:13:07.580227       1 flags.go:33] FLAG: --requestheader-group-headers="[x-remote-group]"
I0608 08:13:07.580239       1 flags.go:33] FLAG: --requestheader-username-headers="[x-remote-user]"
I0608 08:13:07.580249       1 flags.go:33] FLAG: --route-reconciliation-period="10s"
I0608 08:13:07.580257       1 flags.go:33] FLAG: --secure-port="10258"
I0608 08:13:07.580270       1 flags.go:33] FLAG: --skip-headers="false"
I0608 08:13:07.580282       1 flags.go:33] FLAG: --skip-log-headers="false"
I0608 08:13:07.580291       1 flags.go:33] FLAG: --stderrthreshold="2"
I0608 08:13:07.580298       1 flags.go:33] FLAG: --tls-cert-file=""
I0608 08:13:07.580306       1 flags.go:33] FLAG: --tls-cipher-suites="[]"
I0608 08:13:07.580323       1 flags.go:33] FLAG: --tls-min-version=""
I0608 08:13:07.580331       1 flags.go:33] FLAG: --tls-private-key-file=""
I0608 08:13:07.580338       1 flags.go:33] FLAG: --tls-sni-cert-key="[]"
I0608 08:13:07.580348       1 flags.go:33] FLAG: --use-service-account-credentials="false"
I0608 08:13:07.580356       1 flags.go:33] FLAG: --v="1"
I0608 08:13:07.580363       1 flags.go:33] FLAG: --version="false"
I0608 08:13:07.580374       1 flags.go:33] FLAG: --vmodule=""
I0608 08:13:07.980013       1 serving.go:319] Generated self-signed cert in-memory
failed to create listener: failed to listen on 0.0.0.0:10258: listen tcp 0.0.0.0:10258: bind: address already in use

**Comment by dvonthenen** [comment]
The Helm chart currently doesn't support multi-master. If you do want to add the support, you need to use the manifests in the repo and then change the deployment so the pods end up on different masters using the affinity and anti-affinity rules.

https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#affinity-and-anti-affinity

/feature

**Comment by andrewsykim** [comment]
@dvonthenen does the helm charts also need to be updated to tolerate the not-ready taints as per https://github.com/kubernetes/cloud-provider-vsphere/pull/339 ?

**Comment by zhoudayongdennis** [comment]
there was another Cloud-Controller-Managers (CCM) deployed in the same cluster, which introduced the port conflict, and correct it and wait for result.

**Comment by dvonthenen** [comment]
> @dvonthenen does the helm charts also need to be updated to tolerate the not-ready taints as per #339 ?

Yes, the Helm chart does need to be updated. One of the YAML specs in this repo got stale and I updated it in a yet to be submitted PR.

**Comment by dvonthenen** [comment]
> there was another Cloud-Controller-Managers (CCM) deployed in the same cluster, which introduced the port conflict, and correct it and wait for result.

Yup, that isn't a supported configuration.

**Comment by dvonthenen** [comment]
This should be addressed in this PR for charts repo. If not, please reopen.
https://github.com/helm/charts/pull/23682

/close
