### ISSUE TITLE
vSphere CSI driver documentation is outdated. 

### ISSUE THREAD

**Issue by RaunakShah** [kubernetes/cloud-provider-vsphere#341]
**Is this a BUG REPORT or FEATURE REQUEST?**:

 /kind bug

**What happened**:

Documentation for CSI driver points to the wrong page and has outdated information. Filing this issue to get that fixed. 
 
**What you expected to happen**:
CSI driver installation to be uptodate. 

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- vsphere-cloud-controller-manager version:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by dvonthenen** [comment]
Closing this issue since PR was merged

/close
