### ISSUE TITLE
Support node deletion of terminated VMs

### ISSUE THREAD

**Issue by andrewsykim** [kubernetes/cloud-provider-vsphere#348]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind feature

In the past we opted not to delete the node object of a terminated VM due to certain failure scenarios.  However, this behavior is not consistent with other cloud providers. We should re-evaluate if we want to re-introduce this behavior.

Specifically, `InstanceExistsByProviderID` should return `false, nil` when the VM on vSphere no longer exists, not if the Kubernetes node object exists. This cleans up Kubernetes node objects automatically in the event that a VM is deleted.

**Comment by frapposelli** [comment]
I'm fine with this behavior being reinstated as the default, but we could use a feature toggle to enable use cases that require VMs to be persisted even when deleted from the underlying platform

**Comment by jayunit100** [comment]
Is this inflamed by using a CNI like calico that makes a new eth pair for every pod?  In other CNIs like antrea, you only get one eth per pod.  examples below respectively of antrea/calico.

```
# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: tunl0@NONE: <NOARP,UP,LOWER_UP> mtu 1440 qdisc noqueue state UNKNOWN group default qlen 1000
    link/ipip 0.0.0.0 brd 0.0.0.0
    inet 192.168.0.192/32 brd 192.168.0.192 scope global tunl0
       valid_lft forever preferred_lft forever
90: eth0@if91: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
    link/ether 02:42:ac:12:00:03 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 172.18.0.3/16 brd 172.18.255.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fc00:f853:ccd:e793::3/64 scope global nodad 
       valid_lft forever preferred_lft forever
    inet6 fe80::42:acff:fe12:3/64 scope link 
       valid_lft forever preferred_lft forever

```

But calico... you get alot ... 
```
48: califa2a9ff6cf0@if4: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1440 qdisc noqueue state UP group default 
    link/ether ee:ee:ee:ee:ee:ee brd ff:ff:ff:ff:ff:ff link-netns cni-1cf41e2c-efbf-fd1a-e0f1-b3cc901043c2
49: caliea3410fd406@if4: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1440 qdisc noqueue state UP group default 
    link/ether ee:ee:ee:ee:ee:ee brd ff:ff:ff:ff:ff:ff link-netns cni-d48b9d5e-dc93-0871-8bf4-1ad9d0a504fd
50: calif41f4841036@if4: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1440 qdisc noqueue state UP group default 
    link/ether ee:ee:ee:ee:ee:ee brd ff:ff:ff:ff:ff:ff link-netns cni-113ff084-f3bd-b021-30b6-aef3df5d7ca6
51: caliddd16dddcc5@if4: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1440 qdisc noqueue state UP group default 
    link/ether ee:ee:ee:ee:ee:ee brd ff:ff:ff:ff:ff:ff link-netns cni-dc78710b-dbbe-f6b1-e851-839e9252eaab
52: cali8af2ec2bb27@if4: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1440 qdisc noqueue state UP group default 
    link/ether ee:ee:ee:ee:ee:ee brd ff:ff:ff:ff:ff:ff link-netns cni-2e70dfc8-8dc6-bdd7-9b3a-9ef371e383e3
```

... So does any CNI on a cluster w/ > 16 pods basically expose this? or am i misunderstanding the issue maybe.

**Comment by jayunit100** [comment]
(deleted my above comment, i meant to put it in #338)

**Comment by dvonthenen** [comment]
> I'm fine with this behavior being reinstated as the default, but we could use a feature toggle to enable use cases that require VMs to be persisted even when deleted from the underlying platform

Yea, I'm concerned with that scenario as well as ones where VM's aren't accessible by Center but where the VM/k8s-node is still running. Like a long lived network partition event. One that happens all the time is when the ESX host gets disconnected from Center but is ultimately still running, is connect to the k8s cluster, and can still take on additional k8s workloads. A switch would be a good way to allow both behaviors.

**Comment by dvonthenen** [comment]
PR Merged...
/close
