### ISSUE TITLE
Use a better property for reconciliation between nodes and VMs

### ISSUE THREAD

**Issue by frapposelli** [kubernetes/cloud-provider-vsphere#35]
The current in-tree provider code assumes that the CCM code is running on every node of the cluster and uses the VM UUID (fetched locally from `/sys/class/dmi/id/product_serial`) to perform reconciliation between the kubernetes node and its underlying VM.

With the out-of-tree provider, that assumption is not true anymore and the current code uses DNS names to perform reconciliation between node and VM, while this works in practice, it is suboptimal.

We should investigate a better way to implement this reconciliation.

/kind feature

**Comment by dvonthenen** [comment]
Submitted PR: https://github.com/kubernetes/cloud-provider-vsphere/pull/43

**Comment by frapposelli** [comment]
closing as this was fixed by #43
