### ISSUE TITLE
issues with vcenter fqdns that contains uppercase

### ISSUE THREAD

**Issue by yastij** [kubernetes/cloud-provider-vsphere#351]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 

/kind bug

it seems like we are lower casing the vcenter fqdn before storing in the cache https://github.com/kubernetes/cloud-provider-vsphere/blob/6872a0bb96eb62712a5896744b00bd1d78f88241/pkg/common/credentialmanager/credentialmanager.go#L196-L208, but when trying to access credentials we are using vcenter fqdn as is, see:

https://github.com/kubernetes/cloud-provider-vsphere/blob/6872a0bb96eb62712a5896744b00bd1d78f88241/pkg/common/connectionmanager/connectionmanager.go#L160,

/assign @dvonthenen 

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- vsphere-cloud-controller-manager version:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by dvonthenen** [comment]
Thanks @yastij for catching this!

**Comment by vuil** [comment]
@dvonthenen is this an issue that will be addressed soon?

**Comment by dvonthenen** [comment]
The PR (above) to fix this was opened the same day the issue was filed. Just waiting for feedback or a merge on this PR in order to close this out.
