### ISSUE TITLE
Configuration and HA enhancements for running CCM external of an cluster

### ISSUE THREAD

**Issue by MaxRink** [kubernetes/cloud-provider-vsphere#356]
/kind feature

We are currently using Cluster API with the vSphere provider. During that process we stumbled across the dependency to run the CCM internally of the created cluster. We would like to remove that dependency because of security reasons ( if the workload clusters have no way to even contact the vcenter, they cant influence other VMs running on the shared cluster) The CAPV Issue is tracked here: https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues/924

In our experminets with running the CCM externally, which is working in general, we came across two Issues:

- The current way to outsource credentials into an secret doesnt work, if you configure a kubeconfig  the CCM looks in the workload cluster its watching for the secrets. It would be nice to have an way to pass the password as secret without needing to specify the whole config as secret.

- HA-mode doesnt work as leader election is broken for the above Set-Up. It would be nice to run multiple replicas in the mgmt cluster to tolerate node failures there.
Currently this is broken ( see https://github.com/kubernetes/cloud-provider-vsphere/issues/354 ) for more information

**Comment by dvonthenen** [comment]
My KubeCon EU session is exactly this use case. You need to have individual vCenter accounts per workload cluster. Using vCenter RBAC, restrict the user access to only that particular vSphere folder or Resource Group. That should limit the scope to exactly those users VMs.

**Comment by MaxRink** [comment]
hi @dvonthenen , 
The Link above is broken. I also think its not directly fitting our case, as our securitiy requirement is actually no network connectivity from the workload clusters to the vcenter.
Running the CCM on the CAPI mgmt cluster works fine, as that is already the CPOM. Scoping ontop of that is an added bonus, but keeping the ccm external is basically an hard requirement. Its only used for providing providerIDs to nodes and for removing taints, as we dont use the CSI.
My Issue is handeling that credentials in the first place, as  "secret-name" and "secret-namespace" dont work for pulling in secrets and i havent found a way to pass them via env or in another mount.
If i write them directly in the config, deploying it works just fine, but secret handeling becomes a pain as i need to seperate them from other objects for security reasons (currently we use SealedSecrets for that)

**Comment by dvonthenen** [comment]
You should be able to use CCM installed on the management cluster only. To do that, create a tenant configuration/entry per tenant vSphere account and use vSphere Role Based Access to limit account permissions to just their resource pool/cluster.
