### ISSUE TITLE
cloud provider could not be initialized: could not init cloud provider "vsphere": 1:1: expected section header

### ISSUE THREAD

**Issue by abregar** [kubernetes/cloud-provider-vsphere#357]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>

/kind bug
> /kind feature

**What happened**: 
Following the docs/book  _kubernetes-on-vsphere-with-kubeadm_ seems after the change _Initial implementation for YAML based config_ controllermanager.go crashed after announcing 1:1: expected section header
[crashed_manager.log](https://github.com/kubernetes/cloud-provider-vsphere/files/4960736/crashed_manager.log)

**What you expected to happen**:
Cloud provider initialized successfully 

**How to reproduce it (as minimally and precisely as possible)**:
Use manifests prior named change (csi-vsphere.conf not in yaml format) and try to initialize cloud provider

**Anything else we need to know?**:
csi-vsphere.conf was converted from conf to yaml as written in docs

**Environment**:
- vsphere-cloud-controller-manager version: gcr.io/cloud-provider-vsphere/cpi/release/manager@sha256:64de5c7f10e55703142383fade40886091528ca505f00c98d57e27f10f04fc03
- OS (e.g. from /etc/os-release): CentOS Linux release 7.8.2003 (Core)
- Kernel (e.g. `uname -a`): 3.10.0-1127.13.1.el7.x86_64
- Install tools: rancher
- Others:

**Comment by dvonthenen** [comment]
Hi @abregar!

We haven't cut a release yet of the CPI, so currently the tags for the CPI in GCR point to 1.1.0 and latest still only support the INI configuration. Please use the documentation for the INI based format here:
https://github.com/kubernetes/cloud-provider-vsphere/blob/c08d3f932463ff9579c07f6a283424ee7f0aec47/docs/book/tutorials/kubernetes-on-vsphere-with-kubeadm.md

It might be worth keeping the INI based configuration through and just noting that it's legacy. Will open up a PR to do that this morning.

**Comment by dvonthenen** [comment]
Hi @abregar 

Updated the documentation to include the `INI` based configuration for older versions of the CPI. If you are still having issues, please let me know.

/close

**Comment by abregar** [comment]
Thank you for the clarification. Since I do like the yaml format, is there any estimated date on new CPI version release supporting this feature (and all the fixes since 1.1.0)?

**Comment by dvonthenen** [comment]
I'm in the process of working on that release right now.

Also, since this might trip other people up (myself included just now), the port value is no longer a string but an int.

Correct:
```
global:
  port: 443
```

Incorrect:
```
global:
  port: "443"
```
