### ISSUE TITLE
Run conformance test for every patch version of Kubernetes and push results to testgrid

### ISSUE THREAD

**Issue by frapposelli** [kubernetes/cloud-provider-vsphere#38]
As outlined in [KEP0018](https://github.com/kubernetes/community/blob/master/keps/sig-cloud-provider/0018-testgrid-conformance-e2e.md), SIG Cloud Provider is asking that every Kubernetes cloud provider reports conformance test results for every patch version of Kubernetes at the minimum. Running conformance tests against master and on pre-release versions are highly encouraged but will not be a requirement.

/kind feature

**Comment by frapposelli** [comment]
/assign @akutz 

:tada:

**Comment by figo** [comment]
we are setting up CI job to run k8s conformance test suite with CCM vSphere, the workflow is like below:
```
[Travis-CI] --> [Launch a CI Container]

[CI Container]:   
        (1) Fetch artifacts
        (2) Create k8s cluster
        (3) Setup CCM vSphere
        (4) Run conformance suite
        (5) Upload test result to testgrid
```
It have not been finalized yet, but an example of CI container is available at:
https://github.com/figo/k8s-conformance-ci

**Comment by clintkitson** [comment]
bump @akutz
