### ISSUE TITLE
CPI 1.2 deletes a node object right after its recreation with the same name

### ISSUE THREAD

**Issue by AntonSmolkov** [kubernetes/cloud-provider-vsphere#397]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 

/kind bug
> /kind feature

https://github.com/kubernetes/cloud-provider-vsphere/issues/381#issuecomment-697798343

**Comment by AntonSmolkov** [comment]
@gwang550 Hi. Created a separate bug to track it.

**Comment by dvonthenen** [comment]
Hi @AntonSmolkov 

Did you try using 1.2.1? The CPI 1.2.0 does have that issue, but should be addressed. If you are using 1.2.0, could you provide some logs with `--v=6`? Thanks!

**Comment by AntonSmolkov** [comment]
@dvonthenen 
Hi. I use CPI 1.2.**1**. I mentioned it the related issue.
here is --v=6 log:
[cpi_deletes_wrong_node.log](https://github.com/kubernetes/cloud-provider-vsphere/files/5423340/cpi_deletes_wrong_node.log)
![image](https://user-images.githubusercontent.com/5318028/96884104-d285ef00-1489-11eb-9dcf-c7ba4f5c87fc.png)

Again: "not found" node UID and node being deleted are different
![image](https://user-images.githubusercontent.com/5318028/96884221-f2b5ae00-1489-11eb-8faa-5c42ca2c39ef.png)

**Comment by dvonthenen** [comment]
I missed the link to the first stale issue and was thinking this was a new issue. The UnregisterNode should remove the VM objects based on UUID from cache... will try to simulate the delete and recreate a VM to reproduce.

**Comment by AntonSmolkov** [comment]
An updates?☹️

**Comment by dvonthenen** [comment]
Sorry I was on PTO for the better half of Dec. Just getting caught up with the backlog of stuff while returning. Will take some time getting to this.
