### ISSUE TITLE
list nodes give <none> on internalIP

### ISSUE THREAD

**Issue by lynic** [kubernetes/cloud-provider-vsphere#398]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug
> /kind feature

**What happened**:
kubectl list nodes
Some nodes display <none> on internalIP and ExternalIP.

**What you expected to happen**:
These nodes should display their IP on interlanIP and externalIP.

**How to reproduce it (as minimally and precisely as possible)**:
Stop vmware-tools inside node for a period of time.
kubectl list nodes, this node will display <none> on internalIP
Even after restart vmware-tools and IP address get reported displayed on vc.
kuebctl list nodes still display <none> on internalIP

**Anything else we need to know?**:
k8s v1.18.6+vmware.1

**Environment**:
- vsphere-cloud-controller-manager version: registry.tkg.vmware.run/ccm/manager:v1.1.0_vmware.3
- OS (e.g. from /etc/os-release): photon 3.0
- Kernel (e.g. `uname -a`): 4.19.132-1
- Install tools:
- Others:

**Comment by dvonthenen** [comment]
Hi @lynic 

Did you happen to give this a try?
https://github.com/kubernetes/cloud-provider-vsphere/blob/master/docs/book/known_issues.md

**Comment by dvonthenen** [comment]
What version of CPI are you using? If you restart the CPI, does the correct correct IP show up?

**Comment by lynic** [comment]
> What version of CPI are you using? If you restart the CPI, does the correct IP show up?

Version shows in description, yes, we apply the changes to vmware-tools. The problem is if vmware-tools didn’t report the ip to vc during a period of time, the internalIP will become none, even after the vmware-tools back to normal, the internalIP will not come back until we restart cloud-controller-manager.

Did u fix it in latest code?
