### ISSUE TITLE
Investigate using Bazel as build/test tool

### ISSUE THREAD

**Issue by frapposelli** [kubernetes/cloud-provider-vsphere#40]
[Bazel](https://bazel.io) is used by Kubernetes as build tool, would be nice to understand pro/cons of adopting it vs. using `make`.

The outcome of this issue should be a document or a comment on this issue detailing pro/cons and potentially reaching a consensus on the path forward.

/kind feature

**Comment by stantonxu** [comment]
Some good reference from official website,
https://bazel.build/faq.html#what-is-special-about-bazel
https://bazel.build/faq.html#what-is-bazel-best-at
https://bazel.build/faq.html#what-should-i-not-use-bazel-for
