### ISSUE TITLE
Pod route exchange with NSX-T

### ISSUE THREAD

**Issue by dantingl** [kubernetes/cloud-provider-vsphere#404]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind feature

**What happened**:
When adding node to NSX-T networking, container data plane will be associated with NSX-T encapsulation protocols.

**What you expected to happen**:
Exchange routes with NSX-T tier 1 router, so that:
  - a non-encapsulation transit mode can be used when hosts are not layer-2 adjacent and must have traffic forwarded by a router between them, and/or
  - pods IP addresses are routable and accessible externally from the cluster.

**How to reproduce it (as minimally and precisely as possible)**:
With NSX-T connection info and Tier1 router UUID config, vsphere cloud provider will add static route in T1 router when there is a node added event, and will delete related static route for a node deleted event.

**Anything else we need to know?**:
N/A

**Environment**:
- vsphere-cloud-controller-manager version:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by andrewsykim** [comment]
Given we already support NSX-T load balancers and all the configuration handling exists, I would be okay to support this. @dantingl are you able to work on the PR for this?

**Comment by dantingl** [comment]
Sure, I can work on this.

**Comment by andrewsykim** [comment]
Thanks!

/assign @dantingl

**Comment by andrewsykim** [comment]
@MartinWeindel any thoughts on this?
