### ISSUE TITLE
cpi cannot find node  - Unable to find VM by UUID

### ISSUE THREAD

**Issue by dealboy** [kubernetes/cloud-provider-vsphere#406]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
CPI cannot find the VMs in vsphere. 
**What you expected to happen**:
CPI to query and find all VMs, and assign a ProviderID 

**How to reproduce it (as minimally and precisely as possible)**:
it happens every time in my reference setup and configuration. 
I presume that is either a path issue (our VMs are not in default folders), case sensitivity issue or something similar.

**Anything else we need to know?**:
VMs are not in default folders.
Datacenter has multiple clusters.

I followed the CPI part of configuration from https://github.com/kubernetes/cloud-provider-vsphere/blob/master/docs/book/tutorials/kubernetes-on-vsphere-with-kubeadm.md 

on an existing RKE cluster (v1.18.3)

**Environment**:
- vsphere-cloud-controller-manager version: v1.2.1
- OS (e.g. from /etc/os-release): RHEL7.9
- Kernel (e.g. `uname -a`):    3.10.0-1160.2.2.el7.x86_64
- Others:  RKE cluster (v1.18.3)

Sample log extract

`
116 17:16:42.377487       1 cloud.go:102] Starting the API Server
I1116 17:16:42.377552       1 clientconn.go:105] parsed scheme: ""
I1116 17:16:42.377575       1 clientconn.go:105] scheme "" not registered, fallback to default scheme
I1116 17:16:42.377621       1 passthrough.go:48] ccResolverWrapper: sending update to cc: {[{:43001 0  <nil>}] <nil>}
I1116 17:16:42.377642       1 clientconn.go:578] ClientConn switching balancer to "pick_first"
I1116 17:16:42.377795       1 balancer_conn_wrappers.go:127] pickfirstBalancer: HandleSubConnStateChange: 0xc00045f3c0, CONNECTING
I1116 17:16:42.380023       1 balancer_conn_wrappers.go:127] pickfirstBalancer: HandleSubConnStateChange: 0xc00045f3c0, READY
I1116 17:16:42.381505       1 search.go:76] WhichVCandDCByNodeID nodeID: e2292342-0293-1ad5-64bf-83641074bdcf
I1116 17:16:42.382676       1 server.go:143] APIVersion: 0.0.1
I1116 17:16:42.382705       1 controllermanager.go:234] Starting "cloud-node"
I1116 17:16:42.384597       1 node_controller.go:71] Sending events to api server.
I1116 17:16:42.384677       1 controllermanager.go:244] Started "cloud-node"
I1116 17:16:42.384690       1 controllermanager.go:234] Starting "cloud-node-lifecycle"
I1116 17:16:42.386168       1 node_lifecycle_controller.go:77] Sending events to api server
I1116 17:16:42.386254       1 controllermanager.go:244] Started "cloud-node-lifecycle"
I1116 17:16:42.386267       1 controllermanager.go:234] Starting "service"
W1116 17:16:42.388455       1 cloud.go:129] The vSphere cloud provider does not support load balancers
E1116 17:16:42.388485       1 core.go:80] Failed to start service controller: the cloud provider does not support external load balancers
W1116 17:16:42.388809       1 controllermanager.go:241] Skipping "service"
I1116 17:16:42.388821       1 controllermanager.go:234] Starting "route"
I1116 17:16:42.388828       1 core.go:91] Will not configure cloud provider routes for allocate-node-cidrs: false, configure-cloud-routes: true.
W1116 17:16:42.388849       1 controllermanager.go:241] Skipping "route"
I1116 17:16:42.409970       1 search.go:76] WhichVCandDCByNodeID nodeID: dev-dev-0348
E1116 17:16:47.427581       1 connection.go:63] Failed to create govmomi client. err: ServerFaultCode: Cannot complete login due to an incorrect user name or password.
I1116 17:16:47.427617       1 connectionmanager.go:152] Invalid credentials. Fetching credentials from secrets. vcServer=192.168.10.10 credentialHolder=Global
E1116 17:16:47.533014       1 datacenter.go:124] Unable to find VM by UUID. VM UUID: e2292342-0293-1ad5-64bf-83641074bdcf
E1116 17:16:47.533036       1 search.go:181] Error while looking for vm=e2292342-0293-1ad5-64bf-83641074bdcf(byUUID) in vc=192.168.10.10 and datacenter=NHQ_DEV: No VM found
I1116 17:16:47.533055       1 search.go:186] Did not find node e2292342-0293-1ad5-64bf-83641074bdcf in vc=192.168.10.10 and datacenter=NHQ_DEV
E1116 17:16:47.533086       1 nodemanager.go:144] WhichVCandDCByNodeID failed using normally formatted UUID. Err: No VM found
I1116 17:16:47.533111       1 search.go:76] WhichVCandDCByNodeID nodeID: 422329e2-9302-d51a-64bf-83641074bdcf
E1116 17:16:47.535879       1 datacenter.go:107] Unable to find VM by DNS Name. VM DNS Name: dev-dev-0348
E1116 17:16:47.535909       1 search.go:181] Error while looking for vm=dev-dev-0348(byName) in vc=192.168.10.10 and datacenter=NHQ_DEV: No VM found
I1116 17:16:47.535921       1 search.go:186] Did not find node dev-dev-0348 in vc=192.168.10.10 and datacenter=NHQ_DEV
I1116 17:16:47.535937       1 search.go:76] WhichVCandDCByNodeID nodeID: dev-dev-0348
E1116 17:16:47.553402       1 datacenter.go:90] Unable to find VM by IP. VM IP: dev-dev-0348

`

Any ideas?

**Comment by alex1989hu** [comment]
Did you install `open-vm-tools` onto nodes?

**Comment by dealboy** [comment]
@alex1989hu yes, open-vm-tools  v11.0.2

**Comment by alex1989hu** [comment]
When we started to use CPI, we faced that it is mandatory to have it installed - this is why I asked it. Anyway, I found the root cause in your log message:

> Failed to create govmomi client. err: ServerFaultCode: Cannot complete login due to an incorrect user name or password.
I1116 17:16:47.427617 1 connectionmanager.go:152] Invalid credentials. Fetching credentials from secrets.

**Comment by dealboy** [comment]
I have also spotted that, but I am sure that the credentials in the secret are correct.
They are stringData (so I can verify them easily )

**Comment by dvonthenen** [comment]
It is because the CPI first tries to use the creds in the secret before falling back to the config. Also make sure the correct secret is being referenced in the correct namespace.

**Comment by dealboy** [comment]
I have no credentials defined in the vshpere.conf, only the secretName/secretNamespace combination.

and verified that  I get back the secret from the kube-system namespace

```
global:
  port: 443
  insecureFlag: true
  secretName: cpi-global-secret
  secretNamespace: kube-system

vcenter:
  tenant-rancher:
    server: 192.168.10.10
    datacenters:
      - NHQ_DEV
```

**Comment by dealboy** [comment]
One interesting thing is that using only the username in the secret, vsphere-cloud-controller-manager gives me more errors.
Changing it to username@dev.int , it give only the error line shown above. 

(On vcenter I can login either with `username@dev.int` or with plain `username` )

**Comment by dvonthenen** [comment]
seems like the secret data is not correct then... I'm willing to bet it's your username. Try taking the values and logging into vsphere with them

**Comment by dealboy** [comment]
Hi @dvonthenen , I did that, and the accounts can be used to logging into vsphere!

My VMs are under one cluster in vphere and in a 3 level folder structure, does this matter?
is that VM lookup capable of searching in a folder  tree? or in the cluster?

**Comment by dealboy** [comment]
and my kubelet reports `csi.vsphere.vmware.com-reg.sock: connect: connection refused`

does that info help?

```
I1117 12:59:13.373931    1964 reconciler.go:156] operationExecutor.RegisterPlugin started for plugin at "/var/lib/kubelet/plugins_registry/csi.vsphere.vmware.com-reg.sock" (plugin details: &{/var/lib/kubelet/plugins_registry/csi.vsphere.vmware.com-reg.sock 2020-11-17 11:21:08.072347197 +0000 UTC m=+9.202032648 <nil> }) 
I1117 12:59:13.373999    1964 operation_generator.go:181] parsed scheme: ""
I1117 12:59:13.374012    1964 operation_generator.go:181] scheme "" not registered, fallback to default scheme
I1117 12:59:13.374038    1964 passthrough.go:48] ccResolverWrapper: sending update to cc: {[{/var/lib/kubelet/plugins_registry/csi.vsphere.vmware.com-reg.sock  <nil> 0 <nil>}] <nil> <nil>}
I1117 12:59:13.374061    1964 clientconn.go:933] ClientConn switching balancer to "pick_first"
W1117 12:59:13.374210    1964 clientconn.go:1208] grpc: addrConn.createTransport failed to connect to {/var/lib/kubelet/plugins_registry/csi.vsphere.vmware.com-reg.sock  <nil> 0 <nil>}. Err :connection error: desc = "transport: Error while dialing dial unix /var/lib/kubelet/plugins_registry/csi.vsphere.vmware.com-reg.sock: connect: connection refused". Reconnecting...
I1117 12:59:13.374251    1964 balancer_conn_wrappers.go:78] pickfirstBalancer: HandleSubConnStateChange: 0xc00130fcc0, {CONNECTING <nil>}
I1117 12:59:13.374292    1964 balancer_conn_wrappers.go:78] pickfirstBalancer: HandleSubConnStateChange: 0xc00130fcc0, {TRANSIENT_FAILURE connection error: desc = "transport: Error while dialing dial unix /var/lib/kubelet/plugins_registry/csi.vsphere.vmware.com-reg.sock: connect: connection refused"}
I1117 12:59:14.374457    1964 balancer_conn_wrappers.go:78] pickfirstBalancer: HandleSubConnStateChange: 0xc00130fcc0, {CONNECTING <nil>}
W1117 12:59:14.374499    1964 clientconn.go:1208] grpc: addrConn.createTransport failed to connect to {/var/lib/kubelet/plugins_registry/csi.vsphere.vmware.com-reg.sock  <nil> 0 <nil>}. Err :connection error: desc = "transport: Error while dialing dial unix /var/lib/kubelet/plugins_registry/csi.vsphere.vmware.com-reg.sock: connect: connection refused". Reconnecting...
I1117 12:59:14.374544    1964 balancer_conn_wrappers.go:78] pickfirstBalancer: HandleSubConnStateChange: 0xc00130fcc0, {TRANSIENT_FAILURE connection error: desc = "transport: Error while dialing dial unix /var/lib/kubelet/plugins_registry/csi.vsphere.vmware.com-reg.sock: connect: connection refused"}
I1117 12:59:15.065295    1964 logs.go:304] Finish parsing log file "/opt/docker/containers/7e3e55948a043ac7280ea11f2c7b4ec5bd36ca1305d58ff16e1e38457a6a487f/7e3e55948a043ac7280ea11f2c7b4ec5bd36ca1305d58ff16e1e38457a6a487f-json.log"
W1117 12:59:16.148037    1964 clientconn.go:1208] grpc: addrConn.createTransport failed to connect to {/var/lib/kubelet/plugins_registry/csi.vsphere.vmware.com-reg.sock  <nil> 0 <nil>}. Err :connection error: desc = "transport: Error while dialing dial unix /var/lib/kubelet/plugins_registry/csi.vsphere.vmware.com-reg.sock: connect: connection refused". Reconnecting...
I1117 12:59:16.148093    1964 balancer_conn_wrappers.go:78] pickfirstBalancer: HandleSubConnStateChange: 0xc00130fcc0, {CONNECTING <nil>}
I1117 12:59:16.148126    1964 balancer_conn_wrappers.go:78] pickfirstBalancer: HandleSubConnStateChange: 0xc00130fcc0, {TRANSIENT_FAILURE connection error: desc = "transport: Error while dialing dial unix /var/lib/kubelet/plugins_registry/csi.vsphere.vmware.com-reg.sock: connect: connection refused"}
W1117 12:59:18.887421    1964 clientconn.go:1208] grpc: addrConn.createTransport failed to connect to {/var/lib/kubelet/plugins_registry/csi.vsphere.vmware.com-reg.sock  <nil> 0 <nil>}. Err :connection error: desc = "transport: Error while dialing dial unix /var/lib/kubelet/plugins_registry/csi.vsphere.vmware.com-reg.sock: connect: connection refused". Reconnecting...
I1117 12:59:18.887419    1964 balancer_conn_wrappers.go:78] pickfirstBalancer: HandleSubConnStateChange: 0xc00130fcc0, {CONNECTING <nil>}
I1117 12:59:18.887506    1964 balancer_conn_wrappers.go:78] pickfirstBalancer: HandleSubConnStateChange: 0xc00130fcc0, {TRANSIENT_FAILURE connection error: desc = "transport: Error while dialing dial unix /var/lib/kubelet/plugins_registry/csi.vsphere.vmware.com-reg.sock: connect: connection refused"}
I1117 12:59:20.064483    1964 logs.go:304] Finish parsing log file "/opt/docker/containers/7e3e55948a043ac7280ea11f2c7b4ec5bd36ca1305d58ff16e1e38457a6a487f/7e3e55948a043ac7280ea11f2c7b4ec5bd36ca1305d58ff16e1e38457a6a487f-json.log"
I1117 12:59:22.796868    1964 balancer_conn_wrappers.go:78] pickfirstBalancer: HandleSubConnStateChange: 0xc00130fcc0, {CONNECTING <nil>}
W1117 12:59:22.796876    1964 clientconn.go:1208] grpc: addrConn.createTransport failed to connect to {/var/lib/kubelet/plugins_registry/csi.vsphere.vmware.com-reg.sock  <nil> 0 <nil>}. Err :connection error: desc = "transport: Error while dialing dial unix /var/lib/kubelet/plugins_registry/csi.vsphere.vmware.com-reg.sock: connect: connection refused". Reconnecting...
I1117 12:59:22.796945    1964 balancer_conn_wrappers.go:78] pickfirstBalancer: HandleSubConnStateChange: 0xc00130fcc0, {TRANSIENT_FAILURE connection error: desc = "transport: Error while dialing dial unix /var/lib/kubelet/plugins_registry/csi.vsphere.vmware.com-reg.sock: connect: connection refused"}
E1117 12:59:23.374163    1964 goroutinemap.go:150] Operation for "/var/lib/kubelet/plugins_registry/csi.vsphere.vmware.com-reg.sock" failed. No retries permitted until 2020-11-17 13:01:25.374126582 +0000 UTC m=+6026.503812075 (durationBeforeRetry 2m2s). Error: "RegisterPlugin error -- dial failed at socket /var/lib/kubelet/plugins_registry/csi.vsphere.vmware.com-reg.sock, err: failed to dial socket /var/lib/kubelet/plugins_registry/csi.vsphere.vmware.com-reg.sock, err: context deadline exceeded"
```

**Comment by dvonthenen** [comment]
> Hi @dvonthenen , I did that, and the account username/passwd can be used to logging into vsphere!
> 
> My VMs are under one cluster in vphere and in a 3 level folder structure, does this matter?
> is that VM lookup capable of searching in a folder tree? or in the cluster?

this shouldn't matter as long as you are running the 1.2.X or later release

**Comment by dvonthenen** [comment]
> and my kubelet reports `csi.vsphere.vmware.com-reg.sock: connect: connection refused`
> 
> does that info help?
> 
> ```
> I1117 12:59:13.373931    1964 reconciler.go:156] operationExecutor.RegisterPlugin started for plugin at "/var/lib/kubelet/plugins_registry/csi.vsphere.vmware.com-reg.sock" (plugin details: &{/var/lib/kubelet/plugins_registry/csi.vsphere.vmware.com-reg.sock 2020-11-17 11:21:08.072347197 +0000 UTC m=+9.202032648 <nil> }) 
> I1117 12:59:13.373999    1964 operation_generator.go:181] parsed scheme: ""
> I1117 12:59:13.374012    1964 operation_generator.go:181] scheme "" not registered, fallback to default scheme
> I1117 12:59:13.374038    1964 passthrough.go:48] ccResolverWrapper: sending update to cc: {[{/var/lib/kubelet/plugins_registry/csi.vsphere.vmware.com-reg.sock  <nil> 0 <nil>}] <nil> <nil>}
> I1117 12:59:13.374061    1964 clientconn.go:933] ClientConn switching balancer to "pick_first"
> W1117 12:59:13.374210    1964 clientconn.go:1208] grpc: addrConn.createTransport failed to connect to {/var/lib/kubelet/plugins_registry/csi.vsphere.vmware.com-reg.sock  <nil> 0 <nil>}. Err :connection error: desc = "transport: Error while dialing dial unix /var/lib/kubelet/plugins_registry/csi.vsphere.vmware.com-reg.sock: connect: connection refused". Reconnecting...
> I1117 12:59:13.374251    1964 balancer_conn_wrappers.go:78] pickfirstBalancer: HandleSubConnStateChange: 0xc00130fcc0, {CONNECTING <nil>}
> I1117 12:59:13.374292    1964 balancer_conn_wrappers.go:78] pickfirstBalancer: HandleSubConnStateChange: 0xc00130fcc0, {TRANSIENT_FAILURE connection error: desc = "transport: Error while dialing dial unix /var/lib/kubelet/plugins_registry/csi.vsphere.vmware.com-reg.sock: connect: connection refused"}
> I1117 12:59:14.374457    1964 balancer_conn_wrappers.go:78] pickfirstBalancer: HandleSubConnStateChange: 0xc00130fcc0, {CONNECTING <nil>}
> W1117 12:59:14.374499    1964 clientconn.go:1208] grpc: addrConn.createTransport failed to connect to {/var/lib/kubelet/plugins_registry/csi.vsphere.vmware.com-reg.sock  <nil> 0 <nil>}. Err :connection error: desc = "transport: Error while dialing dial unix /var/lib/kubelet/plugins_registry/csi.vsphere.vmware.com-reg.sock: connect: connection refused". Reconnecting...
> I1117 12:59:14.374544    1964 balancer_conn_wrappers.go:78] pickfirstBalancer: HandleSubConnStateChange: 0xc00130fcc0, {TRANSIENT_FAILURE connection error: desc = "transport: Error while dialing dial unix /var/lib/kubelet/plugins_registry/csi.vsphere.vmware.com-reg.sock: connect: connection refused"}
> I1117 12:59:15.065295    1964 logs.go:304] Finish parsing log file "/opt/docker/containers/7e3e55948a043ac7280ea11f2c7b4ec5bd36ca1305d58ff16e1e38457a6a487f/7e3e55948a043ac7280ea11f2c7b4ec5bd36ca1305d58ff16e1e38457a6a487f-json.log"
> W1117 12:59:16.148037    1964 clientconn.go:1208] grpc: addrConn.createTransport failed to connect to {/var/lib/kubelet/plugins_registry/csi.vsphere.vmware.com-reg.sock  <nil> 0 <nil>}. Err :connection error: desc = "transport: Error while dialing dial unix /var/lib/kubelet/plugins_registry/csi.vsphere.vmware.com-reg.sock: connect: connection refused". Reconnecting...
> I1117 12:59:16.148093    1964 balancer_conn_wrappers.go:78] pickfirstBalancer: HandleSubConnStateChange: 0xc00130fcc0, {CONNECTING <nil>}
> I1117 12:59:16.148126    1964 balancer_conn_wrappers.go:78] pickfirstBalancer: HandleSubConnStateChange: 0xc00130fcc0, {TRANSIENT_FAILURE connection error: desc = "transport: Error while dialing dial unix /var/lib/kubelet/plugins_registry/csi.vsphere.vmware.com-reg.sock: connect: connection refused"}
> W1117 12:59:18.887421    1964 clientconn.go:1208] grpc: addrConn.createTransport failed to connect to {/var/lib/kubelet/plugins_registry/csi.vsphere.vmware.com-reg.sock  <nil> 0 <nil>}. Err :connection error: desc = "transport: Error while dialing dial unix /var/lib/kubelet/plugins_registry/csi.vsphere.vmware.com-reg.sock: connect: connection refused". Reconnecting...
> I1117 12:59:18.887419    1964 balancer_conn_wrappers.go:78] pickfirstBalancer: HandleSubConnStateChange: 0xc00130fcc0, {CONNECTING <nil>}
> I1117 12:59:18.887506    1964 balancer_conn_wrappers.go:78] pickfirstBalancer: HandleSubConnStateChange: 0xc00130fcc0, {TRANSIENT_FAILURE connection error: desc = "transport: Error while dialing dial unix /var/lib/kubelet/plugins_registry/csi.vsphere.vmware.com-reg.sock: connect: connection refused"}
> I1117 12:59:20.064483    1964 logs.go:304] Finish parsing log file "/opt/docker/containers/7e3e55948a043ac7280ea11f2c7b4ec5bd36ca1305d58ff16e1e38457a6a487f/7e3e55948a043ac7280ea11f2c7b4ec5bd36ca1305d58ff16e1e38457a6a487f-json.log"
> I1117 12:59:22.796868    1964 balancer_conn_wrappers.go:78] pickfirstBalancer: HandleSubConnStateChange: 0xc00130fcc0, {CONNECTING <nil>}
> W1117 12:59:22.796876    1964 clientconn.go:1208] grpc: addrConn.createTransport failed to connect to {/var/lib/kubelet/plugins_registry/csi.vsphere.vmware.com-reg.sock  <nil> 0 <nil>}. Err :connection error: desc = "transport: Error while dialing dial unix /var/lib/kubelet/plugins_registry/csi.vsphere.vmware.com-reg.sock: connect: connection refused". Reconnecting...
> I1117 12:59:22.796945    1964 balancer_conn_wrappers.go:78] pickfirstBalancer: HandleSubConnStateChange: 0xc00130fcc0, {TRANSIENT_FAILURE connection error: desc = "transport: Error while dialing dial unix /var/lib/kubelet/plugins_registry/csi.vsphere.vmware.com-reg.sock: connect: connection refused"}
> E1117 12:59:23.374163    1964 goroutinemap.go:150] Operation for "/var/lib/kubelet/plugins_registry/csi.vsphere.vmware.com-reg.sock" failed. No retries permitted until 2020-11-17 13:01:25.374126582 +0000 UTC m=+6026.503812075 (durationBeforeRetry 2m2s). Error: "RegisterPlugin error -- dial failed at socket /var/lib/kubelet/plugins_registry/csi.vsphere.vmware.com-reg.sock, err: failed to dial socket /var/lib/kubelet/plugins_registry/csi.vsphere.vmware.com-reg.sock, err: context deadline exceeded"
> ```

It seems like you have a problem with the CSI driver. Before running CSI for vSphere, the node lookup in CPI should be addressed first.

**Comment by dvonthenen** [comment]
Can you log into the vSphere MOB, find the VM and grab a screenshot of 2 things:
1) grab a screenshot of the `summary.config` field/struct for VM `dev-dev-0348`
2) grab a screenshot of the `guest` field/struct (same VM)

**Comment by dealboy** [comment]
> Can you log into the vSphere MOB, find the VM and grab a screenshot of 2 things:
> 
> 1. grab a screenshot of the `summary.config` field/struct for VM `dev-dev-0348`
> 2. grab a screenshot of the `guest` field/struct (same VM)

![image](https://user-images.githubusercontent.com/1675899/99514062-9c099a00-298b-11eb-8593-735ccc988436.png)

![summary config](https://user-images.githubusercontent.com/1675899/99514561-2f42cf80-298c-11eb-86d4-841f7852c571.PNG)

**Comment by dealboy** [comment]
Hi @dvonthenen  do you see anything strange on the above screenshots?

Is there something else I could try?

**Comment by dvonthenen** [comment]
I think I see the problem, the hostname should be the FQDN. If you update the hostname to `dev-dev-0348.development.int`, that should fix it.

**Comment by dealboy** [comment]
thanks a lot @dvonthenen !  issue is fixed

**Comment by dvonthenen** [comment]
Awesome!
