### ISSUE TITLE
PV was in Released status but the persistentVolumeReclaimPolicy with Delete in storageclass

### ISSUE THREAD

**Issue by zhoudayongdennis** [kubernetes/cloud-provider-vsphere#409]
vSphere Client version 6.7.0.40000 with CNS volume usage.

here was the detail info about Released PV, and detail info for an example Release PV.

the number was in increasing trend.

[root@nc0750node02 ~]# kubectl get pv | grep vsphere | grep Released |wc -l
46
[root@nc0750node02 ~]# kubectl get pv | grep vsphere | grep Released
pvc-05ab5701-834e-4181-8401-d02ce444f3f6   4Gi        RWO            Delete           Released      nokia-imshss/datadir-buphssnew5-etcd-0              vsphere                           33h
pvc-11c91ba6-ab5f-4781-8bc8-8bb9ec69e1a4   4Gi        RWO            Delete           Released      nokia-imshss/datadir-buphssnew5-etcd-2              vsphere                           31h
pvc-186c10eb-ad8d-4bfa-b098-ca41b133157e   4Gi        RWO            Delete           Released      nokia-imshss/datadir-buphssnew3-etcd-0              vsphere                           5d18h
pvc-18effeda-6a35-4379-8c53-1c61b031c457   4Gi        RWO            Delete           Released      nokia-imshss/datadir-buphssnew5-etcd-0              vsphere                           10h
pvc-21d4f508-2516-4daa-872f-98a0a00e43cf   4Gi        RWO            Delete           Released      nokia-imshss/datadir-buphssnew3-etcd-2              vsphere                           5d15h
pvc-2a7f275f-c5b1-4064-a100-2c137123bae0   4Gi        RWO            Delete           Released      nokia-imshss/datadir-buphssnew5-etcd-0              vsphere                           32h
pvc-2f46368c-885b-4443-9ad7-41fe62e1622e   4Gi        RWO            Delete           Released      nokia-imshss/datadir-buphssnew5-etcd-2              vsphere                           32h
pvc-2f7e9d66-65cc-4368-a2a7-28cfb570257f   4Gi        RWO            Delete           Released      nokia-imshss/datadir-buphssnew3-etcd-2              vsphere                           8d
pvc-37b04446-ae6f-49e2-b579-52d9d9278c3e   4Gi        RWO            Delete           Released      nokia-imshss/datadir-buphssnew3-etcd-0              vsphere                           11d
pvc-4505777f-62a0-47b5-9e29-740189b31db2   4Gi        RWO            Delete           Released      nokia-imshss/datadir-buphssnew3-etcd-2              vsphere                           7d8h
pvc-4ad78c3c-42d5-41cc-91fc-b2d8b849f4a0   4Gi        RWO            Delete           Released      nokia-imshss/datadir-buphssnew3-etcd-0              vsphere                           5d15h
pvc-4ae47159-9747-42a0-9ef3-8c3eb675f681   4Gi        RWO            Delete           Released      nokia-imshss/datadir-buphssnew5-etcd-1              vsphere                           15h
pvc-50fc8bc4-adc1-4327-9938-a14bab9a3e0f   4Gi        RWO            Delete           Released      nokia-imshss/datadir-buphssnew3-etcd-1              vsphere                           4d17h
pvc-52a4c61c-4e13-43d1-aae1-1a0e87e35a3f   4Gi        RWO            Delete           Released      nokia-imshss/datadir-buphssnew5-etcd-1              vsphere                           32h
pvc-53852935-bd21-412f-8d73-ca8730372423   4Gi        RWO            Delete           Released      nokia-imshss/datadir-buphssnew3-etcd-2              vsphere                           8d
pvc-556748ff-3f84-4d6a-b591-e4b4b0f6af3f   4Gi        RWO            Delete           Released      nokia-imshss/datadir-buphssnew3-etcd-1              vsphere                           5d23h
pvc-6950b30e-7852-475e-aa28-8546d12a9625   4Gi        RWO            Delete           Released      nokia-imshss/datadir-buphssnew5-etcd-2              vsphere                           22h
pvc-69b6ae1e-1fcc-4ea9-99c4-22ad0d3f2190   4Gi        RWO            Delete           Released      nokia-imshss/datadir-buphssnew3-etcd-2              vsphere                           4d17h
pvc-6dde5f0c-c4ed-402a-8476-bbd34854a68a   4Gi        RWO            Delete           Released      nokia-imshss/datadir-buphssnew3-etcd-0              vsphere                           8d
pvc-6ef9112d-794d-4121-91f8-c3649bbd1719   4Gi        RWO            Delete           Released      nokia-imshss/datadir-buphssnew5-etcd-0              vsphere                           22h
pvc-838d02c3-7cd2-4b2c-9ac5-f8ebb2025f21   4Gi        RWO            Delete           Released      nokia-imshss/datadir-buphssnew5-etcd-0              vsphere                           15h
pvc-91a90cb3-8324-4be8-b814-1da7ee1d8e55   4Gi        RWO            Delete           Released      nokia-imshss/datadir-buphssnew5-etcd-1              vsphere                           31h
pvc-92128868-6f8e-4497-b414-0ae3ea36bfc1   4Gi        RWO            Delete           Released      nokia-imshss/datadir-buphssnew5-etcd-2              vsphere                           33h
pvc-9b4e7559-6a16-4f9b-aebf-c152344c90b6   4Gi        RWO            Delete           Released      nokia-imshss/datadir-buphssnew3-etcd-2              vsphere                           11d
pvc-9c61f8b7-32cc-435d-9af6-917a9cac7260   4Gi        RWO            Delete           Released      nokia-imshss/datadir-buphssnew3-etcd-0              vsphere                           4d17h
pvc-9d38abf0-27fe-435a-a051-25343138c7a4   4Gi        RWO            Delete           Released      nokia-imshss/datadir-buphssnew5-etcd-1              vsphere                           33h
pvc-9e813abb-3e19-49e2-9c81-568499f21e19   4Gi        RWO            Delete           Released      nokia-imshss/datadir-buphssnew3-etcd-1              vsphere                           7d8h
pvc-9fb27e62-32f7-479f-bac6-87038a4e2f21   4Gi        RWO            Delete           Released      nokia-imshss/datadir-buphssnew3-etcd-2              vsphere                           5d13h
pvc-a1054ae4-f92a-4303-896a-a9ef985a3062   4Gi        RWO            Delete           Released      nokia-imshss/datadir-buphssnew3-etcd-1              vsphere                           5d18h
pvc-abb08aa1-7390-4e03-a206-70d6db5562f9   4Gi        RWO            Delete           Released      nokia-imshss/datadir-buphssnew3-etcd-0              vsphere                           5d23h
pvc-b51d71de-adc8-4fe2-84a6-226ea95f3d6b   4Gi        RWO            Delete           Released      nokia-imshss/datadir-buphssnew5-etcd-1              vsphere                           10h
pvc-bb6938b9-9f89-41a2-a0fd-2a94ca2236ba   4Gi        RWO            Delete           Released      nokia-imshss/datadir-buphssnew3-etcd-1              vsphere                           11d
pvc-bc0c0cd0-34fa-40e7-932d-740e5a4587a1   4Gi        RWO            Delete           Released      nokia-imshss/datadir-buphssnew3-etcd-1              vsphere                           5d15h
pvc-c1c8c8a3-7337-4cfa-9bdd-15d8e3901897   4Gi        RWO            Delete           Released      nokia-imshss/datadir-buphssnew3-etcd-0              vsphere                           5d13h
pvc-c5124186-836e-4891-8fb6-a9c1b582c4f2   4Gi        RWO            Delete           Released      nokia-imshss/datadir-buphssnew3-etcd-2              vsphere                           5d23h
pvc-c9cf575d-e5fa-40ed-81a4-e005b5198025   4Gi        RWO            Delete           Released      nokia-imshss/datadir-buphssnew3-etcd-0              vsphere                           3d10h
pvc-c9f7a834-8a16-40a8-8dad-40d883e0e77f   4Gi        RWO            Delete           Released      nokia-imshss/datadir-buphssnew5-etcd-1              vsphere                           22h
pvc-cd113eca-5d55-4bdd-b5f5-d2991ede0c3a   4Gi        RWO            Delete           Released      nokia-imshss/datadir-buphssnew3-etcd-1              vsphere                           5d13h
pvc-d1af84c8-2fbe-44a2-86c0-83970e452b00   4Gi        RWO            Delete           Released      nokia-imshss/datadir-buphssnew5-etcd-2              vsphere                           15h
pvc-e1af7030-3483-43e2-aae8-878a96b6e0a2   4Gi        RWO            Delete           Released      nokia-imshss/datadir-buphssnew3-etcd-1              vsphere                           8d
pvc-e3371a12-fcde-4f35-b2dc-3f4b71cb8f42   4Gi        RWO            Delete           Released      nokia-imshss/datadir-buphssnew5-etcd-0              vsphere                           31h
pvc-e5e2cf9e-09f5-4c6d-88bb-63e6f3edb7fd   4Gi        RWO            Delete           Released      nokia-imshss/datadir-buphssnew3-etcd-2              vsphere                           3d10h
pvc-eae9b70c-96bd-43fa-8556-2450beeb8465   4Gi        RWO            Delete           Released      nokia-imshss/datadir-buphssnew5-etcd-2              vsphere                           10h
pvc-ebeb3cc6-44a3-4448-8c35-c9a07e64fce5   4Gi        RWO            Delete           Released      nokia-imshss/datadir-buphssnew3-etcd-2              vsphere                           5d18h
pvc-ec660a17-7dab-4ba2-9668-267defb072b3   4Gi        RWO            Delete           Released      nokia-imshss/datadir-buphssnew3-etcd-1              vsphere                           3d10h
pvc-f1acbf2c-5025-47be-aa30-83ddeb6f4ab6   4Gi        RWO            Delete           Released      nokia-imshss/datadir-buphssnew3-etcd-0              vsphere                           8d
[root@nc0750node02 ~]#

[root@nc0750node02 ~]# kubectl get pv pvc-f1acbf2c-5025-47be-aa30-83ddeb6f4ab6 -oyaml
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: csi.vsphere.vmware.com
  creationTimestamp: "2020-11-10T18:37:43Z"
  finalizers:
  - kubernetes.io/pv-protection
  - external-attacher/csi-vsphere-vmware-com
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:pv.kubernetes.io/provisioned-by: {}
      f:spec:
        f:accessModes: {}
        f:capacity:
          .: {}
          f:storage: {}
        f:claimRef:
          .: {}
          f:apiVersion: {}
          f:kind: {}
          f:name: {}
          f:namespace: {}
          f:resourceVersion: {}
          f:uid: {}
        f:csi:
          .: {}
          f:driver: {}
          f:fsType: {}
          f:volumeAttributes:
            .: {}
            f:storage.kubernetes.io/csiProvisionerIdentity: {}
            f:type: {}
          f:volumeHandle: {}
        f:persistentVolumeReclaimPolicy: {}
        f:storageClassName: {}
        f:volumeMode: {}
    manager: csi-provisioner
    operation: Update
    time: "2020-11-10T18:37:43Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:finalizers:
          v:"external-attacher/csi-vsphere-vmware-com": {}
    manager: csi-attacher
    operation: Update
    time: "2020-11-10T18:37:47Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:phase: {}
    manager: kube-controller-manager
    operation: Update
    time: "2020-11-11T16:22:06Z"
  name: pvc-f1acbf2c-5025-47be-aa30-83ddeb6f4ab6
  resourceVersion: "12672248"
  selfLink: /api/v1/persistentvolumes/pvc-f1acbf2c-5025-47be-aa30-83ddeb6f4ab6
  uid: 9b446dfa-b6a8-4db8-9cc1-3f328ede80c6
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 4Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: datadir-buphssnew3-etcd-0
    namespace: nokia-imshss
    resourceVersion: "10467436"
    uid: f1acbf2c-5025-47be-aa30-83ddeb6f4ab6
  csi:
    driver: csi.vsphere.vmware.com
    fsType: ext4
    volumeAttributes:
      storage.kubernetes.io/csiProvisionerIdentity: 1604909860583-8081-csi.vsphere.vmware.com
      type: vSphere CNS Block Volume
    volumeHandle: d337654d-09c4-4731-b7af-db9c60a9b5cb
  persistentVolumeReclaimPolicy: Delete
  storageClassName: vsphere
  volumeMode: Filesystem
status:
  phase: Released

**Comment by andrewsykim** [comment]
I think you want to open this issue in https://github.com/kubernetes-sigs/vsphere-csi-driver instead

**Comment by zhoudayongdennis** [comment]
invalid one and create new one in CSI instead of CPI
