### ISSUE TITLE
Merge and improve the documentation of the cloud provider

### ISSUE THREAD

**Issue by embano1** [kubernetes/cloud-provider-vsphere#41]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug
> /kind feature

/kind improvement

**What happened**:
Currently, the ownerhship and status of the in-tree cloud provider documentation is unclear. Also, it ties the cloud provider to the storage related Project "Hatchway" (https://vmware.github.io/vsphere-storage-for-kubernetes/documentation/), where a separation of concerns is perhaps better.

Going forward with both, in-tree and out-of-tree cloud provider, we should consolidate, re-host and clean up the documentation (supported versions, etc.). Also related tools and scripts, e.g. VCP UX deployment script, should be validated against the latest versions or marked as outdated as the current version (https://github.com/vmware/kubernetes/tree/enable-vcp-uxi) seems to be broken with K8s 1.11.

There's several open issues regarding the documentation, e.g. https://github.com/vmware/kubernetes/issues/479 and https://github.com/vmware/kubernetes/issues/491. Also, the current documentation seems to be incorrect with regards to the vsphere.conf on the workers: https://github.com/vmware/kubernetes/issues/501

**Comment by andrewsykim** [comment]
ref https://github.com/kubernetes/cloud-provider/issues/9

**Comment by frapposelli** [comment]
@cantbewong can you help with some links to the docs for in-tree that you authored?

**Comment by andrewsykim** [comment]
Some background information on this from SIG Cloud Provider:

* Ideally we want all providers following a set template so we can easily pull all the docs into a centralized page (something like https://kubernetes.io/docs/setup/pick-right-solution/) 
* There's a KEP to standardize on provider docs which is still a WIP but I think it would still be beneficial to start implementing it based on the proposed changes in https://github.com/kubernetes/enhancements/pull/827

**Comment by andrewsykim** [comment]
/remove-lifecycle stale 

WIP in https://github.com/kubernetes/cloud-provider-vsphere/pull/181

**Comment by frapposelli** [comment]
/close

fixed in #181
