### ISSUE TITLE
Node GC Controller

### ISSUE THREAD

**Issue by andrewsykim** [kubernetes/cloud-provider-vsphere#410]
/kind feature

**What happened**:
There are certain scenarios where it could be beneficial to delete the underlying VM of a node that is in a failed state. One example would be if a node is in a failure state and cannot unmount and detach volumes. In this state, a new pod cannot be  rescheduled to a new node until it's associated volume is unmounted and detached, but we also cannot unmount volumes without the kubelet / CSI running and reporting that status. Even worse is if we attempt to force detach a volume, but during detach the previously failed node comes online again and re-mounts the volume, this could lead to data corruption in the worse case scenario. 

A case can be made where upon specific known failure states, we delete a VM in vCenter to guarantee that the node object is deleted and that the node is guarenteed to not start-up again, this guarentee makes it safe to run force detach operations on volumes to quickly reschedule pods back to healthy nodes. This sort of behavior should NOT be taken lightly as it could result in cascading failures and unexpected deletion of nodes in a cluster, but I'd like to kick off some initial discussions on when/why this could make sense to enable.

**Comment by andrewsykim** [comment]
This sort of behavior is also something that the cluster provisioner should probably handle, not the cloud provider. But still open to hearing ideas/suggestions on this problem.

**Comment by xing-yang** [comment]
Once a VM is deleted by this Node GC Controller, who is responsible for creating a new VM?

**Comment by andrewsykim** [comment]
I think that's up to the cluster provisioner. There's an assumption here that some other system is ensuring clusters always have some desired number of nodes. There's a case to be made that the cluster provisioner should just handle the node health check and deletion then, and not the cloud provider. But that would require every provisioner to re-implement this logic, and typically provisioners don't inspect the volume state of clusters while the cloud provider would.

**Comment by andrewsykim** [comment]
I'm happy to be convinced that the cluster provisioner should handle this sort of thing, cause I'm not in favor of adding this sort of functionality to the cloud provider unless there are no better alternatives. If I'm taking Cluster API as an example, it has machine health checking capabilities but it does not inspect volume states before it decides to replace nodes. Maybe this is acceptable though.

**Comment by xing-yang** [comment]
It might be possible to "cleanup" such a node before pods are allowed to be scheduled on it again rather than delete it.
