### ISSUE TITLE
Supplied deployment manifests taint/toleration mismatch in k8s 1.19

### ISSUE THREAD

**Issue by jonkerj** [kubernetes/cloud-provider-vsphere#413]
/kind bug

**What happened**:
I am using CAPV to bootstrap Talos on vSphere (using CABPT and CACPPT), which mostly works fine. My workload cluster is based on K8S 1.19.3. At the final step, when the API endpoint becomes available, CAPV injects the CPI in the workload cluster. On my workload cluster, however, this consistently leads to a non working `DaemonSet`:

```
jorik@superbox:~$ kubectl get ds -n kube-system vsphere-cloud-controller-manager
NAME                               DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR                     AGE
vsphere-cloud-controller-manager   0         0         0       0            0           node-role.kubernetes.io/master=   32m
```
Note the 0 desired there.

**What you expected to happen**:
I would expect the DaemonSet to get scheduled on all my masters.

**How to reproduce it (as minimally and precisely as possible)**:
Not really sure if this is specific for Talos or K8S v1.19.3 in general. I'd bootstrap k8s v1.19.3 using CAPV and CABPT/CACPPT, but that's a bumpy ride.

**Anything else we need to know?**:
I did a little digging, and I noticed that on my workload cluster the taint on my master node does not match the toleration verbatim. When I change the toleration in the DS spec, it gets scheduled:

```
tolerations:
# omitted
- effect: NoSchedule
  key: node-role.kubernetes.io/master
  value: "true" #<--- I added this one
# omitted
```

I've got a similar issue with CAPV (albeit in golang code, not in YAML), which is filed under kubernetes-sigs/cluster-api-provider-vsphere#1056

**Environment**:
- vsphere-cloud-controller-manager version: v1.2.1
- OS (e.g. from /etc/os-release): Talos 0.7.0
- Kernel (e.g. `uname -a`): v5.9.3

**Comment by dvonthenen** [comment]
I believe this PR https://github.com/kubernetes/cloud-provider-vsphere/pull/392 should address this issue... it just hasn't been merged yet.

If you could test out this change, I can merge this. I'm out on PTO and won't be able to check until Monday.

**Comment by jonkerj** [comment]
Works like a charm!

**Comment by dvonthenen** [comment]
Ok. Merging! Thanks for testing this!

**Comment by dvonthenen** [comment]
Ok. Merging https://github.com/kubernetes/cloud-provider-vsphere/pull/392! Thanks for testing this!

/close
