### ISSUE TITLE
Update the CPI doc related to CSI

### ISSUE THREAD

**Issue by SandeepPissay** [kubernetes/cloud-provider-vsphere#419]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

This is related to the CSI doc here - https://github.com/kubernetes/cloud-provider-vsphere/blob/master/docs/book/tutorials/kubernetes-on-vsphere-with-kubeadm.md#install-the-vsphere-cloud-provider-interface. The doc says:

`Please note that the CSI driver requires the presence of a ProviderID label on each node in the K8s cluster. This can be populated by whatever means is most convenient - Ideally, the Cloud Provider Interface (CPI) would be used as it is actively maintained and updated, but if the vSphere Cloud Provider (VCP) must be used due to brownfield requirements or architectural constraints of your distribution - that is also acceptable. As long as the ProviderID is populated by some means - the vSphere CSI driver will work.
`

CSI is never qualified with in tree VCP as that increases the test matrix and also it will be removed soon. This section of the doc needs to be updated to clarify that CPI is a must for CSI driver. I'm filing this issue to get the doc corrected.

**Comment by bsctl** [comment]
@SandeepPissay any update on it? For my understanding the sentence you reported is no more applicable and no ProviderID label must be provided. Correct?

**Comment by SandeepPissay** [comment]
@bsctl I had an issue with this statement - `Please note that the CSI driver requires the presence of a ProviderID label on each node in the K8s cluster. This can be populated by whatever means is most convenient`

I was highlighting that CPI is a must since we have always qualified vSphere CSI with CPI. In other words, we do not support any other component updating the ProviderID of the node.
