### ISSUE TITLE
Document least privilege roles for vCenter user credentials 

### ISSUE THREAD

**Issue by andrewsykim** [kubernetes/cloud-provider-vsphere#428]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

We should document the least privilege required for the vCenter user/credentials used by the vSphere cloud provider. To my understanding, a read-only role should be sufficient since the vSphere cloud provider does not need any write permissions for VMs.

**Comment by andrewsykim** [comment]
@dvonthenen do you know if we require write permissions for any operations?

**Comment by dvonthenen** [comment]
Sorry for the late reply. Been working on an internal release.

Shouldn't need write operations at all. The permissions should be the same as required by the in-tree driver... and also based on what the CSI driver does, it should also pretty close as far as permissions minus anything storage-related. I haven’t verified that though.

I not really sure about all the permissions required with the new NSXT stuff that’s being introduced in the CPI though.

The existing permissions for the in-tree should be here. Just remove the storage-related stuff for the CPI.
https://vmware.github.io/vsphere-storage-for-kubernetes/documentation/vcp-roles.html
