### ISSUE TITLE
Init fails if config file isn't called vsphere.conf, even when using ConfigMap

### ISSUE THREAD

**Issue by corrieb** [kubernetes/cloud-provider-vsphere#432]
/kind bug

**What happened**:

When following the directions for creating a ConfigMap from the vsphere.conf file for the CPI configuration, there is an undocumented expectation that the file name *must* be vsphere.conf in order for the CCM to initialize successfully.

I would argue that this is a fragile and unintuitive pre-condition, given that the CPI should be looking for the name of the ConfigMap and the data within it. Documentation states: `This file, which here we have called vsphere.conf`. If it must be called vsphere.conf, then this should be made clear. 

**What you expected to happen**:

I would expect that the name of the file that's the source of the data for the ConfigMap should not matter, or this prereq should be clearly documented.

**How to reproduce it (as minimally and precisely as possible)**:

Initialize CPI using a file name that's not `vsphere.conf` when building the ConfigMap. CCM fails to find the config in the ConfigMap and defaults to looking in the filesystem.

```
F0119 00:17:55.755462       1 plugins.go:128] Couldn't open cloud provider configuration /etc/cloud/vsphere.conf: &os.PathError{Op:"open", Path:"/etc/cloud/vsphere.conf", Err:0x2}
```

**Anything else we need to know?**:

I can't find anywhere in the CPI code where this expectation is explicit, so I suspect it may be some weird expectation of the Kubernetes CPI that it requires config to be in the form `cloud-provider-name.conf`. If this is the case, then let's just make it clear in the docs.

**Environment**:
- vsphere-cloud-controller-manager version: master (1/18/21)
- OS (e.g. from /etc/os-release): Photon 3.0
- Kernel (e.g. `uname -a`): 4.19.132-5.ph3-esx
- Install tools:
- Others:

**Comment by kapalevan** [comment]
Does anyone solve that issue ? 

Experiencing same issue with OpenShift 4.6
