### ISSUE TITLE
CloudProvider init appears to have succeeded when initialization failed

### ISSUE THREAD

**Issue by corrieb** [kubernetes/cloud-provider-vsphere#433]
/kind bug
**What happened**:

If you happen to install the Cloud Provider without ensuring that `--cloud-provider=external` is in the kubeadm config, the installation of the CloudProvider appears to have succeeded in that the CCM is running and healthy with no obvious errors.

The only indication that there was an error is if you look at the logs and you see:
```
nodemanager.go:182] shakeOutNodeIDLookup failed. Err=nodeID is empty
```
I spent an hour tracing through the code trying to find out why the nodeID in this function was nil. I eventually realized it's because the ProviderID isn't set on the node because CCM didn't initialize.

Our docs *do* point to the correct config for kubeadm and also indicate to look out for the taints on the node, but I think we can make some improvements.

I would suggest making the following changes:
1. It would be better if CCM wasn't actually "Ready" until it's successfully initialized
2. It would be good to fail earlier with a more helpful error message if Kubelet is obviously misconfigured
3. Looking for the ProviderID in the node Spec is the most obvious verification step, yet it's not mentioned in the docs
4. Rather than "Note the reference" to the kubelet option in the kubeadm config, the doc should make it clear that this is a hard prerequisite.

**What you expected to happen**:

I wouldn't have expected it to take me so long to work out what was wrong. Having the verification step in the docs and a clearer error message would have made it much easier.

**How to reproduce it (as minimally and precisely as possible)**:

Stand up a master using kubeadm without the kubelet `cloud-provider=external` option and then apply the CPI config.

**Anything else we need to know?**:

**Environment**:
- vsphere-cloud-controller-manager version: master (1/18/21)
- OS (e.g. from /etc/os-release): Photon 3.0
- Kernel (e.g. `uname -a`): 4.19.132-5.ph3-esx
- Install tools:
- Others:

**Comment by corrieb** [comment]
@andrewsykim Thanks for the update Andrew. Can you explain how it's a valid configuration? When would you ever want a situation where you don't get ProviderIDs?

**Comment by andrewsykim** [comment]
It's not very common so I'm not sure if we need to account for it, but if I wanted to join baremetal machines to a cluster where the control plane runs on vSphere, I wouldn't set --cloud-provider=external on the kubelets of those machines.

**Comment by jvrahav** [comment]
@andrewsykim would it be possible to address a part of this bug by publishing status on nodes to indicate if there are any failures that CPI is aware of

**Comment by jvrahav** [comment]
Had a brief discussion on this. Andrew suggested that we could potentially make use of NodeConditions to convey the status of CPI w.r.t node. With this we should be able to validate a node for CPI installation/configuration
