### ISSUE TITLE
Unable to label region/zone from vsphere CCM

### ISSUE THREAD

**Issue by xgao3** [kubernetes/cloud-provider-vsphere#435]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
When attempting to provision storage zone/region using documents from here:

https://vsphere-csi-driver.sigs.k8s.io/driver-deployment/deploying_csi_with_zones.html
https://vsphere-csi-driver.sigs.k8s.io/features/volume_topology.html

I'm not able to assign required zone/region node labels using the vSphere cloud config.  I've updated the ConfigMap to include

    [Labels]
    region = "k8s-region"
    zone = "k8s-zone"

deleted vsphere-cloud-controller-manager few times, but not able to get labels assigned to nodes:

root [ /home/capv ]# kubectl get nodes -L failure-domain.beta.kubernetes.io/zone -L failure-domain.beta.kubernetes.io/region
NAME                                     STATUS   ROLES    AGE     VERSION            ZONE   REGION
test-zone-test-control-plane-mv6zz       Ready    master   5h42m   v1.19.1+vmware.2          
test-zone-test-worker-648fcd99d4-q84t8   Ready    <none>   5h41m   v1.19.1+vmware.2          
root [ /home/capv ]# 

No obvious errors are reported in the CCM pod.  

**What you expected to happen**:

Zone and region labels mapped to worker/control plane nodes based on labels assigned in vCenter.

**How to reproduce it (as minimally and precisely as possible)**:

1). edit vsphere-cloud-config
kubectl edit cm -n kube-system vsphere-cloud-config

2). add following lines:

    [Labels]
    region = "k8s-region"
    zone = "k8s-zone"

3). restart cloud manager

kubectl delete pod  vsphere-cloud-controller-manager-d6zbh -n kube-system

**Anything else we need to know?**:

**Environment**:
- vsphere-cloud-controller-manager version: registry.tkg.vmware.run/ccm/manager:v1.2.1_vmware.1
- OS (e.g. from /etc/os-release): Photon OS
- Kernel (e.g. `uname -a`): 4.19.145-2.ph3
- Install tools:  TKG 1.2
- Others:

**Comment by xgao3** [comment]
I tried different version of k8s but still having issues assigning labels..  Any suggestions?

**Comment by PSTobiasMueller** [comment]
I've the same issue. I tried the example from the gitbooks page and although the ccm finds my node i did'nt get any labels for region or zone

**Comment by nickvth** [comment]
You added those tags also on your VMware nodes ? https://github.com/kubernetes/cloud-provider-vsphere/blob/master/docs/book/tutorials/deploying_cpi_and_csi_with_multi_dc_vc_aka_zones.md#2-creating-zones-in-your-vsphere-environment-via-tags

**Comment by nicolehanjing** [comment]
Hi @xgao3 the vsphere-cloud-controller-manager version (v1.2.1) you used was a very old one, zone/region support starts after v1.18.0
can you try using the latest version v1.21.0 and see if the issue is still reproducible?
