### ISSUE TITLE
CCM does not start with K8s 1.20 dependencies

### ISSUE THREAD

**Issue by piepmatz** [kubernetes/cloud-provider-vsphere#438]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

The CCM binary instantly exits with `--cloud-provider cannot be empty`, even though the flag is provided. The binary doesn't react to any flags at all, e.g. `--version` and `-h` have no impact.

I noticed this with a different, private CCM after updating the K8s dependencies to 1.20 and wanted to look how others have solved the issue. #429 by @nicolehanjing looked promising, but results in the same error that I was trying to solve.

**What you expected to happen**:

CCM should react on flags.

**How to reproduce it (as minimally and precisely as possible)**:

```bash
make
.build/bin/vsphere-cloud-controller-manager.linux_amd64 --cloud-provider=foo
```

**Anything else we need to know?**:

@nicolehanjing also updated the AWS CCM's dependencies to K8s 1.20 in https://github.com/kubernetes/cloud-provider-aws/pull/151. Things seem to work there as expected. Maybe because the cobra command is built differently.

**Environment**:
- vsphere-cloud-controller-manager version: d4c2a947bd94b81dc8a96e4926c43bc2cab6fba2 (after merging #429)
- OS (e.g. from /etc/os-release): Docker golang:1.15 and macOS 10.14.6

**Comment by piepmatz** [comment]
It's a K8s upstream bug: https://github.com/kubernetes/cloud-provider/issues/44

**Comment by nicolehanjing** [comment]
Hi @piepmatz 
I have a PR out for fixing this issue: https://github.com/kubernetes/cloud-provider-vsphere/pull/434
There is another PR to fix the upstream bug: https://github.com/kubernetes/kubernetes/pull/98210
