### ISSUE TITLE
Remove documentation about vSphere CSI Driver from CPI Documentation

### ISSUE THREAD

**Issue by divyenpatel** [kubernetes/cloud-provider-vsphere#463]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
/kind documentation

**What happened**:
[CPI documentation](https://cloud-provider-vsphere.sigs.k8s.io/) says about vSphere CSI Driver. Information is not up to date and creating confusion for customers. We need to remove all references of vSphere CSI Driver from the CPI documentation.

**What you expected to happen**:

Here are vSphere CSI references we need to remove

- https://cloud-provider-vsphere.sigs.k8s.io/concepts/csi_overview.html
- https://cloud-provider-vsphere.sigs.k8s.io/container_storage_interface.html
- https://cloud-provider-vsphere.sigs.k8s.io/tutorials/kubernetes-on-vsphere-with-kubeadm.html 
   - Remove section  `Sample manifests to test CSI driver functionality`.
   - Remove section `Verify Cloud Native Storage functionality is working in vSphere`.
- Remove references of CSI from this page - https://cloud-provider-vsphere.sigs.k8s.io/tutorials/deploying_cpi_and_csi_with_multi_dc_vc_aka_zones.html
- Remove deprecated content - https://cloud-provider-vsphere.sigs.k8s.io/tutorials/k8s-vcp-on-vsphere-with-kubeadm.html
 

cc: @SandeepPissay @mylesagray

**Comment by divyenpatel** [comment]
@andrewsykim when can we fix the documentation and remove this page - https://cloud-provider-vsphere.sigs.k8s.io/tutorials/deploying_cpi_and_csi_with_multi_dc_vc_aka_zones.html 

Customers are getting confused regarding the requirement of CPI for topology feature - https://github.com/kubernetes-sigs/vsphere-csi-driver/issues/966

The topology feature in the vSphere CSI driver works fine without the need of configuring zone/region labels in the vSphere cloud provider config file.

**Comment by nicolehanjing** [comment]
Hi @divyenpatel The fix is currently working in progress: https://github.com/kubernetes/cloud-provider-vsphere/pull/497
