### ISSUE TITLE
Document a support policy/commitment for Kubernetes versions

### ISSUE THREAD

**Issue by ibauersachs** [kubernetes/cloud-provider-vsphere#465]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>

/kind bug

> /kind feature

**What happened**:
The documentation does not provide a support policy for new Kubernetes releases. E.g. v1.19.0 of cloud-provider-vsphere was released on Jan 14 2021, while Kubernetes v1.19 was released on 26 August 2020. Similarly, there is no stable release of cloud-provider-vsphere v1.20 yet (with Kubernetes released 8 December 2020, more than 5 months ago), and Kubernetes is already at v1.21 (released over a month ago).

**What you expected to happen**:
Document the level of guaranteed support, i.e. that there will be a matching stable cloud-provider-vsphere release within N weeks of a Kubernetes release.

I realize this is an open-source project, but since this provider is only usable in a commercial, paid-for product (vSphere), and most of the recent commits are from VMware employees, IMO it's not too much to ask. If it is not possible to provide such a guarantee and the project is only maintained on a best-effort basis, this should also be documented.

**Anything else we need to know?**:
Related to #457.

**Environment**:
n/a

**Comment by nicolehanjing** [comment]
@ibauersachs We added the release matrix to README file last week: https://github.com/kubernetes/cloud-provider-vsphere/pull/459, hope that helps :)

**Comment by ibauersachs** [comment]
@nicolehanjing The information merged in #459 doesn't answer my question _at all_. It doesn't contain any timeline for new versions nor a support promise.

**Comment by nicolehanjing** [comment]
I think our current policy is that when a new Kubernetes release comes out, we will bump our k8s dependencies and cut a new release for cloud provider vsphere.
e.g. v1.19.x of cloud-provider-vsphere was released after k8s v1.19 comes out
sometimes we delay our release because of testing for new features or bug fixes

**Comment by ibauersachs** [comment]
An official documentation for supported versions and a support policy (like in the CSI documentation) is still missing.

/remove-lifecycle stale

**Comment by mohag** [comment]
/remove-lifecycle rotten

This probably needs some occasional +1 posts (since there is a bot)

Currently Kubernetes 1.26 is out and the latest version of this is 1.24...

**Comment by chenguo-github** [comment]
+1 for the same question. Is there any plan / timeline to support new minor versions? Thanks!
