### ISSUE TITLE
Support more complicated network setups ther multiple CIDRs are in use for Internal and external IPs

### ISSUE THREAD

**Issue by MaxRink** [kubernetes/cloud-provider-vsphere#474]
/kind feature

**What happened**:
Currently the CPI only supports specifying a single CIDR  to match for internal and external IP.
That isn't always enough, in some instances you end up not being able to set a CIDR that covers all networks that are internal/external (e.g. if you have both 10.0.0.0/8 and 192.168.0.0/16 internal IPs there is no way to safely specify a cidr that covers both without also matching IPs that you most likely will use for external traffic (e.g. internet routable IPs) )
On a first though, this could be solved by making the files setting a the cidr a list of string, so you can define multiple, more granular CIDRs

**Comment by mcwumbly** [comment]
Just came across this and wanted to note that we considered the "list of strings" approach for the dual stack use case as well, but decided to cut that scope on our initial implementation, per https://github.com/kubernetes/cloud-provider-vsphere/pull/508: 

> This commit does not address the fact that only one subnet may be specified for each internal and external network. This means subnet selection does not work in dualstack mode. This functionality can be addressed in a later PR. We'd like discussion with interested parties before we begin that work.

perhaps this is one more reason to consider it though.

cc @tylerschultz
