### ISSUE TITLE
"Signaling deletion" logged at verbosity 4 - should be 2?

### ISSUE THREAD

**Issue by nickperry** [kubernetes/cloud-provider-vsphere#475]
https://github.com/kubernetes/cloud-provider-vsphere/blob/f7b9efdc6be16ba973e2c17cbff28fbff0d4ac57/pkg/cloudprovider/vsphere/instances.go#L179

is logged at V(4), whilst https://github.com/kubernetes/cloud-provider-vsphere/blob/f7b9efdc6be16ba973e2c17cbff28fbff0d4ac57/pkg/cloudprovider/vsphere/instances.go#L164 is at V(2).

This seems counterintuitive? As a user, I'm - if anything - MORE likely to want to know about a machine being deleted than confirmation of it still existing.

**Comment by nicolehanjing** [comment]
Hi @nickperry thanks for raising this, we will fix this soon

**Comment by nickperry** [comment]
I still think this is worth fixing.

**Comment by XudongLiuHarold** [comment]
Hi @nickperry , echo what Nicole said:
```
V(2) - useful information about important log messages that may correlate to important changes
V(4) - for debugging log messages
```
Line 164 uses level 2 is because it shows the important message that the instance exists, Line 179 is just for debugging propose, to log why the instance can't be found. 

So this should be like this.

/close
