### ISSUE TITLE
Is SKIP_NODE_DELETION staying? Can it be documented and used by end users?

### ISSUE THREAD

**Issue by nickperry** [kubernetes/cloud-provider-vsphere#476]
SKIP_NODE_DELETION was originally only intended to be a temporary provision - per https://github.com/kubernetes/cloud-provider-vsphere/issues/393#issuecomment-692382596 - however it still exists.

https://github.com/kubernetes/cloud-provider-vsphere/blob/f7b9efdc6be16ba973e2c17cbff28fbff0d4ac57/pkg/cloudprovider/vsphere/instances.go#L174

Can it be documented and used by end users?

**Comment by yastij** [comment]
cc @andrewsykim

**Comment by mitchellmaler** [comment]
If this is staying as an option can it be added as an option in the vsphere.conf file?
