### ISSUE TITLE
Should CPI delete an unhealthy node when it cannot confirm its existence in VCenter? Or should it have to successfully confirm its non-existance in VCenter? 

### ISSUE THREAD

**Issue by nickperry** [kubernetes/cloud-provider-vsphere#479]
Should CPI delete an unhealthy node when it cannot confirm its existence in VCenter?

Or, should it have to successfully confirm its non-existance in VCenter? 

I believe the former is currently how it works, but I would like it to work like the latter.

/kind bug

**What happened**:

We had a production outage.

A node exceeded the node-monitor-grace-period of 40 seconds between node lease heartbeats.

44 seconds after the last node lease renewal heartbeat, the node controller set condition NodeNotReady.

CPI then tried to verify the node's VM existed, but due to a temporary problem with its VCenter API credentials, it could not auth to the VCenter API.

`node_lifecycle_controller.go:154] error checking if node foo is shutdown: ServerFaultCode: Cannot complete login due to an incorrect user name or password.`

The node then gets deleted as CPI could not confirm its VM still existed.

`Event(v1.ObjectReference{Kind:"Node", Namespace:"", Name:"foo", UID:"365e994a-0d2e-4e0f-a82c-14ba25c392ee", APIVersion:"", ResourceVersion:"", FieldPath:""}): type: 'Normal' reason: 'Deleting node foo because it does not exist in the cloud provider' Node foo event: DeletingNode
`

The node did heartbeat again after 73 seconds and then continued to heartbeat normally, but it was too late to stop the node resource being deleted - the logic that led to its deletion had already been set in motion.

**What you expected to happen**:

I would not expect CPI to mark a node for deletion, because it cannot connect to VCenter. The node should have become ready again and not been deleted.

**How to reproduce it (as minimally and precisely as possible)**:

Set up a cluster with working CPI.
Change the password for the API user that CPI is using to connect to Vcenter, but do not reflect this change in CPI's configmap. Observe login errors in CPI logs.
Cause a cluster node's heartbeat to exceed the node-monitor-grace-period (default 40 seconds), for example by breaking the node's networking.
After a few minutes, check if the node has been deleted.

**Anything else we need to know?**:

**Environment**:
- vsphere-cloud-controller-manager version: 1.2.1
- Kubernetes 1.19.5
- OS (e.g. from /etc/os-release): Oracle Linux 7
- Install tools: Kubeadm

**Comment by nickperry** [comment]
https://github.com/kubernetes/cloud-provider-vsphere/blob/f7b9efdc6be16ba973e2c17cbff28fbff0d4ac57/pkg/cloudprovider/vsphere/instances.go#L155-L181

https://github.com/kubernetes/cloud-provider/blob/kubernetes-1.19.5/controllers/nodelifecycle/node_lifecycle_controller.go#L145-L151

**Comment by nickperry** [comment]
https://github.com/kubernetes/cloud-provider/blob/kubernetes-1.19.5/controllers/nodelifecycle/node_lifecycle_controller.go#L145-L151

**Comment by lubronzhan** [comment]
Hi @nickperry. Do you still have the full CPI log.
According to the logic here https://github.com/kubernetes/cloud-provider-vsphere/blob/v1.2.1/pkg/common/vclib/datacenter.go#L119-L122. it should throw credentials error instead of ErrNotFound.

And also the log you showed, also indicate it didn't get into the deletion logic
```
node_lifecycle_controller.go:154] error checking if node foo is shutdown: ServerFaultCode: Cannot complete login due to an incorrect user name or password.
```

https://github.com/kubernetes/cloud-provider/blob/5a236942a3ca6f0454bfcb979cc31207af4894b2/controllers/nodelifecycle/node_lifecycle_controller.go#L170-L188

I think it's something else that trigger the deletion.

**Comment by nickperry** [comment]
Hi @lubronzhan . I agree - this was the the conclusion I drew when walking through code paths also. However, that line in my kube-apiserver audit logs - 

`Event(v1.ObjectReference{Kind:"Node", Namespace:"", Name:"foo", UID:"365e994a-0d2e-4e0f-a82c-14ba25c392ee", APIVersion:"", ResourceVersion:"", FieldPath:""}): type: 'Normal' reason: 'Deleting node foo because it does not exist in the cloud provider' Node foo event: DeletingNode`

The only place I can see that could generate "Deleting node foo because it does not exist in the cloud provider" is https://github.com/kubernetes/cloud-provider/blob/kubernetes-1.19.5/controllers/nodelifecycle/node_lifecycle_controller.go#L165-L167. And that can only happen if the node has been removed by CPI.

**Comment by nickperry** [comment]
@lubronzhan Here are unfiltered logs for the period. I have just changed hostnames and IPs
[cpi-logs.txt](https://github.com/kubernetes/cloud-provider-vsphere/files/6727264/cpi-logs.txt)

**Comment by nicolehanjing** [comment]
Hi @nickperry 
Currently, the latest vsphere-cloud-controller-manager version is `1.21.0`. The version you used (v1.2.1) is an old one and `v1.2.1 cloud provider vsphere` used a very old **cloud provider** version: https://github.com/kubernetes/cloud-provider-vsphere/blob/v1.2.1/go.mod#L53
It might be good to update to the latest version.

I took a look at the logs, most of them are related to the connection issue due to invalid credentials, some related logs I found:
```
{"message":"E0608 12:45:18.092741       1 node_lifecycle_controller.go:154] error checking if node fookgw12node02.baz is shutdown: ServerFaultCode: Cannot complete login due to an incorrect user name or password.\n","kubernetes":{"container_name":"vsphere-cpi","namespace_name":"kube-system","pod_name":"vsphere-cpi-zphfw","container_image":"docker-registry.prod/mirrors/gcr.io/cloud-provider-vsphere/cpi/release/manager:v1.1.0","host":"fookub11ctlr03.baz","labels":{"app":"vsphere-cpi","component":"cloud-controller","controller-revision-hash":"7bcc6dfd6c","pod-template-generation":"1","release":"vsphere-cpi","vsphere-cpi-infra":"daemonset"}}}
...
...
{"message":"I0608 12:47:07.100405       1 node_lifecycle_controller.go:180] deleting node since it is no longer present in cloud provider: fookgw12node02.baz\n","kubernetes":{"container_name":"vsphere-cpi","namespace_name":"kube-system","pod_name":"vsphere-cpi-zphfw","container_image":"docker-registry.prod/mirrors/gcr.io/cloud-provider-vsphere/cpi/release/manager:v1.1.0","host":"fookub11ctlr03.baz","labels":{"app":"vsphere-cpi","component":"cloud-controller","controller-revision-hash":"7bcc6dfd6c","pod-template-generation":"1","release":"vsphere-cpi","vsphere-cpi-infra":"daemonset"}}}
{"message":"I0608 12:47:07.114146       1 event.go:258] Event(v1.ObjectReference{Kind:\"Node\", Namespace:\"\", Name:\"fookgw12node02.baz\", UID:\"365e994a-0d2e-4e0f-a82c-14ba25c392ee\", APIVersion:\"\", ResourceVersion:\"\", FieldPath:\"\"}): type: 'Normal' reason: 'Deleting node fookgw12node02.baz because it does not exist in the cloud provider' Node fookgw12node02.baz event: DeletingNode\n","kubernetes":{"container_name":"vsphere-cpi","namespace_name":"kube-system","pod_name":"vsphere-cpi-zphfw","container_image":"docker-registry.prod/mirrors/gcr.io/cloud-provider-vsphere/cpi/release/manager:v1.1.0","host":"fookub11ctlr03.baz","labels":{"app":"vsphere-cpi","component":"cloud-controller","controller-revision-hash":"7bcc6dfd6c","pod-template-generation":"1","release":"vsphere-cpi","vsphere-cpi-infra":"daemonset"}}}
```
since the node does not exist in the cloud provider, `node_lifecycle_controller` deletes it. This is the same for another node `fookub11ctlr03.baz`.
I think this is the intended behavior of `node_lifecycle_controller` for even the latest version: https://github.com/kubernetes/cloud-provider/blob/master/controllers/nodelifecycle/node_lifecycle_controller.go#L155

It might be good to add some error checks in the https://github.com/kubernetes/cloud-provider/blob/aba54b70bcbc4d7562e0b8252445089bb4bfb0bb/controllers/nodelifecycle/node_lifecycle_controller.go#L211 e.g. see if it's related to a connection issue, so the node won't get deleted for cases like this

@andrewsykim @lubronzhan wdyt?

**Comment by nickperry** [comment]
Thank you for your analysis @nicolehanjing

**Comment by nicolehanjing** [comment]
@nickperry I tested with the latest cloud provider vsphere version 1.21.0, looks like this issue cannot be reproducible.

**Comment by nickperry** [comment]
> After 2 minutes of the VM not found error, the error disappeared.

Because the node resource was deleted.

> Either the VM is really lost, or VC is returning the wrong information

The VM still existed. Given the credentials were known to be wrong it is impossible for VC to have returned any information, either right or wrong.
