### ISSUE TITLE
Add generating certs (key-pair) in vcpctl for provisioning CCM

### ISSUE THREAD

**Issue by fanzhangio** [kubernetes/cloud-provider-vsphere#48]
`vcpctl` requires user to provide certificate by `--cert` flag in command line. There needs to add an option feature to generate key-pairs  

> Uncomment only one, leave it on its own line: 
>

> /kind feature

**Comment by fanzhangio** [comment]
There are four Solution User Certificates:
- machine
- vpxd
- vpxd-extension
- vsphere-webclient

To generate the cert key-pair for vcpctl, the process is that:
1) Generate `machine.csr` and `machine.key` and store locally. Note: VMCA requires that the certificate have a valid date of at least 24 hours prior
2) Provide the preceding csr to CA to generate a solution user cert and name the files as `machine_name.cer`, `vpxd.cer`, `vpxd-extension.cer`, `vsphere-webclient.cer` and store these files locally (maybe user can specify the path by flags/ENV)
3) Provide the full path to each of these certificates and keys (including CA certs):
- machine.cer
- machine.key
- vpxd.cer
- vpxd.key
- vpxd-extension.cer
- vpxd-extension.key
- vsphere-webclient.cer
- vsphere-webclient.key
- Root64.cer

**Comment by dougm** [comment]
We don't want to use the existing solution user certs.  vCenter doesn't allow multiple solution users to use the same cert anyhow.

govc has some code to generate a new key pair: https://github.com/vmware/govmomi/blob/2eb1d11bc266cc2b0f1f5477ed2dec6ffdcaa5b0/govc/extension/setcert.go#L84

But is only meant for use in tests at the moment, such as: https://github.com/vmware/govmomi/blob/2eb1d11bc266cc2b0f1f5477ed2dec6ffdcaa5b0/govc/test/session.bats#L80

The solution user key pair is only used for signing login requests, they are not used for TLS client authentication.  No need for a CSR or the cert to be signed by a known CA.

**Comment by dvonthenen** [comment]
Closing because PR https://github.com/kubernetes/cloud-provider-vsphere/pull/65 was merged.

/close
