### ISSUE TITLE
Missing/out of date helm charts

### ISSUE THREAD

**Issue by mstrent** [kubernetes/cloud-provider-vsphere#480]
> /kind feature

**What happened**:

Documentation references install via Helm but links are broken or out of date. No official, maintained source seems to exist. The barrier to entry is pretty high on vsphere-csi/cpi. Good helm packaging would improve on this drastically.

```
$ helm repo add stable https://kubernetes-charts.storage.googleapis.com/
**Error: repo "https://kubernetes-charts.storage.googleapis.com/" is no longer available**; try "https://charts.helm.sh/stable" instead
$ helm repo add stable https://charts.helm.sh/stable
"stable" has been added to your repositories
$ helm search repo vsphere-cpi
NAME                    CHART VERSION   APP VERSION     DESCRIPTION
stable/vsphere-cpi      0.2.3           1.2.1           **DEPRECATED** - A Helm chart for vSphere Cloud Pro...
```

**What you expected to happen**:

Helm is a superior way to install and upgrade something like vsphere-cpi.

**How to reproduce it (as minimally and precisely as possible)**:

n/a

**Anything else we need to know?**:

There's a few 3rd parties maintaining helm charts for vsphere CSI and CPI. They are not totally current, but would make a good base to build from:
https://vsphere-tmm.github.io/helm-charts/ (this may be the closest to official, it's by the vSphere Technical Marketing team)
**edit** _The TMM charts above were recently updated and are looking pretty good. Wouldn't it be better if this was made official and added to the source tree?_
https://charts.rancher.io/index.yaml
https://github.com/stefanvangastel/vsphere-cpi-csi-helm/tree/master/charts/vsphere-cpi-csi

**Environment**:

n/a

**Comment by mstrent** [comment]
@nicolehanjing I'd say that PR doesn't fully fix this issue, since the instructions in the docs still specify a "helm repo add" command that doesn't work. As far as I can tell, there's still no valid Helm repo available, so either (1) you need to pull down a local copy of the charts from Github or (2) a proper Helm repo with an index.yaml needs to be provided/documented. (https://helm.sh/docs/topics/chart_repository/)

**Comment by mstrent** [comment]
BTW there's several sources of documentation that need to be updated with correct instructions and current URLs:
https://cloud-provider-vsphere.sigs.k8s.io/tutorials/kubernetes-on-vsphere-with-helm.html
https://github.com/kubernetes/cloud-provider-vsphere/blob/master/docs/book/tutorials/kubernetes-on-vsphere-with-helm.md
https://github.com/kubernetes/cloud-provider-vsphere/blob/master/charts/vsphere-cpi/README.md

**Comment by nicolehanjing** [comment]
Hi @mstrent I will make updates for those related docs soon, once it's ready and fully tested I will let you know

**Comment by mstrent** [comment]
One other quick thing for the Helm chart. On RKE2, the pods will never get scheduled due to 'node-role.kubernetes.io/master: ""' in the nodeSelector in the daemonset template. And since the template if / end value substitute doesn't cover that line, you can't override it with command line or values.yaml.

Either removing that line or extending the values override block around it would solve for RKE2.

    spec:
      nodeSelector:
        node-role.kubernetes.io/master: ""
      {{- if .Values.daemonset.nodeSelector }}
      {{- toYaml .Values.daemonset.nodeSelector | nindent 8 }}
      {{- end }}

**Comment by mstrent** [comment]
...and one more. The RBAC is missing permission for leases. This needs to be added to the role rules:

  - apiGroups:
      - "coordination.k8s.io"
    resources:
      - leases
    verbs:
      - create
      - get
      - list
      - watch
      - update

**Comment by mstrent** [comment]
Thank you, @nicolehanjing !!
