### ISSUE TITLE
1 nodes.go:85] Failed to register node:"masterxx". err=datacenter 'DCNAME - Region' not found

### ISSUE THREAD

**Issue by dburianov** [kubernetes/cloud-provider-vsphere#482]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
We have several configured DataCenters in our VSphere with names like: 
DCNAME - Region, State
and we could not install cloud-provider-vsphere with error:
1 nodes.go:85] Failed to register node:"masterxx". err=datacenter 'DCNAME - Region' not found

**What you expected to happen**:
After investigate this problem we found next:
in error present not full name of datacenter: DCNAME - Region <-> DCNAME - Region, State
in https://github.com/kubernetes/cloud-provider-vsphere/blob/d5f062858935b9c50b0e8e53463b6985ca34494c/pkg/common/connectionmanager/search.go#L131 we see that separator of datacenters is ","

**How to reproduce it (as minimally and precisely as possible)**:
Create Datacenter in VSphere with "," and install cloud privider vsphere

**Anything else we need to know?**:

**Environment**:
- vsphere-cloud-controller-manager version: 1.21.0
- OS (e.g. from /etc/os-release): CentOS Linux 7 (Core)
- Kernel (e.g. `uname -a`): 3.10.0-1160.31.1.el7.x86_64
- Install tools: open-vm-tools.x86_64 11.0.5-3.el7_9.3
- Others:

Could I install and configure cloud-provider-vsphere with "," in DataCenter name?

**Comment by nicolehanjing** [comment]
@andrewsykim wondering if we previously have any naming policy for DataCenter?
that code was written a few years ago, I might miss some contexts here

**Comment by dburianov** [comment]
As I know we use this policy for naming resources more then 3 years. Now we start process upgrade (deploy new cluster with kubespray) exist Kubernetes infrastructure with implement VMWare storage and we have this error. We looked for sollution for renaming exist DataCenters but we have a lot of scripts, where used exists DC names.

**Comment by dburianov** [comment]
and experiments with escape symbol `,` in Go have not positive results

**Comment by nicolehanjing** [comment]
Hi @dburianov
can you also share the **vsphere.conf** you use? 
e.g. https://github.com/kubernetes/cloud-provider-vsphere/blob/master/manifests/controller-manager/vsphere.conf#L14

Also, do you have the log that matches this line: https://github.com/kubernetes/cloud-provider-vsphere/blob/d5f062858935b9c50b0e8e53463b6985ca34494c/pkg/common/connectionmanager/search.go#L152, which would be helpful to debug the issue.

**Comment by dburianov** [comment]
Hello @nicolehanjing 

> Hi @dburianov
> can you also share the **vsphere.conf** you use?
> e.g. https://github.com/kubernetes/cloud-provider-vsphere/blob/master/manifests/controller-manager/vsphere.conf#L14
```
cat vsphere.yml | grep -v "^#"
external_vsphere_vcenter_ip: "az01vc01.corp.local"
external_vsphere_vcenter_port: "443"
external_vsphere_insecure: "true"
external_vsphere_user: "storage_user"
external_vsphere_password: "storage_password"
external_vsphere_datacenter: "DCNAME - Region, State"
external_vsphere_kubernetes_cluster_id: "infra-k8s-mss-sb"

vsphere_csi_enabled: true
```

> 
> Also, do you have the log that matches this line:
> 
> https://github.com/kubernetes/cloud-provider-vsphere/blob/d5f062858935b9c50b0e8e53463b6985ca34494c/pkg/common/connectionmanager/search.go#L152

I don't found nothing in my logs for this log output

My logs:
```
[root@az01sbk8smssmaster01 ~]# kubectl logs -f po/vsphere-csi-controller-0 -n kube-system -c vsphere-csi-controller
I0714 09:21:29.403164       1 config.go:261] GetCnsconfig called with cfgPath: /etc/cloud/csi-vsphere.conf
I0714 09:21:29.403485       1 config.go:206] Initializing vc server az01vc01.corp.local
I0714 09:21:29.403500       1 controller.go:67] Initializing CNS controller
I0714 09:21:29.403526       1 virtualcentermanager.go:63] Initializing defaultVirtualCenterManager...
I0714 09:21:29.403535       1 virtualcentermanager.go:65] Successfully initialized defaultVirtualCenterManager
I0714 09:21:29.403553       1 virtualcentermanager.go:107] Successfully registered VC "az01vc01.corp.local"
I0714 09:21:29.403564       1 manager.go:62] Initializing volume.volumeManager...
I0714 09:21:29.403569       1 manager.go:66] volume.volumeManager initialized
I0714 09:21:29.602561       1 virtualcenter.go:145] New session ID for 'GA\sa-k8s-mss' = 522a0664-9c47-66cf-b65b-86d3bb9e7097
I0714 09:21:29.602600       1 manager.go:74] Initializing node.nodeManager...
I0714 09:21:29.602608       1 manager.go:78] node.nodeManager initialized
I0714 09:21:29.602618       1 kubernetes.go:56] k8s client using in-cluster config
I0714 09:21:29.604081       1 service.go:88] configured: csi.vsphere.vmware.com with map[mode:controller]
time="2021-07-14T09:21:29Z" level=info msg="identity service registered"
time="2021-07-14T09:21:29Z" level=info msg="controller service registered"
time="2021-07-14T09:21:29Z" level=info msg=serving endpoint="unix:///var/lib/csi/sockets/pluginproxy/csi.sock"
I0714 09:21:29.604322       1 reflector.go:123] Starting reflector *v1.Node (0s) from pkg/mod/k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:94
I0714 09:21:29.604346       1 reflector.go:161] Listing and watching *v1.Node from pkg/mod/k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:94
I0714 09:21:29.626657       1 manager.go:101] Successfully registered node: "az01sbk8smssmaster03" with nodeUUID ""
I0714 09:21:29.626699       1 virtualmachine.go:126] Initiating asynchronous datacenter listing with uuid
E0714 09:21:29.633494       1 virtualcenter.go:301] Failed to fetch datacenter given dcPath DCNAME - Region with err: datacenter 'DCNAME - Region' not found
E0714 09:21:29.633530       1 datacenter.go:134] Failed to fetch datacenters for vc az01vc01.corp.local with err: datacenter 'DCNAME - Region' not found
I0714 09:21:29.633548       1 virtualmachine.go:158] AsyncGetAllDatacenters finished with uuid
E0714 09:21:29.633563       1 virtualmachine.go:150] AsyncGetAllDatacenters with uuid  sent an error: datacenter 'DCNAME - Region' not found
I0714 09:21:29.633577       1 virtualmachine.go:142] AsyncGetAllDatacenters finished with uuid
I0714 09:21:29.633589       1 virtualmachine.go:142] AsyncGetAllDatacenters finished with uuid
I0714 09:21:29.633599       1 virtualmachine.go:142] AsyncGetAllDatacenters finished with uuid
I0714 09:21:29.633606       1 virtualmachine.go:142] AsyncGetAllDatacenters finished with uuid
I0714 09:21:29.633615       1 virtualmachine.go:142] AsyncGetAllDatacenters finished with uuid
I0714 09:21:29.633621       1 virtualmachine.go:158] AsyncGetAllDatacenters finished with uuid
E0714 09:21:29.633630       1 virtualmachine.go:193] Returning err: datacenter 'DCNAME - Region' not found for UUID
E0714 09:21:29.633637       1 manager.go:116] Couldn't find VM instance with nodeUUID , failed to discover with err: datacenter 'DCNAME - Region' not found
E0714 09:21:29.633644       1 manager.go:104] Failed to discover VM with uuid: "" for node: "az01sbk8smssmaster03"
W0714 09:21:29.633653       1 nodes.go:85] Failed to register node:"az01sbk8smssmaster03". err=datacenter 'DCNAME - Region' not found
I0714 09:21:29.633662       1 manager.go:101] Successfully registered node: "az01sbk8smssmaster06" with nodeUUID ""
I0714 09:21:29.633673       1 virtualmachine.go:126] Initiating asynchronous datacenter listing with uuid
E0714 09:21:29.639888       1 virtualcenter.go:301] Failed to fetch datacenter given dcPath DCNAME - Region with err: datacenter 'DCNAME - Region' not found
E0714 09:21:29.639913       1 datacenter.go:134] Failed to fetch datacenters for vc az01vc01.corp.local with err: datacenter 'DCNAME - Region' not found
I0714 09:21:29.639936       1 virtualmachine.go:142] AsyncGetAllDatacenters finished with uuid
E0714 09:21:29.639954       1 virtualmachine.go:150] AsyncGetAllDatacenters with uuid  sent an error: datacenter 'DCNAME - Region' not found
I0714 09:21:29.639981       1 virtualmachine.go:158] AsyncGetAllDatacenters finished with uuid
I0714 09:21:29.639997       1 virtualmachine.go:142] AsyncGetAllDatacenters finished with uuid
I0714 09:21:29.640009       1 virtualmachine.go:142] AsyncGetAllDatacenters finished with uuid
I0714 09:21:29.640020       1 virtualmachine.go:142] AsyncGetAllDatacenters finished with uuid
I0714 09:21:29.640030       1 virtualmachine.go:142] AsyncGetAllDatacenters finished with uuid
I0714 09:21:29.640040       1 virtualmachine.go:158] AsyncGetAllDatacenters finished with uuid

``` 
> 
> , which would be helpful to debug the issue.

**Comment by nicolehanjing** [comment]
Hi @dburianov can you share the logs of `vsphere-cloud-controller-manager`?

**Comment by dburianov** [comment]
``Hello @nicolehanjing 
Additional logs for my previus post 
`I0714 09:21:29.952307       1 controller.go:357] ControllerGetCapabilities: called with args {XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0}
I0714 09:21:30.284000       1 controller.go:357] ControllerGetCapabilities: called with args {XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0}
I0714 09:22:29.011706       1 streamwatcher.go:103] Unexpected EOF during watch stream event decoding: unexpected EOF
I0714 09:22:29.011772       1 reflector.go:370] pkg/mod/k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:94: Watch close - *v1.Node total 63 items received
W0714 09:22:30.101148       1 reflector.go:289] pkg/mod/k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:94: watch of *v1.Node ended with: too old resource version: 365209 (365213)
I0714 09:22:31.101631       1 reflector.go:161] Listing and watching *v1.Node from pkg/mod/k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:94
I0714 09:29:38.111112       1 reflector.go:370] pkg/mod/k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:94: Watch close - *v1.Node total 473 items received
I0714 09:38:04.112456       1 reflector.go:370] pkg/mod/k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:94: Watch close - *v1.Node total 554 items received
`
last 2 log line repeat a lot of times

**Comment by dburianov** [comment]
> Hi @dburianov can you share the logs of `vsphere-cloud-controller-manager`?

`kubectl logs vsphere-cloud-controller-manager-jcz8n -n kube-system
I0714 09:22:10.081939       1 main.go:65] vsphere-cloud-controller-manager version: ${VERSION}
I0714 09:22:10.082249       1 flags.go:33] FLAG: --address="0.0.0.0"
I0714 09:22:10.082257       1 flags.go:33] FLAG: --allocate-node-cidrs="false"
I0714 09:22:10.082262       1 flags.go:33] FLAG: --allow-untagged-cloud="false"
I0714 09:22:10.082265       1 flags.go:33] FLAG: --alsologtostderr="false"
I0714 09:22:10.082269       1 flags.go:33] FLAG: --authentication-kubeconfig=""
I0714 09:22:10.082273       1 flags.go:33] FLAG: --authentication-skip-lookup="false"
I0714 09:22:10.082276       1 flags.go:33] FLAG: --authentication-token-webhook-cache-ttl="10s"
I0714 09:22:10.082280       1 flags.go:33] FLAG: --authentication-tolerate-lookup-failure="false"
I0714 09:22:10.082283       1 flags.go:33] FLAG: --authorization-always-allow-paths="[/healthz]"
I0714 09:22:10.082291       1 flags.go:33] FLAG: --authorization-kubeconfig=""
I0714 09:22:10.082294       1 flags.go:33] FLAG: --authorization-webhook-cache-authorized-ttl="10s"
I0714 09:22:10.082297       1 flags.go:33] FLAG: --authorization-webhook-cache-unauthorized-ttl="10s"
I0714 09:22:10.082300       1 flags.go:33] FLAG: --bind-address="0.0.0.0"
I0714 09:22:10.082303       1 flags.go:33] FLAG: --cert-dir=""
I0714 09:22:10.082306       1 flags.go:33] FLAG: --cidr-allocator-type="RangeAllocator"
I0714 09:22:10.082309       1 flags.go:33] FLAG: --client-ca-file=""
I0714 09:22:10.082312       1 flags.go:33] FLAG: --cloud-config="/etc/cloud/vsphere.conf"
I0714 09:22:10.082315       1 flags.go:33] FLAG: --cloud-provider="vsphere"
I0714 09:22:10.082318       1 flags.go:33] FLAG: --cluster-cidr=""
I0714 09:22:10.082320       1 flags.go:33] FLAG: --cluster-name="kubernetes"
I0714 09:22:10.082323       1 flags.go:33] FLAG: --concurrent-service-syncs="1"
I0714 09:22:10.082327       1 flags.go:33] FLAG: --configure-cloud-routes="true"
I0714 09:22:10.082330       1 flags.go:33] FLAG: --contention-profiling="false"
I0714 09:22:10.082333       1 flags.go:33] FLAG: --controller-start-interval="0s"
I0714 09:22:10.082336       1 flags.go:33] FLAG: --controllers="[*]"
I0714 09:22:10.082339       1 flags.go:33] FLAG: --external-cloud-volume-plugin=""
I0714 09:22:10.082342       1 flags.go:33] FLAG: --feature-gates=""
I0714 09:22:10.082346       1 flags.go:33] FLAG: --help="false"
I0714 09:22:10.082349       1 flags.go:33] FLAG: --http2-max-streams-per-connection="0"
I0714 09:22:10.082353       1 flags.go:33] FLAG: --kube-api-burst="30"
I0714 09:22:10.082356       1 flags.go:33] FLAG: --kube-api-content-type="application/vnd.kubernetes.protobuf"
I0714 09:22:10.082360       1 flags.go:33] FLAG: --kube-api-qps="20"
I0714 09:22:10.082365       1 flags.go:33] FLAG: --kubeconfig=""
I0714 09:22:10.082367       1 flags.go:33] FLAG: --leader-elect="true"
I0714 09:22:10.082370       1 flags.go:33] FLAG: --leader-elect-lease-duration="15s"
I0714 09:22:10.082373       1 flags.go:33] FLAG: --leader-elect-renew-deadline="10s"
I0714 09:22:10.082376       1 flags.go:33] FLAG: --leader-elect-resource-lock="endpoints"
I0714 09:22:10.082379       1 flags.go:33] FLAG: --leader-elect-retry-period="2s"
I0714 09:22:10.082382       1 flags.go:33] FLAG: --log-backtrace-at=":0"
I0714 09:22:10.082387       1 flags.go:33] FLAG: --log-dir=""
I0714 09:22:10.082390       1 flags.go:33] FLAG: --log-file=""
I0714 09:22:10.082393       1 flags.go:33] FLAG: --log-file-max-size="1800"
I0714 09:22:10.082396       1 flags.go:33] FLAG: --log-flush-frequency="5s"
I0714 09:22:10.082399       1 flags.go:33] FLAG: --logtostderr="true"
I0714 09:22:10.082402       1 flags.go:33] FLAG: --master=""
I0714 09:22:10.082405       1 flags.go:33] FLAG: --min-resync-period="12h0m0s"
I0714 09:22:10.082408       1 flags.go:33] FLAG: --node-monitor-period="5s"
I0714 09:22:10.082411       1 flags.go:33] FLAG: --node-status-update-frequency="5m0s"
I0714 09:22:10.082414       1 flags.go:33] FLAG: --node-sync-period="0s"
I0714 09:22:10.082417       1 flags.go:33] FLAG: --port="0"
I0714 09:22:10.082420       1 flags.go:33] FLAG: --profiling="false"
I0714 09:22:10.082422       1 flags.go:33] FLAG: --requestheader-allowed-names="[]"
I0714 09:22:10.082428       1 flags.go:33] FLAG: --requestheader-client-ca-file=""
I0714 09:22:10.082431       1 flags.go:33] FLAG: --requestheader-extra-headers-prefix="[x-remote-extra-]"
I0714 09:22:10.082435       1 flags.go:33] FLAG: --requestheader-group-headers="[x-remote-group]"
I0714 09:22:10.082441       1 flags.go:33] FLAG: --requestheader-username-headers="[x-remote-user]"
I0714 09:22:10.082444       1 flags.go:33] FLAG: --route-reconciliation-period="10s"
I0714 09:22:10.082447       1 flags.go:33] FLAG: --secure-port="10258"
I0714 09:22:10.082450       1 flags.go:33] FLAG: --skip-headers="false"
I0714 09:22:10.082453       1 flags.go:33] FLAG: --skip-log-headers="false"
I0714 09:22:10.082468       1 flags.go:33] FLAG: --stderrthreshold="2"
I0714 09:22:10.082470       1 flags.go:33] FLAG: --tls-cert-file=""
I0714 09:22:10.082473       1 flags.go:33] FLAG: --tls-cipher-suites="[]"
I0714 09:22:10.082478       1 flags.go:33] FLAG: --tls-min-version=""
I0714 09:22:10.082481       1 flags.go:33] FLAG: --tls-private-key-file=""
I0714 09:22:10.082484       1 flags.go:33] FLAG: --tls-sni-cert-key="[]"
I0714 09:22:10.082488       1 flags.go:33] FLAG: --use-service-account-credentials="false"
I0714 09:22:10.082490       1 flags.go:33] FLAG: --v="2"
I0714 09:22:10.082493       1 flags.go:33] FLAG: --version="false"
I0714 09:22:10.084373       1 flags.go:33] FLAG: --vmodule=""
I0714 09:22:10.698619       1 serving.go:319] Generated self-signed cert in-memory
W0714 09:22:11.262308       1 client_config.go:541] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
I0714 09:22:11.264729       1 controllermanager.go:117] Version: v0.0.0-master+$Format:%h$
W0714 09:22:11.264748       1 plugins.go:118] WARNING: vsphere built-in cloud provider is now deprecated. The vSphere provider is deprecated and will be removed in a future release
W0714 09:22:11.264823       1 config.go:69] ReadCPIConfigYAML failed: yaml: unmarshal errors:
  line 1: cannot unmarshal !!seq into config.CPIConfigYAML
I0714 09:22:11.265094       1 config.go:77] ReadConfig INI succeeded. CPI INI-based cloud-config is deprecated and will be removed in 2.0. Please use YAML based cloud-config.
I0714 09:22:11.265123       1 config.go:88] Config initialized
E0714 09:22:11.265151       1 config_yaml.go:189] Unmarshal failed: yaml: unmarshal errors:
  line 1: cannot unmarshal !!seq into config.LBConfigYAML
W0714 09:22:11.265305       1 config.go:95] ReadConfigYAML failed: yaml: unmarshal errors:
  line 1: cannot unmarshal !!seq into config.LBConfigYAML
I0714 09:22:11.265359       1 config.go:103] ReadConfig INI succeeded. LoadBalancer INI-based cloud-config is deprecated and will be removed in 2.0. Please use YAML based cloud-config.
I0714 09:22:11.265376       1 config.go:114] Config initialized
I0714 09:22:11.266335       1 secure_serving.go:116] Serving securely on [::]:10258
I0714 09:22:11.266379       1 leaderelection.go:235] attempting to acquire leader lease  kube-system/cloud-controller-manager...
`

**Comment by andrewsykim** [comment]
Do you think you can set the log verbosity to 4 (`--v=4`) and share the logs again?

**Comment by andrewsykim** [comment]
Also, is it accurate to assume your data center is in the format `DCNAME - Region, State`? I _think_ if you don't set the datacenter in the config it will default to checking all datacenters which would work around the parsing issue. Our config reader accepts multiple datacenters that are separated by commands, so a name like `DCNAME - Region, State` is read as two separate datacenters, not one.

**Comment by dburianov** [comment]
Hello @andrewsykim 
as i see verbose mode set to 4

```
kubectl describe po/vsphere-csi-controller-0 -n kube-system
vsphere-csi-controller:
Container ID: containerd://32b1454e524a064a3f6e7adce0ae3c3af27d9cb64dcc1ccd69bccfa6ed6939a2
Image: gcr.io/cloud-provider-vsphere/csi/release/driver:v1.0.2
Image ID: gcr.io/cloud-provider-vsphere/csi/release/driver@sha256:149e87faaacda614ee95ec271b54c8bfdbd2bf5825abc12d45c654036b798229
Port: 9808/TCP
Host Port: 0/TCP
Args:
--v=4
State: Running
```

and in logs I see next:

```
E0716 11:17:33.718210       1 datacenter.go:134] Failed to fetch datacenters for vc az01vc01.corp.local with err: datacenter '' not found
I0716 11:17:33.718238       1 virtualmachine.go:142] AsyncGetAllDatacenters finished with uuid
I0716 11:17:33.718251       1 virtualmachine.go:158] AsyncGetAllDatacenters finished with uuid
I0716 11:17:33.718249       1 virtualmachine.go:158] AsyncGetAllDatacenters finished with uuid
I0716 11:17:33.718259       1 virtualmachine.go:158] AsyncGetAllDatacenters finished with uuid
I0716 11:17:33.718268       1 virtualmachine.go:142] AsyncGetAllDatacenters finished with uuid
E0716 11:17:33.718272       1 virtualmachine.go:150] AsyncGetAllDatacenters with uuid  sent an error: datacenter '' not found
I0716 11:17:33.718279       1 virtualmachine.go:142] AsyncGetAllDatacenters finished with uuid
I0716 11:17:33.718292       1 virtualmachine.go:142] AsyncGetAllDatacenters finished with uuid
E0716 11:17:33.718306       1 virtualmachine.go:193] Returning err: datacenter '' not found for UUID
E0716 11:17:33.718314       1 manager.go:116] Couldn't find VM instance with nodeUUID , failed to discover with err: datacenter '' not found
E0716 11:17:33.718326       1 manager.go:104] Failed to discover VM with uuid: "" for node: "az01sbk8smssnode03"
W0716 11:17:33.718334       1 nodes.go:85] Failed to register node:"az01sbk8smssnode03". err=datacenter '' not found
I0716 11:17:33.718345       1 manager.go:101] Successfully registered node: "az01sbk8smssnode04" with nodeUUID ""
I0716 11:17:33.718355       1 virtualmachine.go:126] Initiating asynchronous datacenter listing with uuid
E0716 11:17:33.724946       1 virtualcenter.go:301] Failed to fetch datacenter given dcPath  with err: datacenter '' not found

```


as I understand, for my configuration with Datacenter with comma, I need rename my Datacenter.

**Comment by nicolehanjing** [comment]
Hi @dburianov can you share the logs of `vsphere-cloud-controller-manager` and set the log verbosity to 4 (--v=4) ?

**Comment by dburianov** [comment]
Hello @nicolehanjing 

```
kubectl logs pod/vsphere-cloud-controller-manager-kqq5g -n kube-system | head -n 100
I0720 14:32:14.544567       1 main.go:65] vsphere-cloud-controller-manager version: ${VERSION}
I0720 14:32:14.545371       1 flags.go:33] FLAG: --address="0.0.0.0"
I0720 14:32:14.545394       1 flags.go:33] FLAG: --allocate-node-cidrs="false"
I0720 14:32:14.545406       1 flags.go:33] FLAG: --allow-untagged-cloud="false"
I0720 14:32:14.545417       1 flags.go:33] FLAG: --alsologtostderr="false"
I0720 14:32:14.545428       1 flags.go:33] FLAG: --authentication-kubeconfig=""
I0720 14:32:14.545439       1 flags.go:33] FLAG: --authentication-skip-lookup="false"
I0720 14:32:14.545448       1 flags.go:33] FLAG: --authentication-token-webhook-cache-ttl="10s"
I0720 14:32:14.545465       1 flags.go:33] FLAG: --authentication-tolerate-lookup-failure="false"
I0720 14:32:14.545481       1 flags.go:33] FLAG: --authorization-always-allow-paths="[/healthz]"
I0720 14:32:14.545500       1 flags.go:33] FLAG: --authorization-kubeconfig=""
I0720 14:32:14.545510       1 flags.go:33] FLAG: --authorization-webhook-cache-authorized-ttl="10s"
I0720 14:32:14.545519       1 flags.go:33] FLAG: --authorization-webhook-cache-unauthorized-ttl="10s"
I0720 14:32:14.545529       1 flags.go:33] FLAG: --bind-address="0.0.0.0"
I0720 14:32:14.545539       1 flags.go:33] FLAG: --cert-dir=""
I0720 14:32:14.545548       1 flags.go:33] FLAG: --cidr-allocator-type="RangeAllocator"
I0720 14:32:14.545558       1 flags.go:33] FLAG: --client-ca-file=""
I0720 14:32:14.545567       1 flags.go:33] FLAG: --cloud-config="/etc/cloud/vsphere.conf"
I0720 14:32:14.545576       1 flags.go:33] FLAG: --cloud-provider="vsphere"
I0720 14:32:14.545591       1 flags.go:33] FLAG: --cluster-cidr=""
I0720 14:32:14.545601       1 flags.go:33] FLAG: --cluster-name="kubernetes"
I0720 14:32:14.545610       1 flags.go:33] FLAG: --concurrent-service-syncs="1"
I0720 14:32:14.545622       1 flags.go:33] FLAG: --configure-cloud-routes="true"
I0720 14:32:14.545631       1 flags.go:33] FLAG: --contention-profiling="false"
I0720 14:32:14.545641       1 flags.go:33] FLAG: --controller-start-interval="0s"
I0720 14:32:14.545650       1 flags.go:33] FLAG: --controllers="[*]"
I0720 14:32:14.545661       1 flags.go:33] FLAG: --external-cloud-volume-plugin=""
I0720 14:32:14.545670       1 flags.go:33] FLAG: --feature-gates=""
I0720 14:32:14.545682       1 flags.go:33] FLAG: --help="false"
I0720 14:32:14.545692       1 flags.go:33] FLAG: --http2-max-streams-per-connection="0"
I0720 14:32:14.545703       1 flags.go:33] FLAG: --kube-api-burst="30"
I0720 14:32:14.545712       1 flags.go:33] FLAG: --kube-api-content-type="application/vnd.kubernetes.protobuf"
I0720 14:32:14.545722       1 flags.go:33] FLAG: --kube-api-qps="20"
I0720 14:32:14.545735       1 flags.go:33] FLAG: --kubeconfig=""
I0720 14:32:14.545744       1 flags.go:33] FLAG: --leader-elect="true"
I0720 14:32:14.545754       1 flags.go:33] FLAG: --leader-elect-lease-duration="15s"
I0720 14:32:14.545765       1 flags.go:33] FLAG: --leader-elect-renew-deadline="10s"
I0720 14:32:14.545775       1 flags.go:33] FLAG: --leader-elect-resource-lock="endpoints"
I0720 14:32:14.545784       1 flags.go:33] FLAG: --leader-elect-retry-period="2s"
I0720 14:32:14.545794       1 flags.go:33] FLAG: --log-backtrace-at=":0"
I0720 14:32:14.545806       1 flags.go:33] FLAG: --log-dir=""
I0720 14:32:14.545816       1 flags.go:33] FLAG: --log-file=""
I0720 14:32:14.545826       1 flags.go:33] FLAG: --log-file-max-size="1800"
I0720 14:32:14.545836       1 flags.go:33] FLAG: --log-flush-frequency="5s"
I0720 14:32:14.545845       1 flags.go:33] FLAG: --logtostderr="true"
I0720 14:32:14.545855       1 flags.go:33] FLAG: --master=""
I0720 14:32:14.545864       1 flags.go:33] FLAG: --min-resync-period="12h0m0s"
I0720 14:32:14.545874       1 flags.go:33] FLAG: --node-monitor-period="5s"
I0720 14:32:14.545884       1 flags.go:33] FLAG: --node-status-update-frequency="5m0s"
I0720 14:32:14.545893       1 flags.go:33] FLAG: --node-sync-period="0s"
I0720 14:32:14.545902       1 flags.go:33] FLAG: --port="0"
I0720 14:32:14.545912       1 flags.go:33] FLAG: --profiling="false"
I0720 14:32:14.545921       1 flags.go:33] FLAG: --requestheader-allowed-names="[]"
I0720 14:32:14.545940       1 flags.go:33] FLAG: --requestheader-client-ca-file=""
I0720 14:32:14.545950       1 flags.go:33] FLAG: --requestheader-extra-headers-prefix="[x-remote-extra-]"
I0720 14:32:14.545961       1 flags.go:33] FLAG: --requestheader-group-headers="[x-remote-group]"
I0720 14:32:14.545975       1 flags.go:33] FLAG: --requestheader-username-headers="[x-remote-user]"
I0720 14:32:14.545987       1 flags.go:33] FLAG: --route-reconciliation-period="10s"
I0720 14:32:14.545996       1 flags.go:33] FLAG: --secure-port="10258"
I0720 14:32:14.546006       1 flags.go:33] FLAG: --skip-headers="false"
I0720 14:32:14.546015       1 flags.go:33] FLAG: --skip-log-headers="false"
I0720 14:32:14.546024       1 flags.go:33] FLAG: --stderrthreshold="2"
I0720 14:32:14.546034       1 flags.go:33] FLAG: --tls-cert-file=""
I0720 14:32:14.546043       1 flags.go:33] FLAG: --tls-cipher-suites="[]"
I0720 14:32:14.546055       1 flags.go:33] FLAG: --tls-min-version=""
I0720 14:32:14.546084       1 flags.go:33] FLAG: --tls-private-key-file=""
I0720 14:32:14.546096       1 flags.go:33] FLAG: --tls-sni-cert-key="[]"
I0720 14:32:14.546108       1 flags.go:33] FLAG: --use-service-account-credentials="false"
I0720 14:32:14.546118       1 flags.go:33] FLAG: --v="4"
I0720 14:32:14.546127       1 flags.go:33] FLAG: --version="false"
I0720 14:32:14.546139       1 flags.go:33] FLAG: --vmodule=""
I0720 14:32:15.035802       1 serving.go:319] Generated self-signed cert in-memory
W0720 14:32:15.826278       1 client_config.go:541] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
I0720 14:32:15.830502       1 controllermanager.go:117] Version: v0.0.0-master+$Format:%h$
W0720 14:32:15.830545       1 plugins.go:118] WARNING: vsphere built-in cloud provider is now deprecated. The vSphere provider is deprecated and will be removed in a future release
W0720 14:32:15.830778       1 config.go:69] ReadCPIConfigYAML failed: yaml: unmarshal errors:
  line 1: cannot unmarshal !!seq into config.CPIConfigYAML
I0720 14:32:15.831208       1 config_ini_legacy.go:160] Initializing vc server az01vc01.corp.local
I0720 14:32:15.831256       1 config.go:77] ReadConfig INI succeeded. CPI INI-based cloud-config is deprecated and will be removed in 2.0. Please use YAML based cloud-config.
I0720 14:32:15.831311       1 config.go:88] Config initialized
E0720 14:32:15.831370       1 config_yaml.go:189] Unmarshal failed: yaml: unmarshal errors:
  line 1: cannot unmarshal !!seq into config.LBConfigYAML
W0720 14:32:15.831648       1 config.go:95] ReadConfigYAML failed: yaml: unmarshal errors:
  line 1: cannot unmarshal !!seq into config.LBConfigYAML
I0720 14:32:15.831726       1 config.go:103] ReadConfig INI succeeded. LoadBalancer INI-based cloud-config is deprecated and will be removed in 2.0. Please use YAML based cloud-config.
I0720 14:32:15.831755       1 config.go:114] Config initialized
I0720 14:32:15.832403       1 secure_serving.go:116] Serving securely on [::]:10258
I0720 14:32:15.832489       1 leaderelection.go:235] attempting to acquire leader lease  kube-system/cloud-controller-manager...
I0720 14:32:15.836475       1 leaderelection.go:344] lock is held by az01sbk8smssmaster03_95e51525-29dd-42fb-bbbf-815be6af0eeb and has not yet expired
I0720 14:32:15.836507       1 leaderelection.go:240] failed to acquire lease kube-system/cloud-controller-manager
```

**Comment by nicolehanjing** [comment]
Hi @drubin 
From my understanding, the log you provided is not from a working leader instance of vsphere-cloud-controller-manager, see the logs: 
```
I0720 14:32:15.832489       1 leaderelection.go:235] attempting to acquire leader lease  kube-system/cloud-controller-manager...
I0720 14:32:15.836475       1 leaderelection.go:344] lock is held by az01sbk8smssmaster03_95e51525-29dd-42fb-bbbf-815be6af0eeb and has not yet expired
I0720 14:32:15.836507       1 leaderelection.go:240] failed to acquire lease kube-system/cloud-controller-manager
```

I think there would be another vsphere-cloud-controller-manager pod that acquired leader lease, can you check that and provide the logs of the leader vsphere-cloud-controller-manager pod?
