### ISSUE TITLE
Create manifests to deploy CCM as pod or daemonset

### ISSUE THREAD

**Issue by frapposelli** [kubernetes/cloud-provider-vsphere#5]
For reference: https://github.com/kubernetes/cloud-provider-openstack/tree/master/manifests/controller-manager

**Comment by frapposelli** [comment]
Initial stab at manifest under review as #14

**Comment by dvonthenen** [comment]
Will deploy and give this a try and provide feedback.

**Comment by dvonthenen** [comment]
I believe I have this working now for both a pod/deployment and DaemonSet with proper RBAC settings. Will have a PR in a bit.

**Comment by dvonthenen** [comment]
PR: https://github.com/kubernetes/cloud-provider-vsphere/pull/20
