### ISSUE TITLE
old cached UUID is used to query from vSphere when adding new node

### ISSUE THREAD

**Issue by ozhankaraman** [kubernetes/cloud-provider-vsphere#501]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
We plan to recycle/replace our nodes with same name, hostname, nodename but with different OS. First we delete the node with kubectl/kubespray, after that when we add new node cloud-provider-vsphere first responds like 
" Successfully initialized node" and after that it gets error like below
"error while looking for vm=420d8d85-cd76-545e-843e-8e7665a58d60(byUUID) in vc=vsphere-xxx and datacenter=datacenter-xxx: No VM found" and  after that it is deleting node.
"deleting node since it is no longer present in cloud provider". 

Somehow even cloud provider got the new correct uuid but it still queries vSphere with old/cached nodes uuid, maybe because old and new nodes hostname, nodename is same. This same procedure was working fine on our old cluster which was using vSphere cloud controller version .1.2.1 and K8s 1.19.x. UUID is enabled on vSphere and vm hw version is 15.

We are using kubespray v2.16.0, our K8s version is v1.20.7 and vSphere cloud controller is v1.21.0

I could also able to add a new node with different name so there is no problem on vSphere integration also we are using this intergation on other clusters for long time without any problem

If I delete all vsphere-cloud-controller-manager daemonset pods then I could able to add a node with same name, specs. Looks like somehow we have problem on caching query or some other mechanism has a problem/bug there.

Whole raw log is below:
```
I0825 13:35:30.416314       1 instances.go:82] instances.NodeAddressesByProviderID() CACHED with 420d8847-8d22-a2c9-d20b-682f7b9706dd
I0825 13:35:30.416319       1 instances.go:82] instances.NodeAddressesByProviderID() CACHED with 420ddd16-f3da-eb46-3140-584d5107204f
I0825 13:36:30.430963       1 instances.go:82] instances.NodeAddressesByProviderID() CACHED with 420d8847-8d22-a2c9-d20b-682f7b9706dd
I0825 13:36:30.430990       1 instances.go:82] instances.NodeAddressesByProviderID() CACHED with 420ddd16-f3da-eb46-3140-584d5107204f
I0825 13:36:30.430996       1 instances.go:82] instances.NodeAddressesByProviderID() CACHED with 420de93e-339a-550b-971b-27059fcd3bd9
I0825 13:36:30.431002       1 instances.go:82] instances.NodeAddressesByProviderID() CACHED with 420d482f-06a0-d0ba-1e7b-4d8382440f38
I0825 13:36:30.431008       1 instances.go:82] instances.NodeAddressesByProviderID() CACHED with 420d1a27-69f9-b618-1c28-b77d0b4132fa
I0825 13:36:30.431013       1 instances.go:82] instances.NodeAddressesByProviderID() CACHED with 420d225e-ab98-d507-ed3e-65ff12399202
I0825 13:36:58.524897       1 node_controller.go:390] Initializing node dev-007-cluster-worker-0 with cloud provider
I0825 13:36:58.524936       1 instances.go:112] instances.InstanceID() CACHED with dev-007-cluster-worker-0
I0825 13:36:58.524948       1 instances.go:82] instances.NodeAddressesByProviderID() CACHED with 420d8d85-cd76-545e-843e-8e7665a58d60
I0825 13:36:58.524959       1 node_controller.go:492] Adding node label from cloud provider: beta.kubernetes.io/instance-type=vsphere-vm.cpu-4.mem-32gb.os-centos7
I0825 13:36:58.524965       1 node_controller.go:493] Adding node label from cloud provider: node.kubernetes.io/instance-type=vsphere-vm.cpu-4.mem-32gb.os-centos7
I0825 13:36:58.525435       1 search.go:76] WhichVCandDCByNodeID nodeID: 420dc08d-0373-fd99-59c1-83136821ebc2
I0825 13:36:58.553101       1 search.go:208] Found node 420dc08d-0373-fd99-59c1-83136821ebc2 as vm=VirtualMachine:vm-3441 in vc=vsphere-xxx and datacenter=datacenter-xxx
I0825 13:36:58.553133       1 search.go:210] Hostname: dev-007-cluster-worker-0, UUID: 420dc08d-0373-fd99-59c1-83136821ebc2
I0825 13:36:58.553155       1 nodemanager.go:134] Discovered VM using normal UUID format
I0825 13:36:58.557448       1 nodemanager.go:241] Adding Hostname: dev-007-cluster-worker-0
I0825 13:36:58.557494       1 nodemanager.go:342] Adding IP: 10.10.10.219
I0825 13:36:58.557510       1 nodemanager.go:366] Found node 420dc08d-0373-fd99-59c1-83136821ebc2 as vm=VirtualMachine:vm-3441 in vc=vsphere-xxx and datacenter=datacenter-xxx
I0825 13:36:58.557522       1 nodemanager.go:368] Hostname: dev-007-cluster-worker-0 UUID: 420dc08d-0373-fd99-59c1-83136821ebc2
I0825 13:36:59.016907       1 node_controller.go:454] Successfully initialized node dev-007-cluster-worker-0 with cloud provider
I0825 13:36:59.017479       1 event.go:291] "Event occurred" object="dev-007-cluster-worker-0" kind="Node" apiVersion="v1" type="Normal" reason="Synced" message="Node synced successfully"
I0825 13:37:00.906421       1 search.go:76] WhichVCandDCByNodeID nodeID: 420d8d85-cd76-545e-843e-8e7665a58d60
E0825 13:37:00.918346       1 datacenter.go:124] Unable to find VM by UUID. VM UUID: 420d8d85-cd76-545e-843e-8e7665a58d60
E0825 13:37:00.918364       1 search.go:181] Error while looking for vm=420d8d85-cd76-545e-843e-8e7665a58d60(byUUID) in vc=vsphere-xxx and datacenter=datacenter-xxx: No VM found
I0825 13:37:00.918374       1 search.go:186] Did not find node 420d8d85-cd76-545e-843e-8e7665a58d60 in vc=vsphere-xxx and datacenter=datacenter-xxx
E0825 13:37:00.918384       1 nodemanager.go:144] WhichVCandDCByNodeID failed using normally formatted UUID. Err: No VM found
I0825 13:37:00.918394       1 search.go:76] WhichVCandDCByNodeID nodeID: 858d0d42-76cd-5e54-843e-8e7665a58d60
E0825 13:37:00.925152       1 datacenter.go:124] Unable to find VM by UUID. VM UUID: 858d0d42-76cd-5e54-843e-8e7665a58d60
E0825 13:37:00.925169       1 search.go:181] Error while looking for vm=858d0d42-76cd-5e54-843e-8e7665a58d60(byUUID) in vc=vsphere-xxx and datacenter=datacenter-xxx: No VM found
I0825 13:37:00.925179       1 search.go:186] Did not find node 858d0d42-76cd-5e54-843e-8e7665a58d60 in vc=vsphere-xxx and datacenter=datacenter-xxx
E0825 13:37:00.925199       1 nodemanager.go:152] WhichVCandDCByNodeID failed using UUID. Err: No VM found
E0825 13:37:00.925205       1 nodemanager.go:182] shakeOutNodeIDLookup failed. Err=No VM found
I0825 13:37:00.925223       1 node_lifecycle_controller.go:155] deleting node since it is no longer present in cloud provider: dev-007-cluster-worker-0
I0825 13:37:00.925488       1 event.go:291] "Event occurred" object="dev-007-cluster-worker-0" kind="Node" apiVersion="" type="Normal" reason="DeletingNode" message="Deleting node dev-007-cluster-worker-0 because it does not exist in the cloud provider"
```

**What you expected to happen**:
I could replace/rebuild a node with same name, spec, hostname, vmname, structure

**How to reproduce it (as minimally and precisely as possible)**:
It fails all the time when I try to add a node

**Anything else we need to know?**:

**Environment**:
- vsphere-cloud-controller-manager version: 1.21.0
- OS (e.g. from /etc/os-release): Centos 7 update 7
- Kernel (e.g. `uname -a`): 3.10.0-1062.9.1.el7.x86_64 
- Install tools: kubespray
- Others:

**Comment by ozhankaraman** [comment]
Hi @nicolehanjing, did you find any time to check this issue, issue is still valid, if you plan to work and send a fix I could test it on my platform.

**Comment by ozhankaraman** [comment]
any news about the issue reported?

**Comment by nicolehanjing** [comment]
Hi @ozhankaraman 

I've investigated this issue today, and the problem I found is that even though `nodeRegUUIDMap` deletes the cache for node `dev-007-cluster-worker-0` with UUID `420d4a89-949a-19cb-5dd3-38adc685db54`, another cache called `nodeUUIDMap` still keeps that record (`420d4a89-949a-19cb-5dd3-38adc685db54` maps to `dev-007-cluster-worker-0`). 

And then when we add node `dev-007-cluster-worker-0` back, though it gets new UUID `420d6092-e577-7d8d-5cd8-2f6b46e4f979`, we still fetch node addresses from `nodeUUIDMap` with old cache `420d4a89-949a-19cb-5dd3-38adc685db54` and since VM cannot be found, we delete the corresponding node `dev-007-cluster-worker-0` by mistake.

**Comment by lubronzhan** [comment]
It's the same issue here https://github.com/kubernetes/cloud-provider-vsphere/issues/397#issuecomment-729076915
We will work on a fix ASAP

**Comment by lubronzhan** [comment]
This is fixed on master branch, we will cherry pick to 1.22 and 1.21

**Comment by ozhankaraman** [comment]
thx @lubronzhan, good work cheers

**Comment by lubronzhan** [comment]
@ozhankaraman I can give you a dev image to try it out for your specific case

**Comment by ozhankaraman** [comment]
send me the image but I need an approval to test it, I will keep you updated, whether I could test or not

**Comment by lubronzhan** [comment]
@ozhankaraman I created this one `lubronzhan/cpi:master` I just built from master branch. If you have security concern you can also build one from master

**Comment by lubronzhan** [comment]
I also built this pre release image as well
`gcr.io/cloud-provider-vsphere/cpi/release/manager:v1.22.4-alpha.1`

**Comment by ozhankaraman** [comment]
Hey @lubronzhan, I tested it with v1.22.4 image and I approve that your fix resolves issue here, thanks for your help
