### ISSUE TITLE
New release image (v1.22) is not pushed to GCR

### ISSUE THREAD

**Issue by nicolehanjing** [kubernetes/cloud-provider-vsphere#504]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
We recently released v1.22 for cloud provider vsphere, see release here: https://github.com/kubernetes/cloud-provider-vsphere/releases/tag/v1.22.0
However, I didn't see the image get pushed to https://console.cloud.google.com/gcr/images/cloud-provider-vsphere/global/cpi/release/manager
Usually the Jenkins job will be triggered automatically(https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-cloud-provider-vsphere-release/) after the release and it will push a new image with the version tag to GCR. But this time it's not working, probably there were some issues with prow lately that could be related.

**What you expected to happen**:
After publishing the release, a new image with the right version tag (gcr.io/cloud-provider-vsphere/cpi/release/manager:v1.22.0) should be published and we should be able to pull via docker commands

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- vsphere-cloud-controller-manager version:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by nicolehanjing** [comment]
Hi @brandond, this issue is solved by https://github.com/kubernetes/test-infra/pull/24029
You should be able to get 1.22 image now

**Comment by lubronzhan** [comment]
Fixed along with this issue https://github.com/kubernetes/test-infra/issues/23604 by https://github.com/kubernetes/test-infra/pull/24029
