### ISSUE TITLE
Cant create PVC with rancher vsphere CSI and CPI

### ISSUE THREAD

**Issue by Tony-The-Developer** [kubernetes/cloud-provider-vsphere#529]
<  /kind bug

**What happened**:

Failed to provision volume with StorageClass "vsphere-csi-sc": rpc error: code = Internal desc = failed to get shared datastores in kubernetes cluster. Error: Empty List of Node VMs returned from nodeManager
xpected to happen**:

nodemanager.go:182] shakeOutNodeIDLookup failed. Err=nodeID is empty

**How to reproduce it (as minimally and precisely as possible)**:
Create cluster and install CPI and CSI

**Anything else we need to know?**:

**Environment**:
- csi-vsphere version: Latest 
- vsphere-cloud-controller-manager version: Latest
- Kubernetes version: Latest
- vSphere version: 7.01
- OS (e.g. from /etc/os-release): ubuntu 20.04
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by lubronzhan** [comment]
Hi @Tony-The-Developer Could you turn on the log level to 5 so we could gather more information? Thank you.

**Comment by Tony-The-Developer** [comment]
<html>
<body>


I1122 01:00:13.023803 1 controller.go:1332] provision "default/test" class "vsphere-csi-sc": started
--
Sun, Nov 21 2021 5:00:13 pm | I1122 01:00:13.023897 1 controller.go:520] skip translation of storage class for plugin: csi.vsphere.vmware.com
Sun, Nov 21 2021 5:00:13 pm | I1122 01:00:13.024105 1 event.go:282] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"default", Name:"test", UID:"cf88e50d-685d-4ecd-abae-810d4fa96f10", APIVersion:"v1", ResourceVersion:"123646", FieldPath:""}): type: 'Normal' reason: 'Provisioning' External provisioner is provisioning volume for claim "default/test"
Sun, Nov 21 2021 5:00:13 pm | I1122 01:00:13.152771 1 controller.go:1099] Final error received, removing PVC cf88e50d-685d-4ecd-abae-810d4fa96f10 from claims in progress
Sun, Nov 21 2021 5:00:13 pm | W1122 01:00:13.152877 1 controller.go:958] Retrying syncing claim "cf88e50d-685d-4ecd-abae-810d4fa96f10", failure 6
Sun, Nov 21 2021 5:00:13 pm | E1122 01:00:13.152910 1 controller.go:981] error syncing claim "cf88e50d-685d-4ecd-abae-810d4fa96f10": failed to provision volume with StorageClass "vsphere-csi-sc": rpc error: code = Internal desc = failed to get shared datastores in kubernetes cluster. Error: empty List of Node VMs returned from nodeManager
Sun, Nov 21 2021 5:00:13 pm | I1122 01:00:13.152939 1 event.go:282] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"default", Name:"test", UID:"cf88e50d-685d-4ecd-abae-810d4fa96f10", APIVersion:"v1", ResourceVersion:"123646", FieldPath:""}): type: 'Warning' reason: 'ProvisioningFailed' failed to provision volume with StorageClass "vsphere-csi-sc": rpc error: code = Internal desc = failed to get shared datastores in kubernetes cluster. Error: empty List of Node VMs returned from nodeManager


</body>
</html>

**Comment by lubronzhan** [comment]
Is this CSI log? Could you share the CPI log instead? Since we only handle issues for CPI. There is different repo for CSI https://github.com/kubernetes-sigs/vsphere-csi-driver.

**Comment by Tony-The-Developer** [comment]
I1121 16:49:10.159872 1 search.go:208] Found node 422ffd68-74b1-12e4-27ce-b125d5b1947d as vm=VirtualMachine:vm-9348 in vc=172.31.1.10 and datacenter=TTD
I1121 16:49:10.159937 1 search.go:210] Hostname: production-etcd1, UUID: 422ffd68-74b1-12e4-27ce-b125d5b1947d
I1121 16:49:10.159978 1 nodemanager.go:134] Discovered VM using normal UUID format
E1121 16:49:10.167826 1 nodemanager.go:182] shakeOutNodeIDLookup failed. Err=nodeID is empty
I1121 16:49:10.167867 1 instances.go:56] instances.NodeAddresses() CACHED with production-control-plane1
I1121 16:49:10.170870 1 nodemanager.go:241] Adding Hostname: production-etcd1
I1121 16:49:10.170949 1 nodemanager.go:342] Adding IP: 172.31.20.23
I1121 16:49:10.170962 1 nodemanager.go:366] Found node 422ffd68-74b1-12e4-27ce-b125d5b1947d as vm=VirtualMachine:vm-9348 in vc=172.31.1.10 and datacenter=TTD
I1121 16:49:10.170987 1 nodemanager.go:368] Hostname: production-etcd1 UUID: 422ffd68-74b1-12e4-27ce-b125d5b1947d
I1121 16:49:10.171065 1 search.go:76] WhichVCandDCByNodeID nodeID: 422f1717-6a55-2860-1c42-5cc0a5160b82
E1121 16:49:10.191732 1 nodemanager.go:182] shakeOutNodeIDLookup failed. Err=nodeID is empty
I1121 16:49:10.191790 1 instances.go:56] instances.NodeAddresses() CACHED with production-control-plane3
I1121 16:49:10.215511 1 search.go:208] Found node 422f1717-6a55-2860-1c42-5cc0a5160b82 as vm=VirtualMachine:vm-9354 in vc=172.31.1.10 and datacenter=TTD
I1121 16:49:10.215571 1 search.go:210] Hostname: production-worker3, UUID: 422f1717-6a55-2860-1c42-5cc0a5160b82
I1121 16:49:10.215639 1 nodemanager.go:134] Discovered VM using normal UUID format
I1121 16:49:10.229025 1 nodemanager.go:241] Adding Hostname: production-worker3
I1121 16:49:10.229100 1 nodemanager.go:342] Adding IP: 172.31.20.46
I1121 16:49:10.229115 1 nodemanager.go:366] Found node 422f1717-6a55-2860-1c42-5cc0a5160b82 as vm=VirtualMachine:vm-9354 in vc=172.31.1.10 and datacenter=TTD
I1121 16:49:10.229140 1 nodemanager.go:368] Hostname: production-worker3 UUID: 422f1717-6a55-2860-1c42-5cc0a5160b82

**Comment by lubronzhan** [comment]
Could you turn the log level to 4 by changing `--v=2` to `--v=5`then paste the CPI log here.
Looks like it tried to find the node and finally found it.
Could you show `kubectl describe nodes | grep "ProviderID"**` and `kubectl get node`
Are nodes all ready and has the providerID? If providerID are ok and nodes are ready, probably something wrong on the CSI side

**Comment by Tony-The-Developer** [comment]
![image](https://user-images.githubusercontent.com/68414482/142793381-1abfe33a-9541-4461-aede-c2e5c41239aa.png)

**Comment by Tony-The-Developer** [comment]
And where do I change the log level? I'm using rancher and helm.

**Comment by nicolehanjing** [comment]
Hi @Tony-The-Developer 
CSI installation doc is updated and can be found here: https://docs.vmware.com/en/VMware-vSphere-Container-Storage-Plug-in/2.0/vmware-vsphere-csp-getting-started/GUID-61646244-E24F-4E7E-AB1A-F95B5A5DD518.html#GUID-61646244-E24F-4E7E-AB1A-F95B5A5DD518
We will update our doc in CPI to remove CSI parts soon, so please refer CSI docs directly

**Comment by lubronzhan** [comment]
Hi @Tony-The-Developer have you tried the doc? We will close this one
