### ISSUE TITLE
Explore the creation of a Helm chart for deploying CCM

### ISSUE THREAD

**Issue by frapposelli** [kubernetes/cloud-provider-vsphere#53]
The CCM could potentially be deployed through Helm for more flexibility, explore the creation of a Helm chart for it.

/kind feature
/assign @dvonthenen

**Comment by dvonthenen** [comment]
Will be looking at this shortly.

**Comment by dvonthenen** [comment]
Submitted Helm to the OSS list. Dev and test on this are complete. Just waiting for OSS sign off to clear before submitting the PR.

**Comment by frapposelli** [comment]
thanks @dvonthenen !

**Comment by dvonthenen** [comment]
OSS Project contribution approved:
https://osstp.vmware.com/oss/#/upstreamcontrib/project/1255745

PR for Initial Release of Chart:
https://github.com/helm/charts/pull/8508

**Comment by frapposelli** [comment]
@dvonthenen is this done? what's missing?

/remove-lifecycle rotten

**Comment by dvonthenen** [comment]
I got tied up with CSI work recently... I need to take this to Charts Office Hours next week (meets on Tues at 9am) and see what the hold up is getting this merged. The chart is complete. Will probably bump the version on it just to use the latest tagged image even though the last 2 tags are functionally identical for the CCM.

**Comment by frapposelli** [comment]
cool! thanks!

**Comment by frapposelli** [comment]
reminder: If not closed by May 1st, drop from the milestone

**Comment by dvonthenen** [comment]
Started looking at this again... this should hopefully be low hanging fruit in terms of refreshing/updating based on changes.

Will try to shepherd this into the charts repo again.

**Comment by dvonthenen** [comment]
This unfortunately isn't so straight forward anymore. 🤣

Will start on this process...
https://github.com/helm/hub/blob/master/Repositories.md

**Comment by dvonthenen** [comment]
Start inquiry about hosting a VMware Helm Chart repo.

**Comment by dvonthenen** [comment]
Pinged Adnan Abdulhussein as a follow up to this issue. Should hear more info about direction of path forward.

**Comment by dvonthenen** [comment]
Discussed with Adnan about this issue... he recommends the best path forward right now is to create a PR into the main helm/charts repo and try to get that merged. since that's a very public facing PR, will re-test for drift (I dont believe there is any) and then open the PR on monday

**Comment by dvonthenen** [comment]
PR submitted:
https://github.com/helm/charts/pull/18790

**Comment by dvonthenen** [comment]
Closing since the PR was merged
/close
