### ISSUE TITLE
vsphere-cloud-controller-manager version is not shown in the log correctly

### ISSUE THREAD

**Issue by alex-vmw** [kubernetes/cloud-provider-vsphere#533]
### What happened?

vsphere-cloud-controller-manager version is shown as `${VERSION}` in the log:
```
I1201 10:00:32.996286       1 main.go:81] vsphere-cloud-controller-manager version: ${VERSION}
```

### What did you expect to happen?

Expected to see a version number instead of `${VERSION}`.

### How can we reproduce it (as minimally and precisely as possible)?

Start vsphere-cloud-controller-manager 1.22.3 and look at its log.

### Kubernetes version

<details>
1.22.3
</details>

### Cloud provider or hardware configuration

<details>
vSphere
</details>

### OS version

<details>
Ubuntu 20.04.3 LTS
</details>

### Kernel (e.g. `uname -a`)

<details>
5.4.0-88-generic
</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### Others

<details>

</details>

**Comment by nicolehanjing** [comment]
I think the value comes from https://github.com/kubernetes/cloud-provider-vsphere/blob/master/cmd/vsphere-cloud-controller-manager/main.go#L81, where [makefile](https://github.com/kubernetes/cloud-provider-vsphere/blob/master/Makefile#L76) passes the version value. 

I checked the value by running: 
```
$ make version
v1.22.3
```

So even the version value is correct, the problem is that we cannot pass it via MakeFile. Do you have any context for it? @akutz

**Comment by akutz** [comment]
Hi @nicolehanjing ,

I guarantee at one point in time a Go build flag was used to set `main.version` at https://github.com/kubernetes/cloud-provider-vsphere/blob/master/cmd/vsphere-cloud-controller-manager/main.go#L54.

**Comment by akutz** [comment]
In fact, it should still set the version via https://github.com/kubernetes/cloud-provider-vsphere/blob/0ce006108f01994e3c7b4b35dde1162262807c93/Makefile#L76.

What I bet is happening is the official binary is being built where there are no git tags and thus no version is calculated.

**Comment by akutz** [comment]
It still embeds the version when built locally:

1. Clone the repo
2. Run `make` and one can see the following in the output:
    ```bash
    CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags '-extldflags "-static" -w -s -X "main.version=v1.22.3-10-g0ce0061" -X "k8s.io/kubernetes/pkg/version.gitVersion=v1.22.3-10-g0ce0061" -X "k8s.io/component-base/pkg/version.gitVersion=v1.22.3-10-g0ce0061"' -o /Users/akutz/Projects/cloud-provider-vsphere/.build/bin/vsphere-cloud-controller-manager.linux_amd64 cmd/vsphere-cloud-controller-manager/main.go
    ```
3. The binary will be built at `.build/bin/vsphere-cloud-controller-manager.linux_amd64`
4. Use the `strings` command to verify the version is in the binary:
    ```bash
    $ strings .build/bin/vsphere-cloud-controller-manager.linux_amd64 | grep -F 'v1.22.3-10-g0ce0061'        
    v1.22.3-10-g0ce0061
    ```
5. I can even verify the binary prints the version by running the command via docker:
    ```bash
    $ docker run -it --rm -v $(pwd)/.build/bin/vsphere-cloud-controller-manager.linux_amd64:/ccm ubuntu /ccm --version
    vsphere-cloud-controller-manager v1.22.3-10-g0ce0061
    ```

So it's still there. It is likely how it's being built officially causing the version to not show up.

**Comment by nicolehanjing** [comment]
Hi @akutz , thanks for the info and it looks like the issue is in the dockerfile for building images.
I've validated the fix and here's the PR: https://github.com/kubernetes/cloud-provider-vsphere/pull/535
