### ISSUE TITLE
controllermanager.go version is not shown in the log correctly

### ISSUE THREAD

**Issue by alex-vmw** [kubernetes/cloud-provider-vsphere#534]
### What happened?

controllermanager.go version is shown as `v0.0.0-master+$Format:%H$` in the log:
```
I1201 10:00:32.996725       1 controllermanager.go:142] Version: v0.0.0-master+$Format:%H$
```

### What did you expect to happen?

Expected to see a real version number instead of `v0.0.0-master+$Format:%H$`.

### How can we reproduce it (as minimally and precisely as possible)?

Start vsphere-cloud-controller-manager 1.22.3 and look at its log.

### Kubernetes version

<details>
1.22.3
</details>

### Cloud provider or hardware configuration

<details>
vSphere
</details>

### OS version

<details>
Ubuntu 20.04.3 LTS
</details>

### Kernel (e.g. `uname -a`)

<details>
5.4.0-88-generic
</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### Others

<details>

</details>

**Comment by nicolehanjing** [comment]
Hi @alex-vmw
this should be fixed in the upstream https://github.com/kubernetes/cloud-provider/blob/master/app/controllermanager.go#L144.
I've duplicated this issue in the cloud provider repo: https://github.com/kubernetes/cloud-provider/issues/53

**Comment by XudongLiuHarold** [comment]
Resolved by above PR.

/close

**Comment by lubronzhan** [comment]
Reopen since upstream hasn't fixed this yet
