### ISSUE TITLE
Add unit tests for the helm charts

### ISSUE THREAD

**Issue by HanFa** [kubernetes/cloud-provider-vsphere#549]
### What would you like to be added?

Unit tests for the CPV helm charts can be run with the unit test plugin https://github.com/helm-unittest/helm-unittest `helm unittest`

### Why is this needed?

Unit tests for the CPV helm charts can be added to improve the testability of the helm manifests.

**Comment by XudongLiuHarold** [comment]
The helm unittest repo is not maintained anymore.

/close
