### ISSUE TITLE
chart:  use of plaintext password in config map leaks credentials

### ISSUE THREAD

**Issue by addyess** [kubernetes/cloud-provider-vsphere#597]
https://github.com/kubernetes/cloud-provider-vsphere/blob/ce447aa6b3d277a0fec371b1a648a26b3f3e7d63/charts/vsphere-cpi/templates/configmap.yaml#L26-L27

why don't these reference a secret like this:
```yaml
      secretName: vsphere-cloud-secret
      secretNamespace: kube-system
```

**Comment by vadim-morozow** [comment]
bump
