### ISSUE TITLE
Enable the use of Kubernetes secrets to store passwords for CCM

### ISSUE THREAD

**Issue by frapposelli** [kubernetes/cloud-provider-vsphere#6]
We should allow users to store infrastructure secrets in the right place.

/kind feature

**Comment by dvonthenen** [comment]
I am actually looking at the code and the functionality is mostly there with a couple of (significant) caveats:
1. The functionality is disabled currently (hence the significant caveat).
2. I don't really agree with the order precedence for what credentials are used to establish a connection.

Going to re-enable it (see if what is implemented actually works) and change the precedence.

**Comment by dvonthenen** [comment]
PR: https://github.com/kubernetes/cloud-provider-vsphere/pull/33
