### ISSUE TITLE
Integration test and several other test should be running on PR against release branch as well

### ISSUE THREAD

**Issue by lubronzhan** [kubernetes/cloud-provider-vsphere#603]
### What would you like to be added?

Below tests are only run against master branch
https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/cloud-provider-vsphere/cloud-provider-vsphere-config.yaml#L142-L284
We should make it run against release branch as well

### Why is this needed?

Currently, there are some tests we only run on master branch, there is no verification for PR against release branch.

**Comment by HanFa** [comment]
Submitted a PR on test-infra that run CI against different release branches. https://github.com/kubernetes/test-infra/pull/25599
