### ISSUE TITLE
Node initialization fails with multiple IPs and node IP is not first

### ISSUE THREAD

**Issue by bnason** [kubernetes/cloud-provider-vsphere#614]
### What happened?

Deployed vSphere CPI into a new cluster, when it goes to initialize the node, it is seemingly failing because it only gets the first IP in vSphere and that does not match the reported node IP. This node has 2 IPs associated with it initially: 1) the K8s API Server Floating IP and 2) the node ip

### What did you expect to happen?

vSphere CPI to check all IPs against the node ip

### How can we reproduce it (as minimally and precisely as possible)?

Have a VM Node with 2 IPs, where the first IP is not the "node ip". For example, it could be a floating load balancer ip.

### Anything else we need to know (please consider providing level 4 or above logs of CPI)?

[vsphere-tmm-vsphere-cpi-rw497.log](https://github.com/kubernetes/cloud-provider-vsphere/files/8453334/vsphere-tmm-vsphere-cpi-rw497.log)

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.5", GitCommit:"c285e781331a3785a7f436042c65c5641ce8a9e9", GitTreeState:"clean", BuildDate:"2022-03-16T15:58:47Z", GoVersion:"go1.17.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.8", GitCommit:"7061dbbf75f9f82e8ab21f9be7e8ffcaae8e0d44", GitTreeState:"clean", BuildDate:"2022-03-16T14:04:34Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider or hardware configuration

<details>

</details>

### OS version

<details>

```console
$ cat /etc/os-release
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
LOGO=archlinux-logo

```

</details>

### Kernel (e.g. `uname -a`)

<details>

```console
$ uname -a
Linux workstation 5.16.13-arch1-1 #1 SMP PREEMPT Tue, 08 Mar 2022 20:07:36 +0000 x86_64 GNU/Linux

```

</details>

### Install tools

<details>
Cluster API (CAPI)
Cluster API vSphere Provider (CAPV)
Cluster API Bootstrap Provider Talos (CABPT)
Cluster API Control Plane Provider Talos (CACPPT)
</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
vSphere CPI v1.22.5
vSphere CSI v2.5.1
</details>

### Others

<details>

</details>

**Comment by bnason** [comment]
I've forked this repo and updated the code as best as I can to allow for multiple IPs and have it working for me.

Fix applied to v1.22.6
https://github.com/bnason/cloud-provider-vsphere/tree/v1.22.6-fix-multi-ips

Fix applied to master
https://github.com/bnason/cloud-provider-vsphere/tree/fix-multi-ips

**Comment by johnwc** [comment]
Did you create a PR for your fixes?

**Comment by lubronzhan** [comment]
Sorry. I'll take a look at the code.
Currently, workaround would be using 
```
[Nodes]
exclude-internal-network-subnet-cidr
exclude-external-network-subnet-cidr
```

**Comment by lubronzhan** [comment]
Are you passing `--node-ip` to your kubelet?
https://github.com/kubernetes/cloud-provider/blob/v0.22.6/controllers/node/node_controller.go#L695-L708
Looks like if the IP that vsphere CPI pick up doesn't match the kubelet ip then it will fail.
Let me check with previous contributor why only single ip is added to Node, whether there are other potential risks

**Comment by lubronzhan** [comment]
We could try loosing the criteria with some APHA feature gate. Don't want to immediately open the pandora's box

**Comment by lubronzhan** [comment]
Oh also I think we broke the logic when implementing the dual stack, at least we should show each Nic's IP

**Comment by benjvfr** [comment]
Having the same issue, the control plane node having the Kubernetes API Server VIP is not initialized by vSphere CPI : 
```
instances.NodeAddressesByProviderID() FOUND with 420f3e49-ce2a-1623-6446-593cb5ed1354
E0202 15:22:59.147699       1 node_controller.go:229] error syncing 'k8s-control-plane-89v1pq': failed to get node modifiers from cloud provider: provided node ip for node "k8s-control-plane-89v1pq" is not valid: failed to get node address from cloud provider that matches ip: 10.50.1.4, requeuing
```
I tried to exclude the vip in vsphere.conf, but not working : 
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: cloud-config
  namespace: kube-system
data:
  vsphere.conf: |
    global:
      port: 443
      ....
    nodes:
      exclude-internal-network-subnet-cidr: "10.50.1.200/32"
      exclude-external-network-subnet-cidr: "10.50.1.200/32"
```

**Comment by roman-geraskin-m10** [comment]
Still have this issue 

/reopen

**Comment by vring0** [comment]
+1

**Comment by nightguide** [comment]
+1 

/reopen

**Comment by lubronzhan** [comment]
Hi @nightguide could you open a new issue with your clusters' detail? Thank you

**Comment by nightguide** [comment]
Hi @lubronzhan!

Done. See https://github.com/kubernetes/cloud-provider-vsphere/issues/1455

**Comment by nightguide** [comment]
@roman-geraskin-m10 @bnason @benjvfr Hi all!

Solution can be found here. https://github.com/kubernetes/cloud-provider-vsphere/issues/1455
