### ISSUE TITLE
Helm install/upgrade fails

### ISSUE THREAD

**Issue by mstrent** [kubernetes/cloud-provider-vsphere#637]
### What happened?

Attempted to install the latest version of the CPI Helm chart and received the following error from Helm:

`Error: UPGRADE FAILED: template: vsphere-cpi/templates/service.yaml:1:14: executing \"vsphere-cpi/templates/service.yaml\" at <.Values.service.enabled>: nil pointer evaluating interface {}.enabled`

I believe this is due to removing the "service" section from values.yaml in this commit:
https://github.com/kubernetes/cloud-provider-vsphere/commit/a8648cf38a7785f1c61589cd29523d5ad8483008

Adding " --set service.enabled=false" to the helm command line works around the issue.

### What did you expect to happen?

Successful install of vSphere CPI via helm.

### How can we reproduce it (as minimally and precisely as possible)?

Install vSphere CPI via provided helm chart per instructions.

### Kubernetes version

<details>

1.21

</details>

### Cloud provider or hardware configuration

<details>
RKE2 on prem
</details>

### OS version

<details>
Ubuntu
</details>

### Kernel (e.g. `uname -a`)

<details>

</details>

### Install tools

<details>
Helm 3.x
</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### Others

<details>

</details>

**Comment by stratus-ss** [comment]
I have the same problem

K8s version: v1.23.5+3afdacb
OpenShift: 4.10.18

Cloud Provider: VMWare 7.x

**Comment by lubronzhan** [comment]
We removed the service  from CPI, let me fix the helm

**Comment by lubronzhan** [comment]
It's fixed in 1.24.1

**Comment by mstrent** [comment]
Thank you!
