### ISSUE TITLE
Bug: gopkg.toml should be updated with dependencies

### ISSUE THREAD

**Issue by fanzhangio** [kubernetes/cloud-provider-vsphere#64]
**BUG REPORT**:
Some commits imported packages which not updated in Gopkg.toml. It will cause compile error in local dev env.  So, it would be better for updating the Gopkg.toml along with each PR commit.

> /kind bug

**What happened**:
For example: 
Gopkg.toml only contains minimal dependencies, like `k8s.io/api`, `k8s.io/apimachinery`, `k8s.io/client-go`, `k8s.io/kubernetes`, etc.

New added dependencies are missing, like `k8s.io/sample-controller`, etc.

**What you expected to happen**:
Update the toml file by adding each new dependency.

**Anything else we need to know?**:

**Environment**:
- vsphere-cloud-controller-manager version:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by frapposelli** [comment]
closing since we moved to go module

/close
