### ISSUE TITLE
CPI should not trigger deleting Node when Node VM is inaccessible 

### ISSUE THREAD

**Issue by divyenpatel** [kubernetes/cloud-provider-vsphere#642]
### What happened?

When Node VM is inaccessible for any reason, but VM is still present in the VC inventory, CPI is telling k8s to delete the Node.

### What did you expect to happen?

CPI should not trigger Node Object deletion when Node is present in the VC inventory in any state. Only when Node is deleted from VC inventory it should be removed from k8s.

We can preserve VM MoRef somewhere on the k8s node object, and attempt to find VM for the MoRef.
If Moref is found and its state is inaccessible we should not trigger deletion of Node.

We need to make this change in `func (i *instances) InstanceExistsByProviderID(ctx context.Context, providerID string) (bool, error) {`
https://github.com/kubernetes/cloud-provider-vsphere/blob/8a5fcdb50b37f1b0780ad163a3877e3145f53c2a/pkg/cloudprovider/vsphere/instances.go#L153-L177

![vm-connection-state](https://user-images.githubusercontent.com/22985595/185513556-6782f079-8068-4d84-a1ea-71b64c557056.jpg)

### How can we reproduce it (as minimally and precisely as possible)?

Deploy Node VM on the Datastore on the external array.
Remove access of datastore for the esxi host on which Node VM is deployed.
Node VM will become inaccessible.

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider or hardware configuration

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Kernel (e.g. `uname -a`)

<details>

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### Others

<details>

</details>

**Comment by divyenpatel** [comment]
@yastij what is your opinion on the fix?
This fix will resolve a lot of issues occurring due to VM becoming inaccessible for a short period of time.

**Comment by lubronzhan** [comment]
Hi @divyenpatel 
> CPI should not trigger Node Object deletion when Node is present in the VC inventory in any state. Only when Node is deleted from VC inventory it should be removed from k8s.
Do you mean there could be a case that even the VM is not deleted, VC would still return error like `ErrNoVMFound`?  Otherwise why would CPI delete the node if it could find it.
Then what would adding `VM MoRef` make a difference? Since CPI would still call the same VC API.
Could you please clarify this?

**Comment by divyenpatel** [comment]
@lubronzhan 

When VM becomes in-accessible, ` SearchIndex -> FindbyUUID ` API return void, which is treated as "VM not found" by CPI, and thus CPI triggers delete of the Node object from the API server.

**Comment by divyenpatel** [comment]
SearchIndex -> FindbyUUID does not differentiate between VM inaccessible vs VM removed from VC inventory.
but if you query VM using vm-moref, we can look up connectionstate and skip issuing VM object deletion for VMs went into an in-accessible state.

**Comment by lubronzhan** [comment]
Thanks. We do have caching inside CPI, let me see if I can cache the moref in that and make use of it

**Comment by lubronzhan** [comment]
Hi @divyenpatel I created a PR here could you review https://github.com/kubernetes/cloud-provider-vsphere/pull/650
Also is it possible to build a dev image and test in your environment? Since I'm not sure how to reproduce this scenario

**Comment by divyenpatel** [comment]
We can reproduce this issue easily. 

Deploy Node VM on NFS datastore, and then shut down NFS server, which in turn will make datastore and Node VM inaccessible. Node VM is still present on the VC inventory but it is inaccessible and in that case, Node should not be deleted from the API server.

@lubronzhan 
Can you share the CPI image with the fix?

**Comment by lubronzhan** [comment]
@divyenpatelhere it is: gcr.io/cf-pks-golf/cpi:test-vm-state-check
Ok, our nimbus testbed only has iscsi datastore

**Comment by divyenpatel** [comment]
Thanks, @lubronzhan we will update you about the testing result.

**Comment by divyenpatel** [comment]
@lubronzhan we have validated the image you have provided. It is working as expected.
you can merge the PR and provide us an official release.

**Comment by lubronzhan** [comment]
Cool, 1.24.2 should include this fix
https://github.com/kubernetes/cloud-provider-vsphere/releases/tag/v1.24.2
