### ISSUE TITLE
CPI cannot initialize vm, error "Failed to find VM by DNS Name", missing read-only permission on datacenter

### ISSUE THREAD

**Issue by m-ferrero** [kubernetes/cloud-provider-vsphere#665]
### What happened?

On a customer we have a kubernetes cluster installed with rancher inside a vmware vsphere environment.
We have installed cpi and csi vmware drivers with rancher helm charts.
The final goal is to use vsphere csi volumes in the kubernetes cluster.

There is a "rancher" user created in vmware for the cpi and csi drivers.
Permissions and roles have been created accordingly to this document
https://docs.vmware.com/en/VMware-vSphere-Container-Storage-Plug-in/2.0/vmware-vsphere-csp-getting-started/GUID-0AB6E692-AA47-4B6A-8CEA-38B754E16567.html

For security reasons the customer is not willing to give the rancher vmware user the permission Read-only on the datacenter.
It has been given only on the single host where the vm are running.

In these conditions the nodes cannot be initialized correctly, they remains with the taint
"node.cloudprovider.kubernetes.io/uninitialized=true:NoSchedule"

In the cpi pods we see the errors:
"Failed to find VM by DNS Name. VM DNS Name: VMNAME, err: ServerFaultCode: Permission to perform this operation was denied."

As a workaround we already know we can:
- give the user that permission
- let the cpi initialize the nodes
- remove the permission
- the cpi will gives errors, but the csi and the volumes will work

We do not know if this can be considered a stable situation and if every thing can stop working any moment.

Is it possible to make the drivers work without this permission or with some reduced permission?

thanks
best redgards
Massimiliano

### What did you expect to happen?

Have a reduced sets of permissions that not involves read-only on the whole datacenter.

We already know it is not feasible to ask the customer a dedicated datacenter just for the kubernetes clusters.

### How can we reproduce it (as minimally and precisely as possible)?

The issue should not be rancher related, I think any kubernetes cluster in vmware in same conditions, read-only permission missing on datacenter, should behave in the same manner.

We have counter tested: we have a working cluster in a test environment, same version and all permissions given, and it's working correctly.

We removed the permission from rancher vmware user, created a new node, had the cpi try to initialize it and it failed with the same error.

### Anything else we need to know (please consider providing level 4 or above logs of CPI)?

I1020 15:22:23.783665       1 node_controller.go:390] Initializing node VMNAME with cloud provider
I1020 15:22:23.783716       1 search.go:76] WhichVCandDCByNodeID nodeID: VMNAME
E1020 15:22:23.790424       1 datacenter.go:103] Failed to find VM by DNS Name. VM DNS Name: VMNAME, err: ServerFaultCode: Permission to perform this operation was denied.
E1020 15:22:23.790442       1 search.go:181] Error while looking for vm=VMNAME(byName) in vc=IP and datacenter=DCNAME: ServerFaultCode: Permission to perform this operation was denied.
E1020 15:22:23.790459       1 nodemanager.go:205] shakeOutNodeIDLookup failed. Err=ServerFaultCode: Permission to perform this operation was denied.
E1020 15:22:23.790486       1 node_controller.go:212] error syncing 'VMNAME': failed to get provider ID for node VMNAME at cloudprovider: failed to get instance ID from cloud provider: ServerFaultCode: Permission to perform this operation was denied., requeuing
I1020 15:22:25.278278       1 node_controller.go:390] Initializing node VMNAME with cloud provider
I1020 15:22:25.278313       1 search.go:76] WhichVCandDCByNodeID nodeID: VMNAME
E1020 15:22:25.286864       1 datacenter.go:103] Failed to find VM by DNS Name. VM DNS Name: VMNAME, err: ServerFaultCode: Permission to perform this operation was denied.
E1020 15:22:25.286878       1 search.go:181] Error while looking for vm=VMNAME(byName) in vc=IP and datacenter=DCNAME: ServerFaultCode: Permission to perform this operation was denied.
E1020 15:22:25.286895       1 nodemanager.go:205] shakeOutNodeIDLookup failed. Err=ServerFaultCode: Permission to perform this operation was denied.
E1020 15:22:25.286924       1 node_controller.go:212] error syncing 'VMNAME': failed to get provider ID for node VMNAME at cloudprovider: failed to get instance ID from cloud provider: ServerFaultCode: Permission to perform this operation was denied., requeuing

### Kubernetes version

Kubernetes version: 1.23.7 and 1.23.10

### Cloud provider or hardware configuration

Version 6.7.0 Build 19299595
vSphere Client version 6.7.0.51000
Hypervisor: VMware ESXi, 6.7.0, 19195723
VM HW Version: 13
VMware Tools: Running, version:12320 (Guest Managed)

### OS version

openSUSE Leap 15.3

### Kernel (e.g. `uname -a`)

Linux ELVGNGKUBWK1 5.3.18-150300.59.93-default #1 SMP Tue Sep 6 05:05:37 UTC 2022 (7acce37) x86_64 x86_64 x86_64 GNU/Linux

### Install tools

Rancher v2.6.6

### Related plugins (CNI, CSI, ...) and versions (if applicable)

rancher/mirrored-cloud-provider-vsphere-csi-release-driver:v2.5.1
rancher/mirrored-cloud-provider-vsphere-cpi-release-manager:v1.22.6

**Comment by lubronzhan** [comment]
Hi @m-ferrero, we have a page of minimum required documentation https://github.com/kubernetes/cloud-provider-vsphere/blob/83fe0cb99f97ee736e6e8471e76a979cdec7fd96/docs/book/vcp_roles.md
Unfortunately, datacenter readonly is required for that
