### ISSUE TITLE
cloud-provider-vsphere should ignore nodes with providerID prefix != 'vsphere://'

### ISSUE THREAD

**Issue by tommasopozzetti** [kubernetes/cloud-provider-vsphere#677]
### What happened?

When running with the in-tree cloud controller manager, each kubelet deals with its own node, allowing different kubelets in a cluster to have different cloud controller manager implementations.
When moving to this external implementation, the controller makes the assumption that every node in the cluster is a VM from vsphere, and if that is not the case it deletes non-found VMs as soon as the nodes are NotReady and it continuously prints out warnings that the VMs are not found when the nodes are Ready.

### What did you expect to happen?

The controller should allow multiple cloud providers to coexist in the same cluster. For example in the ClusterAPI case, both VMs and bare metal nodes might be required, and the bare metal nodes might be managed with a different provider such as BYOH or metal3.

Each different provider is already being differentiated by setting a unique providerID prefix on nodes, so it would be enough for the cloud-provider-vsphere to give some time when a new node pops up for it to be initialized before assuming it needs to delete it (in case it does not find that it needs to initialize it itself by finding the corresponding VM), and simply ignore initialized nodes that have a providerID prefix that is not the vsphere one (communicating that some other cloud controller manager is managing those). 

### How can we reproduce it (as minimally and precisely as possible)?

Create a ClusterAPI cluster with nodes from the CAPV provider and install the cloud-provider-vsphere. Add a node from a different provider (such as BYOH provider).

Notice cloud-provider-vsphere outputting warning logs that the VM cannot be found and deleting the node if it cannot become Ready in time.

### Anything else we need to know (please consider providing level 4 or above logs of CPI)?

A current workaround consists in disabling node deletion for cloud-provider-vsphere by setting env variable `SKIP_NODE_DELETION` as explained in [here](https://github.com/kubernetes/cloud-provider-vsphere/blob/1635728ecc0ecdedd4936b9ca45fd9482b4b6b76/docs/book/tutorials/disable-node-deletion.md) which allows the nodes to coexist by avoiding deletion when the bare metal nodes are NotReady, but it still generates lots of warning logs from cloud-provider-vsphere about VMs not being found. Furthermore, this workaround removes the useful feature of node deletion when a VM is deleted from the provider (though a similar behavior can be achieved, at least in the clusterAPI case, through the CAPI primitives instead and the CAPV provider). 

### Kubernetes version

1.23.5

### Cloud provider or hardware configuration

vSphere 7.0.3.00700

**Comment by lubronzhan** [comment]
Hi @tommasopozzetti it's a common issue on out of tree Cloud provider interface not just on CP vsphere 
Check out this issue https://github.com/kubernetes/kubernetes/issues/88820
It was proposed before but never got to work on.
I would say this is a feature improvement since we never claim CPI supporting single cluster with machines from multiple infra.  Each cloud provider by default only manage the mapping between node to machine on the existing infrastructure.
We could add a flag to ignore the machine with different providerID prefix as an alpha feature. So that you can at least use that in your env?
I call it an alpha feature since it relies on other cloud provider to manage the machines with different providerID prefix, which doesn't guarantee the cluster will be a good state

**Comment by tommasopozzetti** [comment]
Hi @lubronzhan thank you for taking a look and for the extra info!

I think your original proposal of an alpha feature would be reasonable though. While I agree that this is a shared effort between the CPI and CP vsphere, the assumption is that CPI will be running also in the other provider's cloud controller so it is still vsphere CP responsibility I think to ignore the nodes that are not specific to this CPI implementation to avoid throwing error for nodes that are not registered with this cloud provider.

The issue that remains and that indeed would be more on the CPI side would be that of node deletion (aka what to do for a node that is not registered yet and is found by vsphere not to be an existing VM). I think in the grand scheme of things, implementing something like providerClasses would be the right way to go, but in the meantime even just a simple (reasonable and possibly configurable as another alpha feature disabled by default) timeout before deleting nodes (to give them time to initialize if managed by another provider) would solve the issue.
CP vsphere can influence the decision on node deletion as you said by throwing proper errors like in [here](https://github.com/kubernetes/cloud-provider-vsphere/blob/dc6df7006aa857b1c48a05ef1061175b611bc424/pkg/cloudprovider/vsphere/instances.go#L169-L173). It could define two errors like `NodeInitializing` and `NodeNotManaged` to throw if a node is not found as a VM and we are still in the timeout zone or if a node is initialized with a different providerID. After timeout, if no other providerID has been set on the node, then CP vsphere can proceed with normal deletion.

Let me know what you think!
