### ISSUE TITLE
vSphere CPI never deletes a node since v1.23.3

### ISSUE THREAD

**Issue by braunsonm** [kubernetes/cloud-provider-vsphere#680]
### What happened?

Ever since this PR was merged: https://github.com/kubernetes/cloud-provider-vsphere/pull/650

The vSphere CPI will never delete VMs when it should. (Aka the VM is deleted from the vSphere inventory)

### What did you expect to happen?

The VM should be deleted from the cluster when removed from the vSphere Inventory

### How can we reproduce it (as minimally and precisely as possible)?

1. Create a VM
2. Join it to the cluster
3. Delete the VM from vSphere
4. Notice the errors:

```
virtualmachine.go:437] Failed to get VM Managed object with property summary. err: +ServerFaultCode: The object 'vm.VirtualMachine:vm-1234' has already ben deleted or has not been completely created
instances.go:183] instances.InstanceExistsByProviderID() check for node uid '"UUID"' by using vm-id '"VirtualMachine:vm-1234"' failed
```

### Anything else we need to know (please consider providing level 4 or above logs of CPI)?

The problem happens from this line: https://github.com/kubernetes/cloud-provider-vsphere/pull/650/files#diff-92a268f6c166473b915b494a0b5a8119529bc9562bbdbb1fa7b71f309efebda6R438

This response from the vSphere mof should not be treated as an error. This response indicates the VM is removed from the inventory.

### Kubernetes version

1.24

### Cloud provider or hardware configuration

N/A

### OS version

N/A

### Kernel (e.g. `uname -a`)

<details>

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### Others

<details>

</details>

**Comment by braunsonm** [comment]
cc @lubronzhan

**Comment by lubronzhan** [comment]
Oh good catch. https://github.com/kubernetes/kubernetes/pull/70291/files
I think this fix ignores the case that if VM is deleted, `GetVMMoList` will fail anyway. 
Also need to add a new E2E test for this case
Thanks for finding it

**Comment by lubronzhan** [comment]
@divyenpatel Since the PR I made here https://github.com/kubernetes/cloud-provider-vsphere/pull/650. It won't delete VM not in correct state but it also won't delete the Node whose VM that's deleted from vSphere.
Because [this](https://github.com/kubernetes/cloud-provider-vsphere/pull/650/files#diff-92a268f6c166473b915b494a0b5a8119529bc9562bbdbb1fa7b71f309efebda6R438) will only return error if VM is not found.
I'm gonna change this line to return VM doesn't exist without error if error is `vclib.IsManagedObjectNotFoundError(err)` I can create a dev build could you help check would this break your issue [here](https://github.com/kubernetes/cloud-provider-vsphere/issues/642) ?

**Comment by lubronzhan** [comment]
Created a dev image with this PR and verified that now the regression is gone

```
E0119 02:23:33.473341       1 datacenter.go:264] Failed to get VM managed objects from VM objects. vmObjList: [VirtualMachine:vm-77], properties: [summary.runtime.powerState], err: ServerFaultCode: The object 'vim.VirtualMachine:vm-77' has already been deleted or has not been completely created
E0119 02:23:33.473444       1 virtualmachine.go:438] VM's ManagedObject is not found, assume it's already deleted, err: +ServerFaultCode: The object 'vim.VirtualMachine:vm-77' has already been deleted or has not been completely created
I0119 02:23:33.473471       1 node_lifecycle_controller.go:164] deleting node since it is no longer present in cloud provider: test-md-0-jdghl-95f5c9d4c-xzmr7
I0119 02:23:33.474100       1 event.go:294] "Event occurred" object="test-md-0-jdghl-95f5c9d4c-xzmr7" fieldPath="" kind="Node" apiVersion="" type="Normal" reason="DeletingNode" message="Deleting node test-md-0-jdghl-95f5c9d4c-xzmr7 because it does not exist in the cloud provider"

```

@divyenpatel could you verify that this `projects.registry.vmware.com/lubron/cpi:test-flag-1` won't break your previous issue? Thank you

**Comment by braunsonm** [comment]
@lubronzhan thanks for being so quick with this one. Do you know if you'll be backporting this to 1.23?

**Comment by lubronzhan** [comment]
Let's wait for @divyenpatel 's response, don't want to break CSI's case.
Once that's done I will back port it. Because it will impact our product. Thanks for finding

**Comment by divyenpatel** [comment]
@lubronzhan I have shared the CPI image to our FVT team.

**Comment by lubronzhan** [comment]
Thank you!

**Comment by lubronzhan** [comment]
Hi @divyenpatel any update on this?

**Comment by lubronzhan** [comment]
Hi @divyenpatel we might have to merge the fix first since this issue is more critical

**Comment by braunsonm** [comment]
Hey @lubronzhan is there any update on this? It's still a pretty critical issue for us.

**Comment by lubronzhan** [comment]
Hi, I'm cutting the new release.

**Comment by lubronzhan** [comment]
Hi @braunsonm I just cut new releases
