### ISSUE TITLE
Add Certificate Authority (ca-file) as a Kubernetes ConfigMap reference for Helm Chart

### ISSUE THREAD

**Issue by benjvfr** [kubernetes/cloud-provider-vsphere#685]
### What would you like to be added?

Currently it seems not possible to add the certificate authority used by vCenter through the Helm Chart (the configmap set insecureFlag to true by default) for the vsphere-cpi pods to use.

In order to mitigate that, as mentioned in the guide (https://cloud-provider-vsphere.sigs.k8s.io/cloud_config.html), I tried to push the CA on the trust store of the each Kubernetes node VMs.
```
# The CA file to be trusted when connecting to vCenter. If not set, the node's
# CA certificates will be used.
ca-file = "/etc/kubernetes/vcenter-ca.crt"
```

But that seems not sufficient, because when the vsphere-cpi pods start, the govmomi process complains about x509 certificate signed by unknown authority :

```
E0201 14:52:48.352181       1 node_controller.go:229] error syncing 'node-01-control-plane-jcfcka': failed to get provider ID for node node-01-control-plane-jcfcka at cloudprovider: failed to get instance ID from cloud provider: Post "https://vcenter.example.org:443/sdk": x509: certificate signed by unknown authority, requeuing
```
The CA certificate has been added in /etc/ssl/certs/ca-certificates of each Kubernetes node VMs.

### Why is this needed?

Add a secure trusted connection to vCenter from the vsphere-cpi pods.

**Comment by lubronzhan** [comment]
Hi, do you mean you want to use the certificate instead of the tls thumbprint?

**Comment by benjvfr** [comment]
Yes, I would like to use the certificate authority (ca-file) attribute. The TLS thumbprint seems not available either in the Chart.

The idea would be to have a new value in the Helm Chart to indicate which secret in Kubernetes contains the CA that signed the certificate of the vCenter Server Appliance (or generate it like the vsphere-cloud-secret).

**Comment by benjvfr** [comment]
Yes exactly. It could be great to add the option to mount the vcenter CA to the CPI pod from a secret.

**Comment by lubronzhan** [comment]
I think it's a valid use case.
I added the option to set tlsthumbprint in 1.26 release.
For CA, we need to evaluate if we have bandwidth for it.
Feel free to contribute!
