### ISSUE TITLE
Question: which Helm chart to use?

### ISSUE THREAD

**Issue by ErikLundJensen** [kubernetes/cloud-provider-vsphere#746]
It looks like this repository is being updated and maintained again. For a while it looked like the vsphere-tmm Helm Chart was taking over. Maybe it was the former Bitnami employees that created the vsphere-tmm Helm Chart.

Looking forward will it be this repository or the vsphere-tmm repository that contains the official vmware helm charts for cloud-provider-vsphere?

Link to the vsphere-tmm helm chart:
https://github.com/vsphere-tmm/helm-charts/tree/master/charts/vsphere-cpi

**Comment by XudongLiuHarold** [comment]
Hi @ErikLundJensen , this repo is and will continue to be the official repo for the vsphere cloud provider

**Comment by XudongLiuHarold** [comment]
close this one for now, feel free to re-open it if you have further question, thanks!

/close
