### ISSUE TITLE
Kubernetes 1.28 support

### ISSUE THREAD

**Issue by sbueringer** [kubernetes/cloud-provider-vsphere#750]
Kubernetes 1.28 will be released next week.

Just wanted to open an issue to be able to follow the work for the cloud-provider-vsphere v1.28 release.

Are there already plans to publish a v1.28 version?

(context: We'll try to bump relatively quickly in Cluster API provider vsphere: https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues/2203)

**Comment by sbueringer** [comment]
cc @lubronzhan (sorry not sure who to cc :))

**Comment by lubronzhan** [comment]
Yeah usually I wait for CAPV to support it and have base image ready so I could test the change out

**Comment by sbueringer** [comment]
Ah sounds good. I think the last time we had a PR open and were waiting for the cloud-provider (not sure :D)

But then we'll just get back to you once we have the OVAs

**Comment by sbueringer** [comment]
@lubronzhan The new images are available now: https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/2233/files

We're currently trying them out via CAPV CI

**Comment by sbueringer** [comment]
cc @wyike ^^

**Comment by wyike** [comment]
waiting for controller-runtime 1.16 release with 1.28 k8s bumped

**Comment by sbueringer** [comment]
/reopen

Just until the release is out (?)

**Comment by wyike** [comment]
> /reopen
> 
> Just until the release is out (?)

Seeing we have a release with v1.28.0 tag out but no official release page published yet.

**Comment by sbueringer** [comment]
Looks to me like there is no 1.28.0 release: https://github.com/kubernetes/cloud-provider-vsphere/releases
