### ISSUE TITLE
CCM failed to clean up cache when deleting old nodes, causing new nodes to be unexpectedly deleted.

### ISSUE THREAD

**Issue by chenguo-github** [kubernetes/cloud-provider-vsphere#759]
### What happened?

- CCM failed to clean up nodeNameMap when deleting old nodes, causing new nodes to be unexpectedly deleted.

- The fix might be:

  Option 1: Clean up cache using node name directly. More specifically, change [this](https://github.com/kubernetes/cloud-provider-vsphere/blob/a6fbe8f588325a50ed384d045e30381b88b56474/pkg/cloudprovider/vsphere/nodemanager.go#L121-L130) part to
  
  
  // in case of a race condition that node with same name create happens before delete event,
	  // delete the node based on uuid
	  name := nm.getNodeNameByUUID(uuid)
	  if name != "" {
		  delete(nm.nodeNameMap, name)
	  } else {
		  klog.V(4).Info("node name: ", node.GetName(), " has a different uuid. Deleting this node from cache using node name directly.")
		  delete(nm.nodeNameMap, node.GetName())
	  }
	  delete(nm.nodeUUIDMap, uuid)
	  nm.nodeInfoLock.Unlock()
  
  Option 2: Look up the node name using node.UID instead of node.Status.NodeInfo.SystemUUID.

### What did you expect to happen?

nodeNameMap cleaned up correctly after node deletion.

### How can we reproduce it (as minimally and precisely as possible)?

- VM Recreate

  Old Node Obj not deleted at this time

- Kubelet Register

  Update node.Status.NodeInfo.SystemUUID in old node obj with a new value

- CCM Delete Old Node Obj

  Failed to clean up nodeNameMap using new SystemUUID [Ref](https://github.com/kubernetes/cloud-provider-vsphere/blob/a6fbe8f588325a50ed384d045e30381b88b56474/pkg/cloudprovider/vsphere/nodemanager.go#L123-L128)

- Trigger VM Restart

- Kubelet Register Again

  New node obj is created at this point, this new node obj is expected to be a valid one and should not be deleted.

- CCM Unexpectedly Delete New Node Obj

  CCM got an old providerID from nodeNameMap because it was not cleaned up previously. Old providerID doesn't match any underlying VM, so CCM deleted the new node obj unexpectedly.

### Anything else we need to know (please consider providing level 4 or above logs of CPI)?

2023-08-23T16:05:54.087418598Z I0823 16:05:54.087346       1 nodemanager.go:115] removeNode NodeName: 81ff17e25ec6-qual-335-1500f723, UID: 420aa1b2-3dc1-24d5-93cd-ee945c337130
2023-08-23T16:05:54.087425877Z I0823 16:05:54.087353       1 nodemanager.go:120] removeNode from UUID and Name cache. NodeName: 81ff17e25ec6-qual-335-1500f723, UID: 420aa1b2-3dc1-24d5-93cd-ee945c337130
2023-08-23T16:05:54.087430218Z I0823 16:05:54.087361       1 nodemanager.go:127] node name: 81ff17e25ec6-qual-335-1500f723 has a different uuid. Skip deleting this node from cache.

### Kubernetes version

1.26

### Cloud provider or hardware configuration

- args:
- --cloud-provider=vsphere
- --v=4
- --authentication-kubeconfig=/etc/kubernetes/admin.conf
- --authorization-kubeconfig=/etc/kubernetes/admin.conf
- --cloud-config=/etc/kubernetes/cloud-config/vsphere.conf
- --kubeconfig=/etc/kubernetes/admin.conf

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Kernel (e.g. `uname -a`)

<details>

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### Others

<details>

</details>

**Comment by chenguo-github** [comment]
Friendly ping

**Comment by xing-yang** [comment]
cc @lubronzhan

**Comment by lubronzhan** [comment]
cc @XudongLiuHarold could you help take a look?

**Comment by lubronzhan** [comment]
And @jingxu97 do you observe the issue with same CPI version?

**Comment by braunsonm** [comment]
I think we're also running into this issue on RKE2 CPI version 1.28.0

**Comment by XudongLiuHarold** [comment]
Will spend some time to take a look at this issue this week.

/assign

**Comment by braunsonm** [comment]
Glad to hear @XudongLiuHarold - Did you have a chance to take a look this week?

**Comment by XudongLiuHarold** [comment]
> Glad to hear @XudongLiuHarold - Did you have a chance to take a look this week?

Got occupied by company business for most of the time, took a look at this issue.

Hi @lubronzhan , I saw your comment here:
```go
	// in case of a race condition that node with same name create happens before delete event,
	// delete the node based on uuid
	name := nm.getNodeNameByUUID(uuid)
	if name != "" {
		delete(nm.nodeNameMap, name)
	} else {
		klog.V(4).Info("node name: ", node.GetName(), " has a different uuid. Delete this node from cache.")
		delete(nm.nodeNameMap, node.GetName())
	}
	delete(nm.nodeUUIDMap, uuid)
	nm.nodeInfoLock.Unlock()
```

Do you see any side effect if we still delete the node name from the cache map even the node name is not matching current deleting uuid anymore?

**Comment by lubronzhan** [comment]
The case in the comment shouldn't happen so I think it's ok to remove the second case.

**Comment by XudongLiuHarold** [comment]
> The case in the comment shouldn't happen so I think it's ok to remove the second case.

Gotcha, thanks!

I submit a fix here: https://github.com/kubernetes/cloud-provider-vsphere/pull/997
