### ISSUE TITLE
csi: support for storage vMotion and SDRS

### ISSUE THREAD

**Issue by codenrhoden** [kubernetes/cloud-provider-vsphere#77]

**Comment by dvonthenen** [comment]
I have working with the FCD team on issues relating to this.

/assign

**Comment by dvonthenen** [comment]
For the FCD driver in a "greenfield" deployment, the Storage vMotion (and subsequently the SDRS) functionality will work as expected. This was verified using 6.7u2 only.

It should be noted that this doesn't cover the before mentioned upgrade scenario (ie volumes created using the in-tree cloud provider to be migrated to this external CCM/CSI provider).

Question is should we claim this support on this CSI driver?

**Comment by codenrhoden** [comment]
I don't think we should, no...  at least not for FCD. If something comes along later that can to it, maybe that can be revisited. I'd recommend to close this for now. Thoughts?

**Comment by dvonthenen** [comment]
Good enough for me.

/close
