### ISSUE TITLE
VM GuestNicInfo is empty, requeuing: on Windows Worker Node

### ISSUE THREAD

**Issue by sonergzn** [kubernetes/cloud-provider-vsphere#772]
### What happened?

Hello, 

I am installing vsphere CSI and CPI in my hybrid K8 cluster in Rancher. In order to CSI driver work probably, the vsphere CPI should initialize nodes first. I have followed the [documentation](https://docs.vmware.com/en/VMware-vSphere-Container-Storage-Plug-in/3.0/vmware-vsphere-csp-getting-started/GUID-0AB6E692-AA47-4B6A-8CEA-38B754E16567.html) on vsphere website and assigned correct permissions. 

However, the CPI seems to be working on Linux worker but not on windows worker node.

As documentation suggested i am tainting nodes before CPI deployment. After that CPI initializes the nodes and removes taints but Windows node doesn't get initialized and and the taints remains on the windows node. 

### What did you expect to happen?

I was expecting that it just initializes the nodes as documentation says. 

### How can we reproduce it (as minimally and precisely as possible)?

I think to reproduce this error: you can just spin up a Rancher K8, with at least one windows node. 
Windows OS version: 2022 DataCenter.
Kubernetes Version 1.25.13

### Anything else we need to know (please consider providing level 4 or above logs of CPI)?

Logs: 

```
 node_controller.go:415] Initializing node <nodename> with cloud provider
2023-10-03T12:06:38.621590647Z I1003 12:06:38.621008       1 search.go:76] WhichVCandDCByNodeID nodeID: <nodename>
I1003 12:06:38.641564       1 search.go:208] Found node <nodename> as vm=VirtualMachine:vm-13139 in vc=192.168.x.x and datacenter=<DC name>
2023-10-03T12:06:38.641766393Z I1003 12:06:38.641597       1 search.go:210] Hostname: <nodename>, UUID: 423a172f-c77d-9d5c-ccea-b63c9cfbd95e
2023-10-03T12:06:38.641770094Z I1003 12:06:38.641613       1 nodemanager.go:126] Discovered VM using FQDN or short-hand name
E1003 12:06:38.644474       1 node_controller.go:229] error syncing '<nodename>': failed to get provider ID for node <nodename> at cloudprovider: failed to get instance ID from cloud provider: VM GuestNicInfo is empty, requeuing

```

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.28.0
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.25.13+rke2r1
```

</details>

### Cloud provider or hardware configuration

<details>
cloud-provider-vsphere-cpi-release-manager:v1.25.2

</details>

### OS version

Linux nodes: Ubuntu 22.04
Windows Node: 2022 DataCenter

### Kernel (e.g. `uname -a`)

<details>

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>
ContainerD version: 1.7 
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### Others

- Each node in the cluster is in the same subnet. 
- The needed permissions to talk to vsphere are provided by using a Service Account
- It is a Rancher k8. 
- Rancher Version is: 2.7.6
- Followed this as well: [cloud-provider-vsphere.sigs.k8s.io](https://cloud-provider-vsphere.sigs.k8s.io/tutorials/kubernetes-on-vsphere-with-helm)
Just want to mention also that it is possible that i am missing or overlooking something.
After a long research i couldn't find anything interesting on the internet.

**Comment by Zombro** [comment]
i don't use rancher, i build from scratch with kubeadm. experienced some similar issues though, interested in trying to help.

what CNI network provider are you using, flannel ? please share details.
this feels like your ethernet adapters are misconfigured.

other questions:
- is your windows vm domain joined ?
- if so, are you joining the windows node by it's FQDN ? not just it's `$(hostname)`

**Comment by lubronzhan** [comment]
We haven't actively tested windows node. But have you checked the vmtool version on your VM? VMTool is the one that generates those info on VM and CPI relies on those information to initialize node. If the vmtool version is too old on your VM, you can try upgrade those.

You can check what this guy did using govc command to debug similar error 
https://github.com/kubernetes/cloud-provider-vsphere/issues/576#issuecomment-1036032905

```
govc vm.info <vm name>
```

**Comment by adonskoy** [comment]
For anyone who have encountered the same problem. The issue is in the default configuration of the VMware Guest Agent

After launching the kubelet, the virtual machine has many interfaces generated by the CNI. Since there are too many of them, the agent does not return any information on the network interfaces. It is enough to exclude these interfaces in the config and then the VMware Guest Agent will correctly return information on the primary interfaces and the cloud provider will work as expected

Example config:
```
[guestinfo]
primary-nics=*
exclude-nics=docker*,cali*

[logging]
log = true

vmsvc.level = debug
vmsvc.handler = file
vmsvc.data = C:\Windows\Temp\vmsvc.log
```
