### ISSUE TITLE
csi: support for datastore cluster(s)

### ISSUE THREAD

**Issue by codenrhoden** [kubernetes/cloud-provider-vsphere#78]
Current in-tree solution does not support datastore clusters, only accessing a specific datastore.

**Comment by dougm** [comment]
Starting with support for placement (https://github.com/vmware/govmomi/issues/740)

**Comment by dougm** [comment]
Other than placement, we'll need to have a `DatastoreCluster` config option or add support to treat existing `Datastore` config option as a cluster.  cc @dvonthenen

**Comment by dvonthenen** [comment]
> Other than placement, we'll need to have a `DatastoreCluster` config option or add support to treat existing `Datastore` config option as a cluster. cc @dvonthenen

Yep, I have another PR to follow the current one open. I will tackle this when I remove the network section.

**Comment by jingxu97** [comment]
@dvonthenen wondering whether you have any new update for this support? Thank you!
