### ISSUE TITLE
Kubernetes 1.29 support

### ISSUE THREAD

**Issue by sbueringer** [kubernetes/cloud-provider-vsphere#789]
Just wanted to open an issue to be able to follow the work for the cloud-provider-vsphere v1.29 release.

Are there already plans to publish a v1.29 version?

(currently working on CAPV v1.29 support here: https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues/2564)

**Comment by sbueringer** [comment]
cc @wyike @lubronzhan (sorry not sure who to cc atm :))

**Comment by chrischdi** [comment]
FYI: Current versions of kube-vip require workarounds for the following issues:

* https://github.com/kube-vip/kube-vip/issues/692
* https://github.com/kube-vip/kube-vip/issues/684

**Comment by DanielXiao** [comment]
Please assign it to me.
