### ISSUE TITLE
Setup a CI job to push latest images to dockerhub

### ISSUE THREAD

**Issue by frapposelli** [kubernetes/cloud-provider-vsphere#8]
Makefile has a `make images` target that builds a CCM container based on `photon:2.0`.

It would be great to get the ball rolling with CI creating a job that runs a build and pushes the resulting image to dockerhub.

/kind feature

**Comment by dvonthenen** [comment]
This requires elevated privileges to modify the repo to hook in a CI system (like Travis CI for example).

**Comment by frapposelli** [comment]
The images will live on GCR, a GCP project is being provisioned.

**Comment by frapposelli** [comment]
Fixed by #61
