### ISSUE TITLE
csi: automatically promote/register existing virtual disk manager volumes to FCD

### ISSUE THREAD

**Issue by codenrhoden** [kubernetes/cloud-provider-vsphere#81]
In an upgrade scenario from in-tree to CSI, there may be existing volumes in use that were controlled by virtual disk manager. We want to promote these volumes by registering them as an FCD, which there is an API for.

**Comment by dvonthenen** [comment]
Will start taking a look at this and see how we can approach this.
/assign

**Comment by clintkitson** [comment]
Hello team,

I would like to focus this issue on investigation. I am not concerned about a migration capability being in place right now. Lets make sure we understand it, and the operational aspects of the CSI driver are setup to work if migration is implemented.

**Comment by dvonthenen** [comment]
Provided a document to stakeholders with observations relating to FCD promotion and also recommendations for an upgrade. Unless there are any objections, will close this issue out as we met the delivered objective.

**Comment by codenrhoden** [comment]
No objections here

**Comment by dvonthenen** [comment]
👍

/close
