### ISSUE TITLE
mdlint image is hosted in a VMware-owned registry

### ISSUE THREAD

**Issue by sbueringer** [kubernetes/cloud-provider-vsphere#826]
Hey folks,

just wanted to let you know that the mdlint image used (gcr.io/cluster-api-provider-vsphere/extra/mdlint:0.17.0) is hosted in a VMware-owned registry (/ GCP project). In CAPV we stopped using this image, so we won't maintain it anymore going forward.

We won't delete the image from the current registry, but we also cannot guarantee that it will exist forever there.

**Comment by sbueringer** [comment]
Just fyi, we'll keep the image around best effort. But I assume after the migration to the community-owned registry we will eventually cleanup/delete the gcp project that contains this image

**Comment by sbueringer** [comment]
cc @lubronzhan @XudongLiuHarold

**Comment by XudongLiuHarold** [comment]
Hi @sbueringer , we plan to migrate to the community-owned registry soon 😄, but need to work on cherrying pick recent changes to each release branches first

**Comment by sbueringer** [comment]
I think this is a different topic. It's just about usage of the mdlint image. Except if you meant moving over the mdlint image 😃

**Comment by XudongLiuHarold** [comment]
> I think this is a different topic. It's just about usage of the mdlint image. Except if you meant moving over the mdlint image 😃

Yeah, I mean we will migrate mdlint image to community-owned registry soon

**Comment by sbueringer** [comment]
Got it, sounds good!
