### ISSUE TITLE
Node resolution fails when other VMs have same VM-tools-reported guest host FQDNs

### ISSUE THREAD

**Issue by akutz** [kubernetes/cloud-provider-vsphere#87]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
The CCM fails during node look up when a VM is cloned, even with a new UUID, or when VMs have the same names. I’ve seen this occur from templates and OVFs. Most recently the CCM failed outright when I exported a VM as an OVF, imported that OVF as a new VM, and then stood up K8s on the new VM. Until I removed the original VM from the vSphere inventory, the CCM indicated that it could not resolve the node.

I **have** to think something is going on internal to vSphere itself that is causing issues when **one** or **more** of the following is true:

* Multiple VMs have the same names…
* Multiple VMs have the same host name as reported by the VM tools…
* VMs are deployed from the same template/OVF with new hardware, but have the same files, such as `/etc/machine-id`, that are read by VM tools and get added to the identity of the VM…
* Or…gremlins?

So my hypothesis seems to be close to something. Look at the UUIDs of the VMs:

```shell
[130]akutz@akutz-a01:Downloads$ govc vm.info -vm.ipath /SDDC-Datacenter/vm/Workloads/yakity-centos
Name:           yakity-centos
  Path:         /SDDC-Datacenter/vm/Workloads/yakity-centos
  UUID:         42301ab6-f495-1845-25ff-5190f281430a
  Guest name:   CentOS 7 (64-bit)
  Memory:       2048MB
  CPU:          1 vCPU(s)
  Power state:  poweredOn
  Boot time:    2018-10-17 21:40:26.36326 +0000 UTC
  IP address:   192.168.3.87
  Host:         10.2.32.4
```

```shell
[0]akutz@akutz-a01:Downloads$ govc vm.info -vm.ipath /SDDC-Datacenter/vm/Workloads/centos-ovf
Name:           centos-ovf
  Path:         /SDDC-Datacenter/vm/Workloads/centos-ovf
  UUID:         42301050-0acb-4e89-31d9-d10386eb4b6e
  Guest name:   CentOS 7 (64-bit)
  Memory:       2048MB
  CPU:          1 vCPU(s)
  Power state:  poweredOn
  Boot time:    2018-10-17 21:38:20.299679 +0000 UTC
  IP address:   192.168.3.52
  Host:         10.2.32.8
```

Now look at the errors from the CCM:

```shell
018-10-17T16:43:55.562713931-05:00 stderr F E1017 21:43:55.562586       1 node_controller.go:417] failed to find kubelet node IP from cloud provider
2018-10-17T16:44:05.571354049-05:00 stderr F I1017 21:44:05.571209       1 instances.go:107] instances.InstanceID() called with yakity.localdomain
2018-10-17T16:44:05.571374006-05:00 stderr F I1017 21:44:05.571230       1 instances.go:111] instances.InstanceID() CACHED with yakity.localdomain
2018-10-17T16:44:05.571379606-05:00 stderr F I1017 21:44:05.571236       1 instances.go:76] instances.NodeAddressesByProviderID() called with vsphere://42301050-0acb-4e89-31d9-d10386eb4b6e
2018-10-17T16:44:05.571384433-05:00 stderr F I1017 21:44:05.571241       1 instances.go:81] instances.NodeAddressesByProviderID() CACHED with 42301050-0acb-4e89-31d9-d10386eb4b6e
2018-10-17T16:44:05.571388477-05:00 stderr F E1017 21:44:05.571250       1 node_controller.go:417] failed to find kubelet node IP from cloud provider
```

The VM in question is `yakity-centos`. The CCM on `yakity-centos` *worked* when the following were true:

1. The VM `centos-ovf` was removed from the inventory
2. The VM `centos-ovf` was added back to the inventory with no information yet reported from VM tools since the VM had not yet been powered on

The CCM *failed* on `yakity-centos` when the following is true:

1. The VM `centos-ovf` is in the inventory and its host name has been reported by VM tools to be the same as the host name reported by `yakity-centos`

The `centos-ovf` VM doesn’t even have to be powered on to cause `yakity-ovf` to fail. All that is required is for `centos-ovf` to have been powered on at least *once* so that VM tools reports `centos-ovf`’s host name as the same as `yakity-ovf`.

When that’s the case, the CCM fails.

This makes complete sense when viewed in the context of the problem we saw a month ago with VM/host names.

**What you expected to happen**:
For the CCM to resolve the node as usual.

**How to reproduce it (as minimally and precisely as possible)**:
I cannot be sure, but it seems related to VMs that report the same guest host names via VM tools. On our VMC environment I can reproduce it with the VMs `centos-ovf` and `yakity-centos`. Please do not touch these VMs without looping me in, however, as I'm using them at the moment.

**Anything else we need to know?**:
My mama says I've the prettiest brown eyes...

I think I found an issue, maybe? In [`instances.go`](https://github.com/kubernetes/cloud-provider-vsphere/blob/master/pkg/cloudprovider/vsphere/instances.go), the `NodeAddresses` function uses [`FindVMByName`](https://github.com/kubernetes/cloud-provider-vsphere/blob/master/pkg/cloudprovider/vsphere/instances.go#L63) where the `NodeAddressesByProviderID` function uses [`FindVMByUUID`](https://github.com/kubernetes/cloud-provider-vsphere/blob/master/pkg/cloudprovider/vsphere/instances.go#L85). Why would `FindVMByName` ever be used?

I think this is the culprit:

```go
// ExternalID returns the cloud provider ID of the instance identified by
// nodeName. If the instance does not exist or is no longer running, the
// returned error will be cloudprovider.InstanceNotFound.
//
// When nodeName identifies more than one instance, only the first will be
// considered.
func (i *instances) ExternalID(ctx context.Context, nodeName types.NodeName) (string, error) {
	glog.V(4).Info("instances.ExternalID() called with ", nodeName)
	return i.InstanceID(ctx, nodeName)
}

// InstanceID returns the cloud provider ID of the instance identified by nodeName.
func (i *instances) InstanceID(ctx context.Context, nodeName types.NodeName) (string, error) {
	glog.V(4).Info("instances.InstanceID() called with ", nodeName)

	// Check if node has been discovered already
	if node, ok := i.nodeManager.nodeNameMap[string(nodeName)]; ok {
		glog.V(2).Info("instances.InstanceID() CACHED with ", string(nodeName))
		return node.UUID, nil
	}

	if err := i.nodeManager.DiscoverNode(string(nodeName), FindVMByName); err == nil {
		glog.V(2).Info("instances.InstanceID() FOUND with ", string(nodeName))
		return i.nodeManager.nodeNameMap[string(nodeName)].UUID, nil
	}

	glog.V(4).Info("instances.InstanceID() NOT FOUND with ", string(nodeName))
	return "", ErrNodeNotFound
}
```

`ExternalID` calls `InstanceID`, which always uses `FindVMByName`.

Maybe. I don’t know. I’m sure this all works 99.9999% of the time and there’s just some weird edge case I’m exacerbating. That and my lack of knowledge of the workflow probably means I’m making mountains out of molehills and seeing bugs where there aren’t any.

**Environment**:
- vsphere-cloud-controller-manager version: latest
- OS (e.g. from /etc/os-release): 
```
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```

- Kernel (e.g. `uname -a`):
```shell
Linux yakity.localdomain 3.10.0-862.14.4.el7.x86_64 #1 SMP Wed Sep 26 15:12:11 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

- Install tools: yakity
- Others:

**Comment by dvonthenen** [comment]
Hi @akutz you are correct that it is due to the FQDN. It is my understanding that the node names (aka the FQDN) must be unique... The cloud provider interface has functions for both ByExternalId and ByName. One issue is that we don't have any influence on which of those two functions are called and they are definitely both being used/called. As an example:
NodeAddresses(ctx context.Context, nodeName types.NodeName) ([]v1.NodeAddress, error)
NodeAddressesByProviderID(ctx context.Context, providerID string) ([]v1.NodeAddress, error)

I can try to change the implementation of `ExternalID(ctx context.Context, nodeName types.NodeName)` to discover based on UUID and see if the overall behavior changes with respect to which functions get called. Would definitely be worth the try... will take a look at doing that this morning.

**Comment by dvonthenen** [comment]
Yea, I took a look at the interface and the implementation again and there isn't anything that can be done to fix it. I was looking for possibly getting around it some how... The interface just simply requires that the node's FQDN be unique. But yea... you correctly identified the issue in the cloud interface, they use the node name to come up with the ExternalID which we selected to use the BIOS UUID which implies a 1 to 1 mapping therefore making the node FQDN unique.
```
ExternalID(ctx context.Context, nodeName types.NodeName)
InstanceID(ctx context.Context, nodeName types.NodeName)
```

Not sure what else can be done aside from changing the implementation the next time the cloud provider interface is changed which I think we should stay on top of and put/suggest this change when the time comes.

**Comment by akutz** [comment]
Hi @dvonthenen,

Ugh, but at the same time, I'm glad you were able to corroborate my findings. I wonder, what if we add a config property to the CCM so that the CCM is able to reduce the scope of its queries to a specific folder or RP?

**Comment by neolit123** [comment]
> the node names (aka the FQDN) must be unique...

this is true.

**Comment by dvonthenen** [comment]
@akutz and I had discussed this offline and it's one of those "it is what it is" kinda things. Will suggest an interface change when the interface gets reworked. That change should be something like kubernetes calls a cloud provider API passing in the entire NodeObject to a function called HowDoYouWantToUniquelyIdentifyMe(NodeObject) and then each provider can return the ID string and that string could be any from IPv4 to a MACAddress to NodeName to UUID. The point is the cloud provider can decide. Will keep an eye out for when we can make that change.

**Comment by dvonthenen** [comment]
It should be noted that if `--provider-id=vsphere://<uuid>` is set in the kubelet config on installation, this will workaround this particular issue.

**Comment by dvonthenen** [comment]
I think this is a pretty well-known requirement at this point and if unique hostnames cannot be accommodated (how do you do DNS anyways?), you can use `--provider-id=vsphere://<uuid>` in the kubelet config on each node to assign the provider ID to the node.

**Comment by dvonthenen** [comment]
I think this is a pretty well-known requirement at this point and if unique hostnames cannot be accommodated (how do you do DNS anyways?), you can use `--provider-id=vsphere://<uuid>` in the kubelet config on each node to assign the provider ID to the node.

/close
