### ISSUE TITLE
csi: read same config from file as is used with cloud provider

### ISSUE THREAD

**Issue by codenrhoden** [kubernetes/cloud-provider-vsphere#89]
When the config map is mounted to the container running the CSI plugin, the plugin should be capable of reading this file. This will allow the same config map to be used for the cloud provider and for CSI.

Since this is just a k/v flat file in the end, this does not make reading that config file K8s specific.

As much as we can, we want to be able to configure the plugin with env vars, but more advanced configs involving multiple vCenter's, for example, would be complicated through that method.

**Comment by dvonthenen** [comment]
PR submitted
https://github.com/kubernetes/cloud-provider-vsphere/pull/91
